### ISSUE TITLE
can not exit memtest process by pressing ESC key under uefi shell

### ISSUE THREAD

**Issue by qhbqyj** [memtest86plus/memtest86plus#104]
can not exit memtest process by pressing ESC key

**Comment by debrouxl** [comment]
Well, you'll have to help us before we can possibly help you ;)
Please tell us about your:
* memtest86+ version;
* keyboard <-> computer connection (mostly USB or PS/2, but maybe you're using a USB C <-> USB A adapter);
* keyboard model;
* computer / motherboard model;
* connector on the motherboard - there's usually a single PS/2 connector for the keyboard, but modern MBs have lots of USB connectors, and if some USB connectors work better than others, we'd need to know which ones;
* processor model.

**Comment by x86fr** [comment]
No answer.
