### ISSUE TITLE
USB Detection hang on Laptop Sony Vaio VPCCB3M1E due to Ricoh camera ID 05ca:18c0 buggy firmware

### ISSUE THREAD

**Issue by franck-888** [memtest86plus/memtest86plus#107]
When installed on usb stick
mt86plus_6.00b2_32.iso
hangs on below laptop after a cold boot (turn off and on), probably during autodetect, right after USB keyboards scanning. See picture 1-USB-hang.png

same happens when using another usb stick.

But memtest works well
- using same usb stick after reboot from linux (ie not from cold boot).
- launching from ssd using debian package from  http://ftp.de.debian.org/debian/pool/main/m/memtest86+/memtest86+_6.00~beta2-1_amd64.deb   See picture 2-deb-work.png
- using same usb stick on another computer.

[ Laptop ]
Sony Vaio VPCCB3M1E
ca. 2011, bios, no boot capability on gpt partitions
Description, french:
https://www.sony.fr/electronics/support/laptop-pc-vpc-series/vpccb3m1e/specifications

FYI memtest86 v4.3.7 works well.

Kind regards,
Franck

![1-USB-hang](https://user-images.githubusercontent.com/107723864/174403201-8c6bdd88-d70e-4f72-8f50-385d2b5cc5cc.png)
![2-deb-work](https://user-images.githubusercontent.com/107723864/174403227-23ceaceb-88c1-453b-a520-0acc27aff3b6.png)

**Comment by franck-888** [comment]
Hi, just in case that helps to figure out:

Outputs of following are attached:

lsusb -t >lsusb-t.txt   [lsusb-t.txt](https://github.com/memtest86plus/memtest86plus/files/8933005/lsusb-t.txt)
lsusb >lsusb.txt   [lsusb.txt](https://github.com/memtest86plus/memtest86plus/files/8933007/lsusb.txt)
lsusb -v >lsusb-v.txt 2>&1   [lsusb-v.txt](https://github.com/memtest86plus/memtest86plus/files/8933008/lsusb-v.txt)

lspci >lspci.txt   [lspci.txt](https://github.com/memtest86plus/memtest86plus/files/8933011/lspci.txt)
lspci -v >lspci-v.txt   [lspci-v.txt](https://github.com/memtest86plus/memtest86plus/files/8933012/lspci-v.txt)

decode-dimms >decode-dimms.txt   [decode-dimms.txt](https://github.com/memtest86plus/memtest86plus/files/8933016/decode-dimms.txt)

dmesg -t >dmesg-t.txt # manually cleaned UUID   [dmesg-t.txt](https://github.com/memtest86plus/memtest86plus/files/8933018/dmesg-t.txt)

Kind regards,
Franck

**Comment by martinwhitaker** [comment]
Please could you build Memtest86+ with the attached patch and report what is displayed.

[ehci-debug.patch.txt](https://github.com/memtest86plus/memtest86plus/files/9032824/ehci-debug.patch.txt)

**Comment by franck-888** [comment]
Thanks for working on this issue.

I applied your patch to the main branch.
= commit 6b998e82e77fe1334a3236afd45be25174806c72

cd build64/
make
make iso
make iso
dd if=memtest.iso of=/dev/MY_USB_KEY bs=1M ; sync

Attached picture is the result of booting on usb key after a cold boot.
![1-patched](https://user-images.githubusercontent.com/107723864/177005552-f03109d1-b552-483c-90ef-759005363f1a.png)


[ side note ]
2x make iso as
1st time:
  ...
  mcopy -s -i esp.img iso/EFI ::
  make: mcopy: No such file or directory
  make: *** [Makefile:155: esp.img] Error 127
  rm boot/mbr.s

2nd time:
make iso
  cp floppy.img iso/boot/floppy.img
  xorrisofs -pad -R -J -volid MT86PLUS_64 -graft-points -hide-rr-moved --grub2-mbr memtest.mbr \
  	  -b /boot/floppy.img --efi-boot --interval:appended_partition_2:all:: \
  	  -part_like_isohybrid -iso_mbr_part_type 0x00 -append_partition 2 0xef ./esp.img \
  	  -o ./memtest.iso /boot=./iso/boot /EFI=./iso/EFI
  ...
  ISO image produced: 3022 sectors
  Written to medium : 3022 sectors at LBA 0
  Writing to 'stdio:./memtest.iso' completed successfully.

Do you also get that ?

Kind regards,
Franck

**Comment by martinwhitaker** [comment]
Your build issue appears to be that you don't have mcopy (part of mtools) installed on your system. That means your ISO won't work for UEFI boot, but it won't affect legacy boot.

From your earlier lsusb report, it looks like the hang occurs when probing your USB camera. Could you test again with this additional patch to try to pin down where it is failing.

[debug2.patch.txt](https://github.com/memtest86plus/memtest86plus/files/9034399/debug2.patch.txt)

**Comment by franck-888** [comment]
I applied your 2nd patch on top of the 1st one to the main branch.

1st attached picture is the result of booting on usb key after a cold boot: it hangs.
![1-patch1and2-coldboot](https://user-images.githubusercontent.com/107723864/177042226-951e733e-3403-4f67-b07c-c49b91607cc3.png)


2nd attached picture is the result of booting on usb key after rebooting from linux: it gives further info and memtest starts when pressing a key.
I could not take picture of all the lines due to the scrolling, but seems they overlap with 1st picture.
![2-patch1and2-reboot_linux](https://user-images.githubusercontent.com/107723864/177042250-4f65e467-f747-47dd-a47d-4cca126ed259.png)


FYI sadly there is no option in (very limited) bios regarding camera (or any other USB device).

I have to correct my former statement:
'But memtest works well
- launching from ssd using debian package from  http://ftp.de.debian.org/debian/pool/main/m/memtest86+/memtest86+_6.00~beta2-1_amd64.deb   See picture 2-deb-work.png
'
as launching from ssd using debian package also hang after a cold boot.
Only works after a reboot from linux.


[ side note ]
Thanks I now installed mtools. It compiled without error.
Sorry I overlooked mtools in 'Build and Installation'. 

Kind regards,
Franck

**Comment by martinwhitaker** [comment]
This [Linux bug report](https://bugzilla.kernel.org/show_bug.cgi?id=207219) looks relevant.

**Comment by franck-888** [comment]
Yes I will try your patch. However I will only get access to sony laptop only by end of this week. I will report then.

**Comment by martinwhitaker** [comment]
Thanks for testing. As the keyboard is shown to be found in your screenshot, I can't at the moment think of a reason why key presses aren't being recognised.

**Comment by franck-888** [comment]
Thanks for the feedback.
FYI after a reboot from linux (= not cold boot), situation remains same:  started Memtest86+ using the "keyboard=buggy-usb" boot option => hangs at the 'press any key to continue'.
=> seems not a firmware init problem (the camera worked after reboot from linux).

**Comment by franck-888** [comment]
If that helps:
After a reboot from linux = warm boot,  without the "keyboard=buggy-usb": pressing a key allows to pass the 'press any key to continue'.
I did then several reboots from memtest (all warm boots), and took the picture below:
![1-warm_boot-no_options](https://user-images.githubusercontent.com/107723864/178117995-cc894bf8-d6cb-4107-b40e-9823aa52f783.jpg)

After taking the picture, pressing a key allows to pass the 'press any key to continue' and have memtest testing memory.

=> the patch 1- solves camera issue but has maybe a drawback regarding internal keyboard detection ?

For the records:
I applied following patches to the main branch:
1-usb_init_options_and_reset.patch.txt
[1-usb_init_options_and_reset.patch.txt](https://github.com/memtest86plus/memtest86plus/files/9077656/1-usb_init_options_and_reset.patch.txt)
2-debug2.patch.txt
3-ehci-debug.patch.txt

cd build64/
make grub-memtest.iso

**Comment by martinwhitaker** [comment]
Just to be sure it is really using the USB driver, are key presses still recognised if you do a warm boot with the `keyboard=usb` option?. If so, maybe it is the extra reset that is stopping it working. To check that, try replacing the previous patch with
````
--- a/system/usbhcd.c
+++ b/system/usbhcd.c
@@ -548,7 +548,7 @@ bool assign_usb_address(const usb_hcd_t *hcd, const usb_hub_t *hub, int port_num
     // the device address, which moves the device into Address state, and fetch the full device descriptor.
 
     size_t fetch_length = sizeof(usb_device_desc_t);
-    if (device_speed < USB_SPEED_HIGH) {
+    {
         fetch_length = 8;
         goto fetch_descriptor;
     }
````
and try a cold boot with the `keyboard=usb` option.

**Comment by franck-888** [comment]
1) to the main branch, git apply:
../patches/1a-usb_init_options_and_reset.patch.txt  [1a-usb_init_options_and_reset.patch.txt](https://github.com/memtest86plus/memtest86plus/files/9077812/1a-usb_init_options_and_reset.patch.txt)
../patches/2-debug2.patch.txt
../patches/3-ehci-debug.patch.txt
../patches/my1-add_grub_entries.patch.txt [my1-add_grub_entries.patch.txt](https://github.com/memtest86plus/memtest86plus/files/9077813/my1-add_grub_entries.patch.txt)


cd build64/
make grub-memtest.iso

"are key presses still recognised if you do a warm boot with the keyboard=usb option?"
Result: No. Keys are not recognised.


2) to the main branch, git apply:
../patches/1b-whatever_device_speed.txt [1b-whatever_device_speed.txt](https://github.com/memtest86plus/memtest86plus/files/9077814/1b-whatever_device_speed.txt)
../patches/2-debug2.patch.txt
../patches/3-ehci-debug.patch.txt
../patches/my1-add_grub_entries.patch.txt

"and try a cold boot with the keyboard=usb option."
Result: No. Keys are not recognised.
Tried after warm reboot from linux:
Result: No. Keys are not recognised.
On the screenshots I cannot see a difference cold vs warm

Cold + keyboard=usb:
![1-cold_arg_usb](https://user-images.githubusercontent.com/107723864/178120503-4ea6a35f-aa5a-46b9-8bf6-4b77ee65ee13.jpg)

Warm + keyboard=usb:
![2-warm-arg_usb](https://user-images.githubusercontent.com/107723864/178120506-17d39627-43f2-4620-8fe4-54d3799921ad.jpg)

**Comment by martinwhitaker** [comment]
I should have looked at your `lsusb -v` report! The USB keyboard being detected is a Logitech Unifying receiver. Are you using that for a wireless mouse?

**Comment by franck-888** [comment]
Yes I have a USB wireless transmitter used for wireless mouse. I did not use the wireless mouse (since a while) but I forgot to remove it since the beginning of this report. It was always plugged in.
I am going to try again above 2. with a cold boot with the keyboard=usb option to see what get reported.

**Comment by franck-888** [comment]
to the main branch, git apply:
../patches/1b-whatever_device_speed.txt 1b-whatever_device_speed.txt
../patches/2-debug2.patch.txt
../patches/3-ehci-debug.patch.txt
../patches/my1-add_grub_entries.patch.txt

Now without the USB mouse transmitter:

cold boot with the keyboard=usb option:
Result: Keys are not recognised & No keyboard detected.
![1-cold_boot-usb](https://user-images.githubusercontent.com/107723864/178121765-c59424c9-0162-4f6d-82aa-4fec685822ee.jpg)

cold boot with the keyboard=buggy-usb option:
Result: Keys are not recognised & No keyboard detected.
![2-cold_boot-buggy-usb](https://user-images.githubusercontent.com/107723864/178121769-dfb962ad-dd87-459c-8f8b-fd101c482b4d.jpg)


Is there possibility that the internal laptop keyboard is simply not using USB ? then how does memtest handle non-USB keyboards ?
Sorry that I did not unplug the USB mouse transmitter (I should have removed it).

**Comment by martinwhitaker** [comment]
Yes, commonly laptop keyboards will either use the legacy keyboard interface or connect to a SMbus controller.  For keyboards connected to a SMbus controller, we rely on the BIOS performing legacy keyboard emulation.

The (current) default for Memtest86+ is to use both legacy and USB keyboards, hence your keyboard is working if you don't specify a `keyboard=` option.

So I think everything is explained now. We have a viable workaround for the USB detection hang caused by the buggy camera device. And the best option for your laptop is to use the `keyboard=legacy` option, which as I mentioned, I plan to make the default when booting in legacy mode.

Thanks for all the testing.

**Comment by x86fr** [comment]
If needed, we can had a quirks list to set specific usb parameters/options based on DMI strings.

**Comment by franck-888** [comment]
Thanks for your explanations & having solved this bug.

To confirm:
Using the main branch, git apply:
../patches/1b-whatever_device_speed.txt 1b-whatever_device_speed.txt
../patches/2-debug2.patch.txt
../patches/3-ehci-debug.patch.txt
../patches/my1-add_grub_entries.patch.txt

Starting memtest
after cold boot
without additional grub option (no 'keyboard=')
without external usb devices plugged in & without external screen

Pressing a key allows to pass the 'press any key to continue'.
=> Memtest works, nice :)

For the record, now including dmidecode, under linux without external usb devices & without external screen:
[lsusb.txt](https://github.com/memtest86plus/memtest86plus/files/9078542/lsusb.txt)
[lsusb-t.txt](https://github.com/memtest86plus/memtest86plus/files/9078543/lsusb-t.txt)
[lsusb-v.txt](https://github.com/memtest86plus/memtest86plus/files/9078544/lsusb-v.txt)

[lspci.txt](https://github.com/memtest86plus/memtest86plus/files/9078546/lspci.txt)
[lspci-v-manually_cleaned.txt](https://github.com/memtest86plus/memtest86plus/files/9078547/lspci-v-manually_cleaned.txt)

[decode-dimms-manually_cleaned.txt](https://github.com/memtest86plus/memtest86plus/files/9078554/decode-dimms-manually_cleaned.txt)
[dmidecode-manually_cleaned.txt](https://github.com/memtest86plus/memtest86plus/files/9078549/dmidecode-manually_cleaned.txt)

[dmesg-t-manually_cleaned.txt](https://github.com/memtest86plus/memtest86plus/files/9078550/dmesg-t-manually_cleaned.txt)

**Comment by epman100** [comment]
> Thanks for your explanations & having solved this bug.

unfortunately for me, the bug is "not" solved with other Sony Vaio laptop models such as my brother's Sony Vaio VPCEB44FX laptop as it can't boot onto the usb device with any mt86plus_6.00 beta, either shows a black screen with nothing or a black screen saying "boot error" and a blinking cursor below the boot error message.

**Comment by franck-888** [comment]
Hi Martin,
Unfortunately 6.00b3 hand the same way as 6.00b2 did on coldboot without option, grub image.
As expected 6.00b3 starts well with keyboard=legacy option.

**Comment by x86fr** [comment]
`keyboard=legacy` will be the default option for final 6.00

**Comment by martinwhitaker** [comment]
`keyboard=legacy` is now the default when booted in legacy mode. If for some reason it is necessary to use `keyboard=usb`, the new `usbinit=2` option provides the workaround. So I think this issue can be closed now.
