### ISSUE TITLE
USB Detection hang on Intel D2500HN Motherboard

### ISSUE THREAD

**Issue by corvus1** [memtest86plus/memtest86plus#108]
Hangs on scanning for USB keyboard (not finding any, obviously).
And I'm not sure why it even wants to have a keyboard. It's not strictly necessary for the function.

**Comment by x86fr** [comment]
It doesn't and should start even if no keyboard is detected.

Can you please describe the exact model of motherboard and keyboard?

**Comment by corvus1** [comment]
It's an old intel d2500hn, and an even older nondescript Genuis PS/2 keyboard. Don't know if that helps.

**Comment by corvus1** [comment]
![IMG_20220618_211141](https://user-images.githubusercontent.com/4068104/174449462-bd31afed-7f95-47e1-8c79-6fe9bdce91dc.jpg)

and hangs there. If I connect a USB keyboard, then it works normally.

**Comment by corvus1** [comment]
I tried on a different, newer, PC, and there it does work with a PS/2 keyboard, although that is in UEFI mode.

**Comment by x86fr** [comment]
Can you try to pass the `noehci` parameter to the kernel with grub?

**Comment by corvus1** [comment]
I looked at it, and it's currently 
```
menuentry "memtest86+ 6.00 beta2" {
        linux16 /boot/memtest86plus/memtest64.bios
}
```
is linux16 okay or should I change it to `chainloader`? linux16 kinda feels weird to me. Not sure where I got it, it must've been there since 2013.

**Comment by corvus1** [comment]
Yeah, so, passing `noehci` worked, memtest runs normally. Will it interfere with its ability to work with a usb keyboard?

**Comment by martinwhitaker** [comment]
Providing your BIOS supports USB legacy keyboard emulation, you will still be able to use a USB keyboard. The preferred (and documented) boot option is `keyboard=legacy`. `noehci` was a temporary workaround, and may be removed in a future release.

**Comment by corvus1** [comment]
@martinwhitaker that works too, thanks. :-)

**Comment by corvus1** [comment]
So, apparently, what's happening in reality is that the memtest's USB keyboard driver hangs if no USB keyboard is present (at least on that motherboard). I assume both of these boot options disable the driver, and allow it to skip that step. 

However, on my other PC it works fine with no USB keyboards, so it might be hardware-specific, and probably difficult to reproduce on any other hardware.

**Comment by x86fr** [comment]
can you please provide more information about your hardware (motherboard model) and post a screenshot of Memtest86+ main screen when it's working?

**Comment by corvus1** [comment]
![IMG_20220619_145955](https://user-images.githubusercontent.com/4068104/174477767-57fb9a40-7b4a-4dee-8553-42601381804d.jpg)

Sure. But just out of idle curiosity, what's there to look at that I didn't tell you before?

**Comment by corvus1** [comment]
![Screenshot_20220619_153020](https://user-images.githubusercontent.com/4068104/174478734-833dd556-9937-4234-820f-3a97727c8989.png)

That's potentially a relevant part, because USB ports are connected through that. But it's not 100%, because on the other machine where I can't reproduce the problem, it's booting in UEFI mode, and in that mode it's possible that usb keyboards work differently.

**Comment by martinwhitaker** [comment]
Yes indeed, this is hardware specific and not reproducible on any of my machines. Please could you build Memtest86+ with the attached patch, and report what is displayed.

[ehci-debug.patch.txt](https://github.com/memtest86plus/memtest86plus/files/9032821/ehci-debug.patch.txt)

**Comment by corvus1** [comment]
@martinwhitaker The patch is meant for 6.00b2, right?

**Comment by martinwhitaker** [comment]
I created it from the head of the main branch, but it should apply cleanly to 6.00b2.

**Comment by corvus1** [comment]
![IMG_20220702_150106](https://user-images.githubusercontent.com/4068104/176998040-430a443f-7a8b-4320-b5fd-f617024f5a5f.jpg)

So, here's the output. Now to the bad news. If I press any key, it starts memtest and it works. Now it's going to be even trickier to diagnose.

**Comment by martinwhitaker** [comment]
Could you try commenting out each of the `print_usb_info()` calls the patch added in `ehci.c`, one by one, to see which one makes the difference.

**Comment by corvus1** [comment]
I'll try, but something tells me it's going to be this one:
`+usb_init_options_t usb_init_options = USB_DEFAULT_INIT | USB_DEBUG;`

**Comment by corvus1** [comment]
So, after a couple of rebuilds and reboots, turns out I was wrong. It's the last hunk that makes it work:

```
@@ -292,6 +293,7 @@ static bool scan_hub_ports(const usb_hcd_t *hcd, const usb_hub_t *hub, int *num_
         uint32_t port_status;
 
         get_hub_port_status(hcd, hub, port_num, &port_status);
+        print_usb_info( " Hub port %i status = %08x", port_num, (uintptr_t)port_status);
 
         // Check the port is powered up.
         if (~port_status & HUB_PORT_POWERED) continue;
```

removing it, and keeping the rest of the patch, I get this:
![IMG_20220702_162104](https://user-images.githubusercontent.com/4068104/177000711-983d95cd-12e2-405a-92ab-bde788b6c7c4.jpg)

Sorry for out of focus, hopefully it's readable.

**Comment by martinwhitaker** [comment]
I'm guessing it was actually this hunk that made the difference (it looks very similar!):
````
@@ -594,6 +595,7 @@ bool ehci_init(int bus, int dev, int func, uintptr_t base_addr, usb_hcd_t *hcd)
         if (num_keyboards >= MAX_KEYBOARDS) break;
 
         uint32_t port_status = read32(&op_regs->port_sc[port_idx]);
+        print_usb_info( " Root port %i status = %08x", 1+port_idx, (uintptr_t)port_status);
 
         // Check the port is powered up.
         if (~port_status & EHCI_PORT_SC_PP) continue;
````
Does making this change also make it work:
````
--- a/system/ehci.c
+++ b/system/ehci.c
@@ -599,7 +599,7 @@ bool ehci_init(int bus, int dev, int func, uintptr_t base_addr, usb_hcd_t *hcd)
         if (~port_status & EHCI_PORT_SC_PP) continue;
 
         // Check if anything is connected to this port.
-        if (~port_status & EHCI_PORT_SC_CCS) continue;
+        if (~port_status & EHCI_PORT_SC_CCS) { usleep(1); continue; }
 
         // Check for low speed device.
         if ((port_status & EHCI_PORT_SC_LS_MASK) == EHCI_PORT_SC_LS_K) {
````

**Comment by corvus1** [comment]
> I'm guessing it was actually this hunk that made the difference (it looks very similar!):

No, I quoted the exact hunk I removed, visual similarities notwithstanding.

> Does making this change also make it work:

I'll try it a bit later today.

**Comment by martinwhitaker** [comment]
> > I'm guessing it was actually this hunk that made the difference (it looks very similar!):
> 
> No, I quoted the exact hunk I removed, visual similarities notwithstanding. It's in a different file even.

Well, that's bizarre, because that code isn't being called. It suggests there's a memory corruption problem.

**Comment by corvus1** [comment]
So... should I replace that piece with a wait instead?

**Comment by martinwhitaker** [comment]
As that function is not being called, it shouldn't have any effect. But it would change the layout of the code in memory.

**Comment by corvus1** [comment]
So I tried the wait patch, it doesn't make it work, but the output changed:
![IMG_20220704_072040](https://user-images.githubusercontent.com/4068104/177076265-3e6d5749-a520-41dd-b46b-10e744208bdd.jpg)

Then for fun, I tried it the second time, and it found one more uhci controller:

![IMG_20220704_072200](https://user-images.githubusercontent.com/4068104/177076328-d9d2a63d-1b2c-4481-807e-5d3badb944d4.jpg)

**Comment by martinwhitaker** [comment]
Well, I still have no idea what's causing this, and as it's not behaving logically (a print statement in a function that is never called should not change the behaviour), there's no way I can debug this without having access to a machine that exhibits the fault.

However, the latest code defaults to only using the legacy keyboard on legacy-boot machines, which should mean Memtest86+ now works on that machine when using the default boot options.

**Comment by corvus1** [comment]
Yes, it is indeed masking the issue. And I suspect it would be hard to figure out even with access to the hardware. It must be some kind of race or memory corruption. I'd just keep it in mind for the next time it does something weird. :-)

**Comment by x86fr** [comment]
I'm almost sure that I have one of these board somewhere. I'm moving soon and almost all of my stuff has been packed, but I think I know where this board is. @martinwhitaker> I can send it to you once I find it if you want.

Let's leave this issue open a little longer. :)

**Comment by corvus1** [comment]
Just for fun, the board has a serial port, so we could bring out the big guns, and use GDB to debug it in hardware over serial.
