### ISSUE TITLE
Black screen Acer Aspire 5 laptop

### ISSUE THREAD

**Issue by RonHD** [memtest86plus/memtest86plus#114]
After disabling Secure Boot and putting the USB first in the boot order, it seems like Memtest86+ booted. The keyboard backlight stays on and the fan runs on high, suggesting it's doing something. But the screen stays black, so I can't tell whether the memory test is running. 

This is on an Acer Aspire A515-56, 8GB memory, 11th gen Intel Core i5-1135G7, iRIS Xe graphics, Intel GOP Driver 17.0.1064, BIOS version 1.26, HDD0 model WDC PC SN530 SDBPNPZ-256G-1114.

The USB was prepared on Windows 10 with the USB installer exe.

**Comment by x86fr** [comment]
Can you please try the latest nightly build available on memtest.org?

**Comment by cwsystem76** [comment]
I have a similar problem with a Coreboot laptop that I was going to report, but the dev build does fix the issue. Almost identical behavior, which appears to have been fixed.

**Comment by RonHD** [comment]
Sorry, I no longer have access to the laptop (I was helping a friend). I was able to test the memory with Memtest86, and didn't have time to get back to this.

**Comment by x86fr** [comment]
Should be fixed, but reopen if not.
