### ISSUE TITLE
Dev build as EFI or ISO fails on new Coreboot firmware, GRUB ISO works

### ISSUE THREAD

**Issue by cwsystem76** [memtest86plus/memtest86plus#115]
After building a new [Coreboot firmware](https://github.com/system76/firmware-open) for a System76 Oryx Pro (_oryp6_) for testing purposes, memtest stopped working on it. The first problem (booting to a black screen, re: https://github.com/memtest86plus/memtest86plus/issues/114) was resolved in recent dev builds (possibly related to https://github.com/memtest86plus/memtest86plus/pull/102), but now there's a new problem. Running the EFI executeable via _systemd-boot_ or using the regular ISO written to a USB stick results in an "Unexpected interrupt on CPU 0" error. The GRUB ISO version works normally when written to the same USB stick, and the system otherwise works normally.

![error](https://user-images.githubusercontent.com/96320715/178514766-a5d75a60-8510-4e40-bb46-cdbb3859daa7.jpg)

Running the EFI executable with a [loader configuration file](https://systemd.io/BOOT_LOADER_SPECIFICATION/) like this should allow me to pass parameters (if I'm reading https://github.com/memtest86plus/memtest86plus/issues/53 correctly), but these options do not change anything:

```
title memtest
efi /EFI/memtest/memtest.efi
options nosm nosmp
```

This is an unreleased debug firmware so it's entirely possible that this is a problem on our end, but we like to direct people to the open-source memtest instead of the commercial version (for obvious reasons) so this is somewhat important for us, and I'd like to be able to tell our engineers what's going on here if this is actually a problem with our Coreboot implementation.

I can also replicate this problem in a _qemu_ VM with our firmware, so I've also attached a copy of the build I'm using, which can be executed with the following command, with `memtest.iso` in this case being the dev ISO (non-GRUB) from https://memtest.org/download/nightly/memtest86plus-nightly-64.iso.zip:

```
qemu-system-x86_64 \
    -enable-kvm \
    -M q35 -m 4096 -vga std \
    -bios firmware.rom \
    -chardev stdio,mux=on,id=debug \
    -device isa-serial,index=2,chardev=debug \
    -device isa-debugcon,iobase=0x402,chardev=debug \
    -device pcie-root-port,bus=pcie.0,id=rp1 \
    -device pcie-pci-bridge,id=br1,bus=rp1 \
    -net none \
    -cdrom memtest.iso \
    "$@"
```
[system76 test firmware.zip](https://github.com/memtest86plus/memtest86plus/files/9094093/system76.test.firmware.zip)

**Comment by cwsystem76** [comment]
Can confirm with a build from the branch.

![image](https://user-images.githubusercontent.com/96320715/178555203-64fe45dd-8606-4b5c-b4d3-722bf5d64547.png)

I'm talking to our engineers about this to see if there's a quick fix or not.

**Comment by cwsystem76** [comment]
This is not going to be a quick fix, and our firmware team is a bit busy for a variety of reasons, so I've opened up an issue on our repo for the Coreboot firmware: https://github.com/system76/firmware-open/issues/336

I'd like to leave this issue open for the time being while we verify where the fix needs to go.

**Comment by martinwhitaker** [comment]
The bug causing the memory map to be empty is now fixed in the main branch.

**Comment by cwsystem76** [comment]
Looks like it's working now in the VM, at least. Thank you for taking a look at this so quickly.

![image](https://user-images.githubusercontent.com/96320715/178825828-cc252d39-abdd-4838-a628-71a8a0313b1f.png)

I'm going to test this on actual hardware next but that requires rebooting my work system. If that works then I'll go ahead and close out both issues.
