### ISSUE TITLE
(CPU?) Speed showing incorrectly

### ISSUE THREAD

**Issue by benkohler** [memtest86plus/memtest86plus#122]
I believe it's the CPU speed showing on the first line under the Memtest86+ header, mine is showing "CLK/temp 43344MHz 39/41*C" which can't be right.

![PXL_20220719_195321674](https://user-images.githubusercontent.com/2581799/179837806-5d1ae556-a423-45fb-8076-704a1bad692a.jpg)
.

**Comment by benkohler** [comment]
Hmm actually this (possibly broken) hardware froze up during the test and CLK looks better at next boot, so this might not be reproducible.  I'll reopen if it seems like I can reliably reproduce.

**Comment by debrouxl** [comment]
Thanks for the report :)
It's not just the reported CPU speed: cache and memory speeds are off by an order of magnitude as well. That could happen with a wrong timer base, although that's supposed to be less likely to occur now that memtest86+ supports both the PIT and the ACPIT.

#120 contains a patch for calibrating the busy loop, but I'm not convinced the corresponding code paths could be hit on your computer.

Dell 042P49 corresponds to Dell Optiplex 3010 DT. I happen to have access to several 7010 SFF similar computers, but I'm not at liberty to run whatever I want whenever I please on them.

**Comment by shr-project** [comment]
Congratz mate for 43Ghz :) I have similar issue, but from opposite side, the frequency seems correct for my TRX3970, but the Memory throughput looks very wrong (and sometimes it detects used XPM 3200Mhz correctly and sometimes it shows 2666Mhz).
![IMG_20220706_010907](https://user-images.githubusercontent.com/1234642/179839583-ddda51b0-19d8-4207-8b63-beeed25e4ca9.jpg)
![IMG_20220712_211737](https://user-images.githubusercontent.com/1234642/179839597-4e3e2d78-9670-4bb8-b57b-1f352d990cc4.jpg)

**Comment by x86fr** [comment]
Please open another issue for this Threadripper.

**Comment by 01e3** [comment]
Right, I don't think busy loop calibration will make any difference here. AFAIK this should be only called when TSC is not available and this is not the situation here.
