### ISSUE TITLE
Temperature reporting does not work on older Intel Core CPU

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#124]
Temperature reporting does not work on older Intel Core CPU.

So far I tested the following CPUs that don't work:
 - Core2 Quad Q9650 (Yorkfield, 45nm) - family: 0x6, model: 0x17, stepping: 0xa
 - Pentium Dual-Core E5200 (Wolfdale-3M, 45nm) - family: 0x6, model: 0x17, stepping: 0xa
 - Core2 Duo E6750 (Conroe, 65nm) - family: 0x6, model: 0xf, stepping: 0xb
 - Core 2 Duo E6420 (Conroe, 65nm) - family: 0x6, model: 0xf, stepping: 0x6

According to https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hwmon/coretemp.c those CPUs may require additional handing for example regarding Tjmax.

![image](https://user-images.githubusercontent.com/105136494/180451839-518323c2-db2c-4edb-a243-43e5e5392f65.png)

**Comment by 01e3** [comment]
Looks like 740df34656b122613f3e1f506daff6d16174a6c2 indeed fixed this, at least on Q9650 (Yorkfield) - model 0x17. Will check Wolfdale-3M and Conroe tomorrow.

![image](https://user-images.githubusercontent.com/105136494/180624620-a3623453-56e0-4e72-bc8e-438e821454b4.png)

**Comment by x86fr** [comment]
Should be fine. Reopen if issues.
