### ISSUE TITLE
ALi SMBus controllers not supported

### ISSUE THREAD

**Issue by InfoLibre** [memtest86plus/memtest86plus#126]
When I test these 2 computers with these RAM (see joined files for RAM model and name), RAM name isn't displayed
[Description (avec carte Wi-Fi  PCMCIA D-Link).odt](https://github.com/memtest86plus/memtest86plus/files/9172314/Description.avec.carte.Wi-Fi.PCMCIA.D-Link.odt)
[Description (avec carte Wi-FI PCMCIA OvisLink).odt](https://github.com/memtest86plus/memtest86plus/files/9172315/Description.avec.carte.Wi-FI.PCMCIA.OvisLink.odt)
.

**Comment by x86fr** [comment]
These laptops seem to use ATI chipsets, which are unsupported for SPD decofing (RAM specs display) at this time.

**Comment by x86fr** [comment]
PS : Please confirm the chipset used by these laptop.

**Comment by InfoLibre** [comment]
Here are lspci and lsusb command result files. Do you need another info?

[lspci.txt](https://github.com/memtest86plus/memtest86plus/files/9175199/lspci.txt)

[lsusb.txt](https://github.com/memtest86plus/memtest86plus/files/9175200/lsusb.txt)

**Comment by debrouxl** [comment]
I didn't notice it previously, but the output of `lspci -nn` would be more accurate than the output of `lspci`, though the latter can be encoded back to numeric IDs, at least if there are no duplicates :)

**Comment by InfoLibre** [comment]
```
00:00.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD/ATI] RS100 Host Bridge [1002:cab0] (rev 13)
00:01.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD/ATI] RS100 AGP Bridge [1002:700f] (rev 01)
00:02.0 USB controller [0c03]: ULi Electronics Inc. USB 1.1 Controller [10b9:5237] (rev 03)
00:06.0 Multimedia audio controller [0401]: ULi Electronics Inc. M5451 PCI AC-Link Controller Audio Device [10b9:5451] (rev 02)
00:07.0 ISA bridge [0601]: ULi Electronics Inc. M1533/M1535/M1543 PCI to ISA Bridge [Aladdin IV/V/V+] [10b9:1533]
00:08.0 Modem [0703]: ULi Electronics Inc. M5457 AC'97 Modem Controller [10b9:5457]
00:09.0 Network controller [0280]: Broadcom Inc. and subsidiaries BCM4306 802.11b/g Wireless LAN Controller [14e4:4320] (rev 02)
00:0a.0 CardBus bridge [0607]: O2 Micro, Inc. OZ6933/711E1 CardBus/SmartCardBus Controller [1217:6933] (rev 01)
00:0a.1 CardBus bridge [0607]: O2 Micro, Inc. OZ6933/711E1 CardBus/SmartCardBus Controller [1217:6933] (rev 01)
00:0c.0 FireWire (IEEE 1394) [0c00]: Texas Instruments TSB43AB21 IEEE-1394a-2000 Controller (PHY/Link) [104c:8026]
00:10.0 IDE interface [0101]: ULi Electronics Inc. M5229 IDE [10b9:5229] (rev c4)
00:11.0 Bridge [0680]: ULi Electronics Inc. M7101 Power Management Controller [PMU] [10b9:7101]
00:12.0 Ethernet controller [0200]: National Semiconductor Corporation DP83815 (MacPhyter) Ethernet Controller [100b:0020]
01:05.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] RS100 [Radeon IGP 320M] [1002:4336]
```

**Comment by debrouxl** [comment]
Thanks. AFAICS from Linux driver sources, the SPD-capable SMBus controller in that list would be 10b9:7101, supported by Linux drivers/i2c/busses/i2c-ali15x3.c or drivers/i2c/busses/i2c-ali1535.c drivers.

Does `decode-dimms` from Linux i2c-tools print the expected SPD information, after the appropriate modules (probably "eeprom", "i2c-ali1535" and "i2c-ali15x3") are `modprobe`'d, if necessary ?

**Comment by InfoLibre** [comment]
Do you need other informations? Which command must I type?

**Comment by InfoLibre** [comment]
If you want, we could use https://www.dwservice.net.

**Comment by debrouxl** [comment]
Sorry. The more usable version of my previous comment is
1) `apt install i2c-tools` on Debian and derivatives, `yum install i2c-tools` (or `dnf install i2c-tools` on recent versions) on Fedora and RHEL derivatives, or whatever installs Linux i2c-tools on your system: these tools are packaged by mainstream Linux distros under the `i2c-tools`, `i2c_tools` or suchlike names, and if not, you can compile it from the tarballs linked at https://www.kernel.org/pub/software/utils/i2c-tools/ ;
2) `modprobe eeprom; modprobe at24; modprobe i2c-ali1535; modprobe i2c-ali15x3` , if I'm not mistaken;
3) `decode-dimms` .

Thanks in advance :)

**Comment by InfoLibre** [comment]
```
# decode-dimms version 4.2

Memory Serial Presence Detect Decoder
By Philip Edelbrock, Christian Zuckschwerdt, Burkart Lingner,
Jean Delvare, Trent Piepho and others


Decoding EEPROM: /sys/bus/i2c/drivers/eeprom/0-0051
Guessing DIMM is in                              bank 2
Kernel driver used                               eeprom

---=== SPD EEPROM Information ===---
EEPROM Checksum of bytes 0-62                    OK (0xA7)
# of bytes written to SDRAM EEPROM               128
Total number of bytes in EEPROM                  256
Fundamental Memory type                          DDR SDRAM
SPD Revision                                     0.0

---=== Memory Characteristics ===---
Maximum module speed                             266 MT/s (PC2100)
Size                                             256 MB
Banks x Rows x Columns x Bits                    4 x 13 x 9 x 64
Ranks                                            2
Voltage Interface Level                          SSTL 2.5V
Module Configuration Type                        No Parity
Refresh Rate                                     Reduced (7.8 us) - Self Refresh
Supported CAS Latencies                          2.5T, 2T
Supported CS Latencies                           0
Supported WE Latencies                           1
tCL-tRCD-tRP-tRAS                                2.5-3-3-6 as DDR-266
                                                 2-2-2-5 as DDR-200
Minimum Cycle Time                               7.5 ns at CAS 2.5
                                                 10 ns at CAS 2
Maximum Access Time                              0.75 ns at CAS 2.5
                                                 0.75 ns at CAS 2

---=== Timings at Standard Speeds ===---
tCL-tRCD-tRP-tRAS as DDR-266                     2.5-3-3-6
tCL-tRCD-tRP-tRAS as DDR-200                     2-2-2-5

---=== Timing Parameters ===---
Address/Command Setup Time Before Clock          0.90 ns
Address/Command Hold Time After Clock            0.90 ns
Data Input Setup Time Before Clock               0.50 ns
Data Input Hold Time After Clock                 0.50 ns
Minimum Row Precharge Delay (tRP)                20.00 ns
Minimum Row Active to Row Active Delay (tRRD)    15.00 ns
Minimum RAS# to CAS# Delay (tRCD)                20.00 ns
Minimum RAS# Pulse Width (tRAS)                  45.00 ns

---=== Module Attributes ===---

---=== Manufacturing Information ===---
Manufacturer                                     Nanya Technology
Manufacturing Location Code                      0x03
Part Number                                      NT256D64SH8B0GM-75
Manufacturing Date                               2003-W29


Number of SDRAM DIMMs detected and decoded: 1

```

**Comment by debrouxl** [comment]
Good, thanks. `lsmod | grep i2c`, which I forgot previously ?

So at least, gathering information from a computer such as yours *can* be done; however, don't hold your breath about an implementation: memtest86+ already supports nearly all of the widespread SMBus controller models for recent computers, and this isn't one of them... The PCI IDs (10b9:7101, 10b9:1563) could still be documented.

**Comment by InfoLibre** [comment]
i2c_algo_bit           16384  1 radeon
i2c_ali15x3            20480  0
i2c_ali1535            20480  0

**Comment by debrouxl** [comment]
Good, this confirms that one of the two ALi SMBus controller Linux drivers is used on your MB.
I've started building up a simple patch which documents these PCI IDs and several others I didn't spend time documenting earlier. I'll send it later.

**Comment by InfoLibre** [comment]
I tested again with Memtest86+ v6.00, RAM name isn't displayed. Does it will be solved in next version?

**Comment by debrouxl** [comment]
_If_ someone contributes a tested driver (\*) for this ancient and nowadays scarce SMBus controller memtest86+ by the time the next version is released, yes, it _could_ technically be solved in the next version.

With drivers for i801, piix4 (including its modern AMD variants) and even the nForce2 family, though most PCI IDs are commented out in the latter until someone contributes a test result (\*), memtest86+ now supposedly supports the vast majority of computers produced in the past couple decades, per #86 , based on a relatively large sample size of CPU-Z validation results.
Unpaid maintainers are more likely to spend time fixing known holes in the coverage for modern computers, e.g. those which require special SMBus controller access / un-hiding methods ( #65 , for instance), than spend time obtaining hardware and adding fresh tested drivers (\*) for SMBus controllers present only in old computers :)

\*: with screenshots showing that it retrieves the expected information from RAM sticks, and that the computer is not broken afterwards, in that decode-dimms or one of the Windows tools can still successfully use the SMBus controller.

**Comment by x86fr** [comment]
The last commits added support for ALi chipsets (M1563-series and M1543/35/33).
