### ISSUE TITLE
 Temperature reporting does not work on older AMD K8 CPUs

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#128]
Temperature reporting does not work on older AMD K8 CPUs

So far I have tested the following CPUs that don't work:
 - AMD Athlon(tm) Dual Core Processor 5400B
 - AMD Athlon(tm) 64 X2 Dual Core Processor 5000+

Both of them are family: 0xf, model: 0x6b, stepping: 0x2

![image](https://user-images.githubusercontent.com/105136494/180575651-2489a6de-6ec2-48fc-b4d8-6e9a66ebecc1.png)

**Comment by x86fr** [comment]
Check first if they're not concerned by the infamous Errata 319 (see #3)

**Comment by 01e3** [comment]
Ah, was not aware about #3, reading...

That said, both Linux and HwMonitor seem to be happy:

```
# sensors k8temp-*
k8temp-pci-00c3
Adapter: PCI adapter
Core0 Temp:   +28.0Â°C
Core0 Temp:   +32.0Â°C
Core1 Temp:   +32.0Â°C
Core1 Temp:   +29.0Â°C

# ls -l /sys/bus/pci/drivers/k8temp/????:??:*
lrwxrwxrwx 1 root root 0 Jul 23 15:42 /sys/bus/pci/drivers/k8temp/0000:00:18.3 -> ../../../../devices/pci0000:00/0000:00:18.3
```


![image](https://user-images.githubusercontent.com/105136494/180610137-f508129b-765b-4fe2-8cd7-0cf5b23aa7a6.png)
