### ISSUE TITLE
Memtest reports too many threads & no T on old Core2Duo 6600

### ISSUE THREAD

**Issue by franck-888** [memtest86plus/memtest86plus#129]
6.00b3 reports

- 4 threads instead of 2.   C2D 6600 is a dual core with 1 thread/core, no SMT.
- No CPU T.    Linux Sensors reports T.

![c2d](https://user-images.githubusercontent.com/107723864/180617064-90377be6-4198-487a-b16e-117c11a1a917.jpg)

Yes CPU is originally 2.40GHz and is overclocked to 3.0GHz.

[cpu-lscpu.txt](https://github.com/memtest86plus/memtest86plus/files/9174326/cpu-lscpu.txt)
[cpu-proc_cpuinfo.txt](https://github.com/memtest86plus/memtest86plus/files/9174328/cpu-proc_cpuinfo.txt)
[sensors.txt](https://github.com/memtest86plus/memtest86plus/files/9174332/sensors.txt)

[dmesg-t.txt](https://github.com/memtest86plus/memtest86plus/files/9174329/dmesg-t.txt)
[dmidecode.txt](https://github.com/memtest86plus/memtest86plus/files/9174330/dmidecode.txt)
[lspci.txt](https://github.com/memtest86plus/memtest86plus/files/9174331/lspci.txt)

Kind regards,
Franck

**Comment by debrouxl** [comment]
Thanks for the detailed report :)
Could you provide the output of `cpuid -r` ?
#125 and #129 might be related.

**Comment by x86fr** [comment]
SMT issue should be solved with latest commit.

**Comment by x86fr** [comment]
Temperature reporting should also be available on Core 2 Duo/Quad now.

**Comment by franck-888** [comment]
Argh, report was not detailed enough then :)
Here it is:
[cpu-cpuid-r.txt](https://github.com/memtest86plus/memtest86plus/files/9175210/cpu-cpuid-r.txt)
[cpu-cpuid.txt](https://github.com/memtest86plus/memtest86plus/files/9175211/cpu-cpuid.txt)

I will build with latest commit.

Kind regards,
Franck

**Comment by franck-888** [comment]
Build with latest commit 740df34656b122613f3e1f506daff6d16174a6c2
Yes both Threads No & CPU T got already solved vs b3.
Nice.
Issue closed.
![build](https://user-images.githubusercontent.com/107723864/180634907-d0a02c49-2068-4809-83e8-0c2e8a23a6ab.jpg)
.
