### ISSUE TITLE
Sometimes the "FAIL" banner stays on the screen

### ISSUE THREAD

**Issue by virxkane** [memtest86plus/memtest86plus#130]
Sometimes the "FAIL" banner stays on the screen and it hides first memory failure description.
![IMG_0180_s](https://user-images.githubusercontent.com/36960933/180655645-4083b563-e8c0-4e0b-ba41-cb0344b07889.JPG)

Version 6.00b3 from Gentoo Linux.

**Comment by x86fr** [comment]
Does it disappear if you press any key?

**Comment by virxkane** [comment]
I didn't press anything, I just didn't know about it :)

**Comment by virxkane** [comment]
But I noticed that if the first pass succeeds and the "PASS" banner appears, then if the next pass fails, the banner automatically disappears, which seems right to me.

**Comment by x86fr** [comment]
Got it. The banner must be removed and re-displayed after each error is printed on the background to avoid this.

**Comment by different55** [comment]
I was unable to dismiss the FAIL banner at all, either by pressing any key or pressing F1 to bring up then close the configuration menu. Without being able to see and without any logs being saved anywhere, I can't feed the badram-formatted output back into my system.

**Comment by 01e3** [comment]
> I was unable to dismiss the FAIL banner at all, either by pressing any key or pressing F1 to bring up then close the configuration menu. Without being able to see and without any logs being saved anywhere, I can't feed the badram-formatted output back into my system.

Does the keyboard work at all? What happens when you hit Esc for example?

**Comment by different55** [comment]
It works as you'd expect, all functions function. Escape immediately reboots, F1 temporarily dismisses the banner while the configuration menu is up, but it reappears when the menu is closed. Space locks and unlocks the scroll lock.

**Comment by x86fr** [comment]
There is 2 options : 1/ add a menu option to permanently disable the banner 2/ never show the banner again when the user pressed a key to make it disappear.

**Comment by 01e3** [comment]
Perhaps we can also consider adding both a menu option (or a hotkey?) and boot option to enable/disable it and/or having the banner disabled by the default, in case most users prefer it to be off?

That said, "it reappears when the menu is closed" seems like a bug?

**Comment by different55** [comment]
Right, right now it's never even dismissed. But I think either moving the banner somewhere it doesn't cover results/info or changing its form entirely are the "best" options not considering the implementation side of things. It's possible to make status visible at a glance from a distance without slapping a pop-up on there. Using background colors or borders for example. Support for log files would also be a workaround, and just handy to avoid transcription errors.

**Comment by x86fr** [comment]
> Perhaps we can also consider adding both a menu option (or a hotkey?) and boot option to enable/disable it and/or having the banner disabled by the default, in case most users prefer it to be off?
> 
> 
> 
> That said, "it reappears when the menu is closed" seems like a bug?

No. It works as expected. The FAIL banner is displayed when errors are detected.

PS: the original issue described by OP is solved and this will be closed. Discussion on banner behavior can be moved to a new discussion.
