### ISSUE TITLE
Possible incorrect DRAM timing info

### ISSUE THREAD

**Issue by virxkane** [memtest86plus/memtest86plus#131]
I am testing AMD R748G2400U2S DDR4 modules, below is a photo of this module:
![IMG_0191 (topview) noexif](https://user-images.githubusercontent.com/36960933/180944746-b33c4f84-4e66-4389-84cc-322685045991.JPG)

According to the label at 2400 MHz, timings 16-16-16-36 should be used.
In BIOS, it shows approximately the same timings:
![IMG_0195 (BIOS RAM)](https://user-images.githubusercontent.com/36960933/180947193-50de80f7-6bb6-40d9-a637-9b1c9ee4635d.JPG)

I dump SPD from this modules using i2c-tools, see bellow:
[r7spd.zip](https://github.com/memtest86plus/memtest86plus/files/9187396/r7spd.zip)

```
$ decode-dimms -x r7spd.dump 
# decode-dimms version 4.3

Memory Serial Presence Detect Decoder
By Philip Edelbrock, Christian Zuckschwerdt, Burkart Lingner,
Jean Delvare, Trent Piepho and others


Decoding EEPROM: r7spd.dump

---=== SPD EEPROM Information ===---
EEPROM CRC of bytes 0-125                        OK (0xE542)
# of bytes written to SDRAM EEPROM               384
Total number of bytes in EEPROM                  512
Fundamental Memory type                          DDR4 SDRAM
SPD Revision                                     1.0
Module Type                                      UDIMM
EEPROM CRC of bytes 128-253                      OK (0x53D8)

---=== Memory Characteristics ===---
Maximum module speed                             2400 MT/s (PC4-19200)
Size                                             8192 MB
Banks x Rows x Columns x Bits                    16 x 16 x 10 x 64
SDRAM Device Width                               8 bits
Ranks                                            1
Primary Bus Width                                64 bits
AA-RCD-RP-RAS (cycles)                           16-16-16-39
Supported CAS Latencies                          25T, 20T, 19T, 18T, 17T, 16T, 15T, 14T, 13T, 12T, 11T, 10T, 9T

---=== Timings at Standard Speeds ===---
AA-RCD-RP-RAS (cycles) as DDR4-2400              16-16-16-39
AA-RCD-RP-RAS (cycles) as DDR4-2133              15-15-15-35
AA-RCD-RP-RAS (cycles) as DDR4-1866              13-13-13-31
AA-RCD-RP-RAS (cycles) as DDR4-1600              11-11-11-26
```
Ok, at 2400 we should see 16-16-16-39, but memtest86+ shows 15-15-15-35:
![IMG_0182 (info)](https://user-images.githubusercontent.com/36960933/180946026-f497365a-13c1-4c5b-98a1-86e02fe6375a.JPG)

It looks like the timings in the program are displayed wrong.

**Comment by x86fr** [comment]
I will investigate. It seems this module is 2400 XMP but 2133 JEDEC and the timings reported are the JEDEC timings instead of the XMP timings.

**Comment by x86fr** [comment]
#151 Duplicate
