### ISSUE TITLE
Wrong display in DDR5

### ISSUE THREAD

**Issue by coolboy-code** [memtest86plus/memtest86plus#133]
![image](https://user-images.githubusercontent.com/58176165/181214408-592d4338-9e83-40f2-9c74-947c66547f4b.png)
Using 6.00b3 

DIMMs are Samsung DDR5 64 GB (2x32GB) 5200MHz.

**Comment by x86fr** [comment]
Asus motherboard ?

Please post a screenshot of memtest86+ running.

**Comment by coolboy-code** [comment]
![ddr5testcas9](https://user-images.githubusercontent.com/58176165/181470393-8cbc1364-9364-424d-8136-9d43fceaafe9.JPG)
It looks like case9 failed

**Comment by debrouxl** [comment]
Besides the many memory errors (which erase the motherboard identification DMI data, if any was found and displayed), the CPU identification string is wacky...
Is it a case of memory addresses below 1 MB being corrupted on some motherboards ?
https://www.phoronix.com/news/Linux-Always-Reserve-1MB
https://www.phoronix.com/news/Windows-Reserves-First-1MB-RAM

**Comment by x86fr** [comment]
This looks like Engineering Sample of unreleased Sapphire Rapids CPU. This platform is still under development so firmware issue may happen.

**Comment by martinwhitaker** [comment]
There looks to be some display corruption on the second error line. Was the display scrolling when you took the screenshot (i.e. is that just an artefact of the photograph)?

21 seconds to reach test 9 seems implausible.

Could you enable tracing (F7 in the configuration menu, or `trace` on the boot command line) and provide a screenshot of the information printed out before the tests start.

**Comment by coolboy-code** [comment]
I ONLY run the test 9. The display was scrolling when I take a photo.

**Comment by OneOfMany07** [comment]
Would it be smart to show some kind of debug information when users get odd initial results like the first image?  Where there isn't any identification information listed.

Being able to send you an automatically generated file with all the needed information, or tell you which field confused the software (without digging by the user) would be handy.

Just a Quality Of Life enhancement to consider.  I don't know how often the above issue happens, outside of brand new platforms that you'll eventually add anyway.

**Comment by x86fr** [comment]
Beta hardware under NDA
