### ISSUE TITLE
Showing incorrect DDR4 ram speed

### ISSUE THREAD

**Issue by franck-888** [memtest86plus/memtest86plus#134]
Possibly linked to #131.

6.00b3 + git up to 8a3cac8133430b93129341c3c6105b7f1d3a5445
shows
"RAM 1200MHz (DDR4-2400) CAS 13-15-15-30"

RAM is indeed certified & sold as DDR4-2400,
but in this config it is supposed to run at DDR4-2133 as
- UEFI BIOS shows 2133MHz (all in 'auto')
- Skylake max support is 2133MHz
- dmidecode reports 2133 MT/s

RAM: https://www.corsair.com/us/en/Categories/Products/Memory/VENGEANCE-LPX/p/CMK32GX4M2A2400C14#tab-tech-specs
motherboard: Gigabyte Technology Co., Ltd. H170-HD3, BIOS F22e 03/09/2018
Skylake Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz

![skylake](https://user-images.githubusercontent.com/107723864/181559845-88532b4a-8fac-4411-883d-20b0d8c01a52.jpg)
![IMG_2115](https://user-images.githubusercontent.com/107723864/181560005-a1b67a2e-3a92-43e8-9c29-2e9ebbbd077b.jpg)
![IMG_2116](https://user-images.githubusercontent.com/107723864/181560089-1eb95906-8e1d-4498-b347-ffea89b6aaee.jpg)

Linux logs:
[decode-dimms.txt](https://github.com/memtest86plus/memtest86plus/files/9211137/decode-dimms.txt)
[dmidecode.txt](https://github.com/memtest86plus/memtest86plus/files/9211139/dmidecode.txt)

[cpu-lscpu.txt](https://github.com/memtest86plus/memtest86plus/files/9211135/cpu-lscpu.txt)
[lspci.txt](https://github.com/memtest86plus/memtest86plus/files/9211290/lspci.txt)
[dmesg-t.txt](https://github.com/memtest86plus/memtest86plus/files/9211304/dmesg-t.txt)

Kind regards,
Franck

**Comment by x86fr** [comment]
"RAM:" line shows the maximum capability of your memory, NOT how fast it is currently running. 
Later, the current memory frequency (if available) will be displayed as "IMC: xxxxxxx" instead of "RAM: xxxxxx"
