### ISSUE TITLE
Застревает проверка оборудования 

### ISSUE THREAD

**Issue by Terminator151186** [memtest86plus/memtest86plus#141]
1 cpu Тип ЦП	QuadCore Intel Core i5-2400, 3300 MHz (33 x 100)
2 Системная плата	Gigabyte GA-PH67A-UD3
3 ddr3 	
4 запускаю через grub4dos, у меня legacy bios
video https://disk.yandex.ru/i/Ae48DAX_IkGamQ

**Comment by birdie-github** [comment]
Title: **Stuck in hardware enumeration**

Body:

Running via grub2dos, I've got legacy BIOS.

**Comment by martinwhitaker** [comment]
Try the latest nightly build. That will default to using legacy keyboard emulation if you have a legacy BIOS.

**Comment by Terminator151186** [comment]
а где скачать (and where to download) new version 
old version https://www.memtest.org/ 

![11](https://user-images.githubusercontent.com/110594846/184286892-450683c3-0e41-4271-bd85-ab1d5f00c840.jpg)

**Comment by martinwhitaker** [comment]
Go to https://memtest.org/dev, and "Download Nightly Build".

**Comment by Terminator151186** [comment]
проверил, все работает
checked, everything works
