### ISSUE TITLE
v6 not ready for production

### ISSUE THREAD

**Issue by j18ter** [memtest86plus/memtest86plus#142]
The Website describes v6 as not ready for production, but labels all versions
prior to v6 as obsolete. This seems inconsistent. Which version is recommended
for 'production'?

**Comment by x86fr** [comment]
That's correct. Final Memtest86+ 6.00 should be released in 2/3 weeks (early septembre max). No version are actually recommended for production.

**Comment by Fantu** [comment]
@x86fr hi, I don't see a 6.00 branch (with fixes-only commits) and about new version there will be an "rc" (release candidate) first or a final 6.00 release directly?

**Comment by x86fr** [comment]
Maybe a short-lived rc. That will depend of the feedbacks from betatesters (next sunday). I still have some minor patchs to commit, but they're only bug fixes.

**Comment by Fantu** [comment]
thanks for reply, I recently used it only for some quick tests and I have not encountered problems and on the debian bugtracker users did not open any bugs related to the package of version 6.00 in debian experimental (https://tracker.debian.org/pkg/memtest86+), anyway is probable that only few users use the experimental
on final release will be migrate to debian unstable (and if not critical bug will be detected after some days to testing), but probably also on the rc, I'll ask the other debian maintainer what he think

**Comment by x86fr** [comment]
Sounds good :)

**Comment by epman100** [comment]
> That's correct. Final Memtest86+ 6.00 should be released in 2/3 weeks (early septembre max). No version are actually recommended for production.

looks like that won't happen anytime soon as it's already September 22, the first official day of the **autumn/fall season** and summer just ended on Wednesday September 21 and there does not seem to be a "final" 6.0 release yet
