### ISSUE TITLE
6 core / 12 threads X5660 reported as "16 Cores 32 Threads SMP: 12T"

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#144]
6 core / 12 threads X5660 reported as "16 Cores 32 Threads SMP: 12T"

![obraz](https://user-images.githubusercontent.com/105136494/184455015-b213fa61-2cd3-4386-9ee7-56f9ec7eaaf3.png)

12T looks OK, but "16 Cores 32 Threads" not so much?

**Comment by x86fr** [comment]
Can you please report the sspec for your CPU? Ie: SLBV6.

(Also, 4 memory modules on a 3-channel platform look odd. Maybe just for testing?)

**Comment by 01e3** [comment]
Yes, it is SLBV6, but running with 166MHz instead of 133MHz BLCK: https://valid.x86.fr/f8d7ry

Sadly, the 3rd memory channel is physically broken with some burnt / broken pins. :( Otherwise, I would be running it with 6x8GB=48GB. Removing and soldering a new DDR3 slot is beyond my skills. :/

**Comment by x86fr** [comment]
For some obscure reasons, this CPU does support Extended Topology Information but DOES NOT support x2APIC.

Please try this patch:

```
diff --git a/system/cpuid.c b/system/cpuid.c
index aef3924..848d391 100644
--- a/system/cpuid.c
+++ b/system/cpuid.c
@@ -181,7 +181,11 @@ void cpuid_init(void)
        case 'G':
         if (cpuid_info.vendor_id.str[7] == 'T') break; // Transmeta
         // Intel
-        if (cpuid_info.max_cpuid >= 0xB && cpuid_info.flags.x2apic) {
+        if (cpuid_info.max_cpuid >= 0xB) {
+            cpuid(0xB, 0, &reg[0], &reg[1], &reg[2], &reg[3]);
+        }
+
+        if ((reg[1] & 0xFF) != 0) { // Check if Extended Topology Information is available (CPUID.0BH:EBX[15:0])

             // Populate Hybrid Status (CPUID 7.EDX[15]) for Alder Lake+
             cpuid(0x7, 0, &reg[0], &reg[1], &reg[2], &reg[3]);
```

**Comment by 01e3** [comment]
This patch made Memtest86+ running on my obscure system happy - 6 Cores 12 Threads SMP: 12T

![obraz](https://user-images.githubusercontent.com/105136494/184695230-2fc8a551-be73-4ff2-a7e4-573e5accc6a8.png)

**Comment by debrouxl** [comment]
x2APIC is from Nehalem onwards, whereas a xAPIC mode was introduced with the P4.

**Comment by 01e3** [comment]
X5660 is Westmere-EP so Nehalem.

**Comment by x86fr** [comment]
Correct. That's why it's quite strange it does not support x2apic (even more as a Xeon). I checked on cpu-z if the bios is to blame (the P6T only supports Core officially), but even on server boards, the x2apic flag is not set.
