### ISSUE TITLE
Doesn't support for arm64?

### ISSUE THREAD

**Issue by nguoido** [memtest86plus/memtest86plus#147]
I would like to ask can memtest86 plus run arm64?

**Comment by debrouxl** [comment]
Nope, x86 & x86_64 only for now.
See also #143: porting a program like memtest86+ to a new ISA represents a significant amount of work. Also, while making memtest86+ work under QEMU in AArch64 system mode would be a good first step, that's not enough for programs performing low-level hardware access: testing memtest86+ requires lots of real-world hardware, in the hands of the developers, for direct testing in a short feedback loop...

**Comment by swiftgeek** [comment]
Anything would be better than memtester under linux, and uboot can provide UEFI environment

**Comment by 13werwolf13** [comment]
if the developers plan to work on aarch64, I am ready to act as a tester on Pinebook Pro and RaspberryPi
i use opensuse which even on aarch64 offers full grub, from there i download the pcmemtest compiled in the repository by the venerable [Dead_Mozay](https://build.opensuse.org/package/show/home:Dead_Mozay/pcmemtest)

**Comment by x86fr** [comment]
Aarch64 support in #626
