### ISSUE TITLE
SPD timing parsing logic seems to be wrong

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#151]
It seems that the timing parsing in Memtest86+ is not correct, at least for DDR/DDR2/DDR3/DDR4 - I have not tested SDRAM/RDRAM and DDR5 yet.

For a number of dumps I collected in https://github.com/memtest86plus/memtest86plus/pull/150, only one (with XMP profile) seems to be parsed properly, for the others:
- DDR4-M393A1G40EB1-CPB: should be reported as DDR4-2133 15-15-15-36 not DDR4-2132 14-14-14-35
- DDR4-M393A1G40EB1-CRC: should be reported as DDR4-2400 17-17-17-39 not 16-16-16-38
- DDR3-M392B1G73DB0-YH9: should be reported as DDR3-1333 9-9-9-24 not 8-8-8-22
- DDR3-M378B5173DB0-CK0: should be reported as DDR3-1600 11-11-11-28 not 10-10-10-26
- DDR3-M391B1G73QH0-CMA: should be reported as DDR3-1866 13-13-13-32 not 10-10-10-28
- DDR2-GoldenEmpire-1.spd: should be reported as DDR2-800 5-5-5-15 not 3-5-5-14
- DDR2-2G-UDIMM.spd: should be reported as DDR2-800 5-5-5-15 not 3-5-5-18

```
This is now very easy to reproduce with the new spd-decode tool:
$ ./spd-decode data/DDR4-M393A1G40EB1-CPB.spd |grep Type:
Type: DDR4-2132 14-14-14-35

$ decode-dimms -x <(xxd data/DDR4-M393A1G40EB1-CPB.spd)|grep 'as .DR'|head -1
AA-RCD-RP-RAS (cycles) as DDR4-2133              15-15-15-36

```

**Comment by x86fr** [comment]
All of this has already been identified and fixed. New code is undergoing betatesting on several thousands of different DRAM.
It should be committed soon.

**Comment by 01e3** [comment]
Ah, fantastic, thank you!

I suspect you want to submit this first, so I'll need to re-do my smbus / spd patches once done?

**Comment by x86fr** [comment]
Yes, the fixes have been applied to the old code, but it's easy to migrate to your new code.

> I have not tested SDRAM/RDRAM and DDR5 yet.

DDR5 also have some issues. Latest logs for example:

```
#1024 - CPU-Z 2.01 : 16GB DDR5-6000 XMP - Kingston KF560C40-16 (2022-W16) - CAS 40-40-40-80
#1024 - Memtest86+ : 16GB DDR5-6000 XMP - Kingston KF560C40-16 (2022-W16) - CAS 40-40-40-80 - OK!
#1025 - CPU-Z 2.01 : 16GB DDR5-5600 XMP - Corsair CMK32GX5M2B5600C36 - CAS 36-36-36-76
#1025 - Memtest86+ : 16GB DDR5-5600 XMP - Corsair CMK32GX5M2B5600C36 - CAS 36-36-36-76 - OK!
#1026 - CPU-Z 2.01 : 16GB DDR5-5600 XMP - Kingston KF556C40-16 (2022-W29) - CAS 40-40-40-80
#1026 - Memtest86+ : 16GB DDR5-5600 XMP - Kingston KF556C40-16 (2022-W29) - CAS 40-40-40-80 - OK!
#1027 - CPU-Z 2.01 : 16GB DDR5-5600 XMP - Kingston KF556C40-16 (2022-W29) - CAS 40-40-40-80
#1027 - Memtest86+ : 16GB DDR5-5600 XMP - Kingston KF556C40-16 (2022-W29) - CAS 40-40-40-80 - OK!
#1028 - CPU-Z 2.01 : 16GB DDR5-4800 XMP - Crucial CT16G48C40U5.M8A1 (2022-W04) - CAS 40-39-39-77
#1028 - Memtest86+ : 16GB DDR5-4800 XMP - Crucial CT16G48C40U5.M8A1 (2022-W04) - CAS 40-38-38-76 - MISMATCH FOR ID iumb9h
#1029 - CPU-Z 2.01 : 16GB DDR5-4800 XMP - Crucial CT16G48C40U5.M8A1 (2022-W04) - CAS 40-39-39-77
#1029 - Memtest86+ : 16GB DDR5-4800 XMP - Crucial CT16G48C40U5.M8A1 (2022-W04) - CAS 40-38-38-76 - MISMATCH FOR ID 5xkvri
#1030 - CPU-Z 2.01 : 16GB DDR5-6200 XMP - Corsair CMT32GX5M2X6200C36 - CAS 36-39-39-76
#1030 - Memtest86+ : 16GB DDR5-6200 XMP - Corsair CMT32GX5M2X6200C36 - CAS 36-39-39-76 - OK!
#1031 - CPU-Z 2.01 : 16GB DDR5-5200 XMP - Kingston KF552C40-16 (2022-W24) - CAS 40-40-40-80
#1031 - Memtest86+ : 16GB DDR5-5200 XMP - Kingston KF552C40-16 (2022-W24) - CAS 40-40-40-80 - OK!
#1032 - CPU-Z 2.01 : 16GB DDR5-6200 XMP - Corsair CMT32GX5M2X6200C36 - CAS 36-39-39-76
#1032 - Memtest86+ : 16GB DDR5-6200 XMP - Corsair CMT32GX5M2X6200C36 - CAS 36-39-39-76 - OK!
#1033 - CPU-Z 2.01 : 16GB DDR5-4800 - Samsung M425R2GA3BB0-CQKOL (2022-W11) - CAS 40-39-39-77
#1033 - Memtest86+ : 16GB DDR5-4800 - Samsung M425R2GA3BB0-CQKOL (2022-W11) - CAS 38-38-38-76 - MISMATCH FOR ID azd1bk
#1034 - CPU-Z 2.01 : 8GB DDR5-4800 - Samsung M425R1GB4BB0-CQKOL (2022-W07) - CAS 40-39-39-77
#1034 - Memtest86+ : 8GB DDR5-4800 - Samsung M425R1GB4BB0-CQKOL (2022-W07) - CAS 38-38-38-76 - MISMATCH FOR ID gy4wwr
#1035 - CPU-Z 2.01 : 16GB DDR5-5200 XMP - Corsair CMK32GX5M2B5200C40 - CAS 40-40-40-77
#1035 - Memtest86+ : 16GB DDR5-5200 XMP - Corsair CMK32GX5M2B5200C40 - CAS 40-40-40-77 - OK!
#1036 - CPU-Z 2.01 : 16GB DDR5-5200 XMP - Corsair CMK32GX5M2B5200C40 - CAS 40-40-40-77
#1036 - Memtest86+ : 16GB DDR5-5200 XMP - Corsair CMK32GX5M2B5200C40 - CAS 40-40-40-77 - OK!
#1037 - CPU-Z 2.01 : 8GB DDR5-4800 - Samsung M425R1GB4BB0-CQKOL (2022-W20) - CAS 40-39-39-77
#1037 - Memtest86+ : 8GB DDR5-4800 - Samsung M425R1GB4BB0-CQKOL (2022-W20) - CAS 38-38-38-76 - MISMATCH FOR ID bqivid
#1038 - CPU-Z 2.01 : 16GB DDR5-5600 XMP - Corsair CMK32GX5M2B5600C36 - CAS 36-36-36-76
#1038 - Memtest86+ : 16GB DDR5-5600 XMP - Corsair CMK32GX5M2B5600C36 - CAS 36-36-36-76 - OK!
#1039 - CPU-Z 2.01 : 16GB DDR5-5200 XMP - Corsair CMK32GX5M2B5200C40 - CAS 40-40-40-77
#1039 - Memtest86+ : 16GB DDR5-5200 XMP - Corsair CMK32GX5M2B5200C40 - CAS 40-40-40-77 - OK!
#1040 - CPU-Z 2.01 : 16GB DDR5-4800 - Samsung M425R2GA3BB0-CQKOD (2021-W46) - CAS 40-39-39-77
#1040 - Memtest86+ : 16GB DDR5-4800 - Samsung M425R2GA3BB0-CQKOD (2021-W46) - CAS 38-38-38-76 - MISMATCH FOR ID ucygqq
#1041 - CPU-Z 2.01 : 16GB DDR5-5200 XMP - Corsair CMT32GX5M2B5200C40 - CAS 40-40-40-77
#1041 - Memtest86+ : 16GB DDR5-5200 XMP - Corsair CMT32GX5M2B5200C40 - CAS 40-40-40-77 - OK!
#1042 - CPU-Z 2.01 : 16GB DDR5-6000 XMP - A-DATA AX5U6000C4016G-B (2022-W10) - CAS 40-40-40-76
#1042 - Memtest86+ : 16GB DDR5-6000 XMP - A-DATA AX5U6000C4016G-B (2022-W10) - CAS 40-40-40-76 - OK!
#1043 - CPU-Z 2.01 : 8GB DDR5-4800 - Micron MTC4C10163S1SC48BA1 (2022-W09) - CAS 40-39-39-77
#1043 - Memtest86+ : 8GB DDR5-4800 - Micron MTC4C10163S1SC48BA1 (2022-W09) - CAS 38-38-38-76 - MISMATCH FOR ID 4g2p29
#1044 - CPU-Z 2.01 : 8GB DDR5-4800 - Samsung M425R1GB4BB0-CQKOD (2022-W05) - CAS 40-39-39-77
#1044 - Memtest86+ : 8GB DDR5-4800 - Samsung M425R1GB4BB0-CQKOD (2022-W05) - CAS 38-38-38-76 - MISMATCH FOR ID um7nsp
```

Almost all of them are due to rounding errors.

**Comment by x86fr** [comment]
Here are the parsing results of your SPD dumps with PR #150 applied:

> DDR4-M393A1G40EB1-CPB: should be reported as DDR4-2133 15-15-15-36 not DDR4-2132 14-14-14-35
`-> 8GB DDR4-2133 - Samsung M393A1G40EB1-CPB (2017-W10) - CAS 15-15-15-36` **[FIXED]**

> DDR4-M393A1G40EB1-CRC: should be reported as DDR4-2400 17-17-17-39 not 16-16-16-38
`-> 8GB DDR4-2400 - Samsung M393A1G40EB1-CRC (2018-W05) - CAS 17-17-17-39` **[FIXED]**

> DDR3-M392B1G73DB0-YH9: should be reported as DDR3-1333 9-9-9-24 not 8-8-8-22
`-> 8GB DDR3-1333 - Samsung M392B1G73DB0-YH9 (2014-W20) - CAS 9-9-9-24` **[FIXED]**

> DDR3-M378B5173DB0-CK0: should be reported as DDR3-1600 11-11-11-28 not 10-10-10-26
`-> 4GB DDR3-1600 - Samsung M378B5173DB0-CK0 (2014-W16) - CAS 11-11-11-28` **[FIXED]**

> DDR3-M391B1G73QH0-CMA: should be reported as DDR3-1866 13-13-13-32 not 10-10-10-28
`-> 8GB DDR3-1866 - Samsung M391B1G73QH0-CMA (2015-W22) - CAS 13-13-13-32` **[FIXED]**

> DDR2-GoldenEmpire-1.spd: should be reported as DDR2-800 5-5-5-15 not 3-5-5-14
`-> 1GB DDR2-800 - GEIL CL4-4-4 (2009-W44) - CAS 5-5-5-15` **[FIXED]**

> DDR2-2G-UDIMM.spd: should be reported as DDR2-800 5-5-5-15 not 3-5-5-18
`-> 2GB DDR2-800 - Kingston 2G-UDIMM (2009-W09) - CAS 5-5-5-18` **[MISMATCH]**

Where does the 5-5-5-15 you expect comes from? The correct value seems to be 5-5-5-18 to me.

**Comment by 01e3** [comment]
Sorry about this, must be a copy & paste error:

tCL-tRCD-tRP-tRAS as DDR2-800                    5-5-5-18
tCL-tRCD-tRP-tRAS as DDR2-666                    5-5-5-15

It is indeed -18 for -800.

**Comment by x86fr** [comment]
Great! So everything seems fixed :)

**Comment by x86fr** [comment]
PS: beware of decode-dimms for DDR2 DIMMs. It doesn't seem to support EPP and reports wrong timings for high-end overclocking/gaming modules (Geil/G.skill/Corsair).

**Comment by 01e3** [comment]
Yes, I'm very aware of this. Perhaps this is also an argument why it may make sense to providing spd-decode tool using Memtest86+ SPD parsing logic from smbus.c. :)

**Comment by 01e3** [comment]
While working on updating my patches I noticed that the XMP profile in DDR3-9905403-440.A00LF.spd is now parsed as DDR3-1600 9-9-9-15, where it should be DDR3-1600 9-9-9-27 (@1.65V) according to https://www.kingston.com/datasheets/KHX1600C9D3X2K2_8GX.pdf.

Also see: http://valid.x86.fr/b89lst

I found this problem by running the sefltests from https://github.com/memtest86plus/memtest86plus/pull/150

I wonder if this change is correct:

```
-        tns  = (uint16_t)(get_spd(slot_idx, 194) & 0xF0) << 4 |
-               get_spd(slot_idx, 195);
+        tns  = (uint16_t)((get_spd(slot_idx, 194) & 0xF0) << 3 |
+               get_spd(slot_idx, 195));
```

If I change it back to "4" spdi.tRAS gets calculated as 27.

Since we are here, there is orphaned ";" next to this section. I can add the following patch to my PR if you agree with the problem and the fix:

```
         // Row Active Time
-        tns  = (uint16_t)((get_spd(slot_idx, 194) & 0xF0) << 3 |
+        tns  = (uint16_t)((get_spd(slot_idx, 194) & 0xF0) << 4 |
                get_spd(slot_idx, 195));
-               ;


```

**Comment by 01e3** [comment]
(BTW: it seems I have no permission to re-open the bug)

**Comment by x86fr** [comment]
I reopen this because it's another perfect example of why selftests are biased in real-world scenarios (unless a LOT of efforts are put on them, or a LOT of input data on this particular case).

I understand why this `<< 3` looked like a typo. When running your selftests, you noticed that this Kingston SPD dump was now wrong. So you changed it back, based on selftest results, and the Kingston is now decoded as expected. That's probably also what I would have done.

But by doing so, you actually increased the decoding errors on 1000 DDR3 SPDs from 0.8% to 2.3% because this commit solves this:

```
<< 3 : Kingston 9905403-437.A01LF (2011-W42) - CAS 9-9-9-27 [WRONG]
<< 4 : Kingston 9905403-437.A01LF (2011-W42) - CAS 9-9-9-15 
```

but also add some new errors like this:

```
<< 3 : 4GB DDR3-1600 XMP - Corsair CMZ8GX3M2A1600C9 (2012-W22) - CAS 9-9-9-24
<< 4 : 4GB DDR3-1600 XMP - Corsair CMX8GX3M2A1600C9 (2012-W22) - CAS 9-9-9-50 [WRONG]
```

I noticed this issue while debugging DDR3 and I added this quick << 3 patch to lower the failure rate unless it is definitely fixed. (< 1% errors on tRAS looked acceptable). 

I hope to have a final fix today or tomorrow 😀

**Comment by x86fr** [comment]
PS : Here is my TODO list for D3:

```
CPU-Z 2.01 : 8GB DDR3-2138 XMP - G.Skill F3-2133C9-8GXH - CAS 9-11-11-31
Memtest86+ : 8GB DDR3-2133 XMP - G.Skill F3-2133C9-8GXH - CAS 8-10-10-29 - MISMATCH FOR ID 4fdw6i (14)

CPU-Z 2.01 : 4GB DDR3-1863 XMP - Wilk Elektronik GY1866D364L9A/4G (2015-W09) - CAS 9-11-9-28
Memtest86+ : 4GB DDR3-1066 XMP - Wilk Elektronik GY1866D364L9A/4G (2015-W09) - CAS 9-11-9-28 - MISMATCH FOR ID nbu1wn (444)

CPU-Z 2.01 : 4GB DDR3-1600 XMP - Kingston KHX1600C9D3/4GX (2012-W12) - CAS 9-9-9-27
Memtest86+ : 4GB DDR3-1600 XMP - Kingston KHX1600C9D3/4GX (2012-W12) - CAS 9-9-9-15 - MISMATCH FOR ID sbvvf7 (449)

CPU-Z 2.01 : 4GB DDR3-1600 XMP - Kingston 9905403-437.A01LF (2011-W42) - CAS 9-9-9-27
Memtest86+ : 4GB DDR3-1600 XMP - Kingston 9905403-437.A01LF (2011-W42) - CAS 9-9-9-15 - MISMATCH FOR ID 6l6uyh (664)

CPU-Z 2.01 : 8GB DDR3-2400 XMP - G.Skill F3-2400C10-8GTX - CAS 10-12-12-31
Memtest86+ : 8GB DDR3-2400 XMP - G.Skill F3-2400C10-8GTX - CAS 9-11-11-29 - MISMATCH FOR ID zty9vf (876)

CPU-Z 2.01 : 4GB DDR3-1600 XMP - Kingston KHX2400C11D3/4GX (2015-W31) - CAS 11-11-11-28
Memtest86+ : 4GB DDR3-1600 XMP - Kingston KHX2400C11D3/4GX (2015-W31) - CAS 11-13-14-32 - MISMATCH FOR ID 3var8y (977)
```

**Comment by 01e3** [comment]
Ah, sure. Selftests will not tell you how to fix, rather that there is a problem. Clearly someone that has all the context need to implement the fix and/or review it. Also, it is hard for them to have 100% coverage of all use-cases. 

Now... I suspect the fix would conflict with my changes... Which order would you like to commit them? If you want the fix first, I can then re-do the patch(es), again - not  a problem, but in case they are ready later today, maybe they can go first?

**Comment by x86fr** [comment]
Yes. You go first and I'll fix after on your code

**Comment by x86fr** [comment]
Seems ok now : `4GB DDR3-1600 XMP - Kingston 9905403-440.A00LF (2011-W39) - CAS 9-9-9-27`

**Comment by 01e3** [comment]
Looks good with my [very] limited testset.
