### ISSUE TITLE
"address test, own address" behavior difference between 32-bit and 64-bit versions

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#155]
Forked from https://github.com/memtest86plus/memtest86plus/issues/153

In the "address test, own address" the "top" half has all zeros (00000000-b3f99d00), which is partially due to the 64-bit binary using 64-bit variables.

Would we have a better coverage if we put there something else then just zeros? Most systems have xx GiBs of RAM, but even for ones with z TiB we will still have soo many zeros. 

As the behavior is different compared to the 32 bit binary, where we use 32-bit variables, perhaps the best way would be to only use the "bottom" part of the address in 32-bit variables - in a consistent manner between the 32bit and 64 bit versions?

Also the value  does not match the address (00000006 73f99d00) - we have 0xb instead of 0x7 in the highest bits of the "bottom" 32 bit number, and for the "top" part of the value it is 0x0 instead of 0x6? 

_Originally posted by @01e3 in https://github.com/memtest86plus/memtest86plus/issues/153#issuecomment-1234965355_

**Comment by x86fr** [comment]
Main question : is this still present in b3 ? 

I can theoretically imagine a race condition between e-core and p-core but this should not happen anymore as e-core are now skipped. 

About filling the top bits of address with something (usually 0xAA or 0x55) to create a "mixed" test, I don't think it will be really useful. Address tests are really basic and quick tests. Using the address as the "test pattern" make it easier to debug. if any issue, it will be detected by moving inversion quickly after.

**Comment by martinwhitaker** [comment]
There are two "own address" tests, tests 1 and 2. Test 1 comes from Memtest86+ v5 and works one (1GB) test window at a time. I added test 2 to quickly identify faults in the address lines above 1GB. Two different tests are needed for 32-bits, because you can't uniquely tag more than 4G 32-bit words. But for 64-bits we could speed up testing by amalgamating these two tests. I didn't do that because:

1. I wanted to minimise the differences between the 32-bit and 64-bit code, to ease maintenance
2. I only deal with low core-count machines, and these tests are fast in that case

But because these tests are run sequentially on all cores, they take far more time on high core-count machines. So it might be worth implementing an amalgamated 64-bit version. Something to consider for v6.1.

**Comment by 01e3** [comment]
Right, I agree that 0xAA or 0x55 may not be the best way of handling this. I have been thinking about doing something like:

```
diff --git a/tests/own_addr.c b/tests/own_addr.c
index b5a9223..e297a12 100644
--- a/tests/own_addr.c
+++ b/tests/own_addr.c
@@ -58,7 +58,13 @@ static int pattern_fill(int my_cpu, testword_t offset)
             }
             test_addr[my_cpu] = (uintptr_t)p;
             do {
+#if TESTWORD_WIDTH == 32
                 write_word(p, (testword_t)p + offset);
+#elif TESTWORD_WIDTH == 64
+                write_word(p, (((testword_t)p + offset + 4) << 32) + (testword_t)p + offset);
+#else
+#error Unsupported TESTWORD_WIDTH
+#endif
             } while (p++ < pe); // test before increment in case pointer overflows
             do_tick(my_cpu);
             BAILOUT;
```
Compile tested only. Also, I have not checked if some tweaks are needed for gcc to generate optimized code. We also would need a similar change in pattern_check.

The idea is that we would write exactly the same values in both binaries (32 and 64), providing consistent test coverage when comes to the patterns used.

**Comment by 01e3** [comment]
Also, the address vs value difference is expected, as explained in the code (system/vmem.c): _We use the third GB to map the physical memory window we are currently testing_, where "third GB" means 2GB - 3GB.

So, the only values expected to be present w/o accessing page_of() / mapped_window (which I expect may be too expensive?) are 0x80000000 - 0xBFFFFFFF, which also explains the "mismatch" I noticed.

**Comment by debrouxl** [comment]
> But because these tests are run sequentially on all cores, they take far more time on high core-count machines.

Yeah, they're expensive on machines with higher core counts and/or RAM size...
In #79, we discussed making the own address tests faster. Sam's suggestion from https://github.com/memtest86plus/memtest86plus/discussions/79#discussioncomment-2799002 is simple, if a bit extreme of a simplification / speedup, based on the fact that failures in the three first tests signal severe memory access errors, or weird stuff going on :)

As for tradeoffs:
* is "one core per socket" really achievable on all x86 / x86_64 processor models through the already implemented ACPI MP / MADT parsing and detection of number of cores per CPU ?
* optional nontemporal stores for the own address tests, are published on the experimental _nontemporal_ branch, with a potential change in detection reliability if a processor's OOO execution engine either elides stores when we don't want it to, or possible changes in write workloads (more bursty ?) somehow stress flaky memory bus or memory harder;
* short of accurately implementing "one core per memory controller", which would be _complex_ and require ongoing maintenance to support future processor topologies, the NUMA node information contained in the ACPI SRAT could be a crude, if known wrong, approximation for such information. That is, on sufficiently modern computers with NUMA both enabled and properly configured (e.g. NUMA emulation for LLC with some recent Zen processors)... but too bad for users if their computers are configured in a way that yields lower performance for most workloads, IMO.

A data point: my 4S Opteron servers have 4 or 8 cores per NUMA node, depending on whether BIOS-level no SMT mode - when supported - is enabled. On the RS904A in no SMT mode, with nontemporal stores, switching from cores 0-31 to cores 0,4,8,12,16,20,24,28 yields a ~2h40 speedup for a memtest86+ pass => 3+h speedup with normal stores.
The PSU of that particular RS904A is currently broken, so I'd have to switch to the R815, but for short benchmarks as the ones I posted at https://github.com/memtest86plus/memtest86plus/discussions/12#discussioncomment-3512388 , its longer boot cycles are annoying...

**Comment by x86fr** [comment]
To follow on, what about adding this https://github.com/memtest86plus/memtest86plus/discussions/79#discussioncomment-2799002 as a first step to reduce test time on massively multi-threaded systems?

**Comment by martinwhitaker** [comment]
"own address in window" won't catch high-order stuck at zero address bits (and "walking ones" may miss them if they are local to a memory bus). So probably better to just disable test 1 by default.

**Comment by debrouxl** [comment]
IME, "Address test, walking ones, no cache" (test 0) is pretty cheap compared to the "Address test, own address in window" (test 1) and "Address test, own address + window" (test 2), so it's not a big deal for test time if test 0 remains SEQ instead of ONE, which seems to be desirable for test reliability, IIUC Martin's message.

Disabling "own address in window" and/or "own address + window" (tests 1 and 2) by default on 64-bit platforms would shorten the default pass run time by hours on my 4S Opterons, so that's fine with me :)

**Comment by x86fr** [comment]
Test 1 now disabled since #[6cf13fe](https://github.com/memtest86plus/memtest86plus/commit/6cf13fe0c479dcc68af715c696386966b28ecdf1)
