### ISSUE TITLE
No SPD detection on Lenovo T580 with 8th gen i5

### ISSUE THREAD

**Issue by BenMyers43** [memtest86plus/memtest86plus#157]
So far, I have seen no system lockups or other failures with version 6.00b2 or 6.00b3.  But I ran Memtest86+ to test memory on a Lenovo Thinkpad T580 with 8th gen Intel i5 CPU, and, for the first time, the program did not display any info about the make, part number, etc of the memory, which is a pair of 8GB Kingston 1xR8 PC4-2666V memory. Their part numbers are different, HP26D4S9S8ME-8 and KN8GB0705194801980ML00 .  Lenovo calls the memory controller "SOC", system on a chip.  If you want, I can send info from the Windows device manager to identify the memory controller.

**Comment by x86fr** [comment]
Please post a CPU-Z validation link if possible.

**Comment by BenMyers43** [comment]
CPU-Z validation, as requested

https://valid.x86.fr/epw3q5

**Comment by x86fr** [comment]
Lenovo locks access to the smbus controller on some laptop and a quirk is needed. Unfortunately, this could be dangerous so I must find one of them to debug. 

PS: I use a Lenovo T480s (same SoC generation) as my main laptop and it works as expected, so I don't really understand why they locks smbus on some SKU and not on some similar SKU.

**Comment by BenMyers43** [comment]
Different BIOS revisions?

**Comment by BenMyers43** [comment]
Here is the link.  Will post on GitHub, too.

https://valid.x86.fr/epw3q5

... Ben

**Comment by x86fr** [comment]
Note to self: add a function to check RCBA

**Comment by x86fr** [comment]
The last commit ([#1f1fe5b](https://github.com/memtest86plus/memtest86plus/commit/1f1fe5bfe871600dad3bd9a0de538d8e051353a9)) probably solved this issue. 

SMBus datas are now displayed properly on my Thinkpad t480s (similar laptop with same 8th gen Core)
