### ISSUE TITLE
Core count issue on Intel Core i3-3240

### ISSUE THREAD

**Issue by mioljub** [memtest86plus/memtest86plus#170]
Aforementioned CPU actually have two cores and four threads - I activate Hyper threading mode in BIOS. I am looking forward for new version of Memtest86plus (v. 6.0.0).

**Comment by x86fr** [comment]
Hi. Please post a screenshot.

**Comment by mioljub** [comment]
I just started compiling patched linux-5.15.65 with original Slackware64-current Live .config file with RT-Full and Ivy Bridge (information from Intel site - formerly known as Ivy Bridge). The rest of .config file remains as original Slackware64-current Live .config file.

Another compiled patched linux-5.15.65 will be with aforementioned .config file but will be RT-Full and Intel-Native (Processor type and features - Processor family).

Btw. in aforementioned .config file I have Preemtible Kernel (Low-Latency Desktop) (General Setup - Preemption Model) and Generic-x86-64 (Processor type and features - Processor family).

I will have three dmesg-report files:
1. original .config file
2. .config file with RT-Full and Ivy Bridge
3. .config file with RT-Full and Intel-Native

RT-full is Fully Preemtible Kernel (Real-Time) (General Setup - Preemption Model)



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by debrouxl** [comment]
Well, x86fr certainly wanted a picture of your computer's screen running memtest86+ :)

**Comment by mioljub** [comment]
Memtest86plus 5.01 started from SYSTEM-RESCUE-CD 5.3.2 (Option A. then Memtest86 ...)

First I tried with SMP (F2 function key) - first.jpg

Then Memtest86plus 5.01 stopped at 21% - second.jpg

I also tried without pressing any function key - third.jpg

---

About Slackware64-current Live USB Flash Drive with Live version died, so ...
________________________________

**Comment by debrouxl** [comment]
Could you try the latest build from https://memtest.org/ , currently 6.00 Beta 3 but possibly soon 6.00 RC1, instead of that old memtest86+ version ? :)

**Comment by mioljub** [comment]
Yes, I am looking forward for the screen of Memtest86plus 6.00 Beta 3.

Btw. I will try before starting this one to disable HyperThreading in BIOS. But it will be very strange - old one says that I have 4 (four) Cores!?

Then I will start Memtest86plus 6.00 Beta 3 (with and then without enabled HyperThreading).


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mioljub** [comment]
I unpacked .exe file with 7-zip (to folder), and copy 64-bit version to 'dead' USB Flash Drive of 64 GB with Slackware64-current Live version.

USB Flash Drive 'died' in previous booting.

Now it works well.

When Memtest86plus 6.00 Beta3 finish second pass I will send You some pictures. One from the end of first pass and second from the end of second pass.

Now I have correct identification of CPU --->

CPU: 2 Cores 4 Threads    SMP: 4T (PAR)

now it finished first pass with message with green letters PASS

Now it is on 17% of second pass with Time: 0:19:00

Great work! Thank You very much!


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mioljub** [comment]
From now I will use make -j 3 (number of Cores plus one - 2 Cores + 1= 3) when compiling Linux Kernel. Thank You very much, again!


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mioljub** [comment]
During first pass of Memtest86plus 6.00 Beta3
________________________________

**Comment by mioljub** [comment]
After second pass of Memtest86plus 6.00 Beta3
________________________________

**Comment by x86fr** [comment]
Presumed fixed.

**Comment by mioljub** [comment]
I will post a screenshot, because some BIOS issue I am now compiling linux-5.15.65 Linux Kernel patched with kernel_compiler_patch (https://GitHub.com/graysky2/kernel_compiler_patch) and Linux Kernel RT Patch (https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/5.15/patch-5.15.65-rt49.patch.xz), then I will have dmesg-report from original Slackware64-current Live and patched kernel linux-5.15.65.
The same message as aforementioned about four cores on Intel i3-3240 I have in original dmesg-report, I will post both dmesg-report files. Very strange thing.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
