### ISSUE TITLE
6.0 b1,b2,b3 not start, freeze during usb detection

### ISSUE THREAD

**Issue by psycodeoday** [memtest86plus/memtest86plus#171]
5.01, 5.31b works fine.
6.0 b1, b2,b3 freeze during usb detection with default bios settings.
.
reproduction:
**bios settings:**
.
![320220918_204803](https://user-images.githubusercontent.com/9746260/190924145-cefd1cf0-8a31-49d6-bb6f-a4e20030a0d6.jpg)
.
**POST screen:**
.
![10220918_202950](https://user-images.githubusercontent.com/9746260/190924088-35e94cbe-e177-4b06-8d9c-36f9b6662513.jpg)
.
**then freeze (0 usb found)**
.
![420220918_203203](https://user-images.githubusercontent.com/9746260/190924233-e51e4d7e-3e31-4d1a-9937-88b0013874c8.jpg)
.
the same freeze is with NO keyboard and mice connected (only usb mass storage)
= = = = = = = = = 
.
**my soluction in bios:**
.
![520220918_204931](https://user-images.githubusercontent.com/9746260/190924155-626b82b5-2239-4425-9c23-f64ec877c071.jpg)
.
**then it starts fine:**
.
![620220918_204553](https://user-images.githubusercontent.com/9746260/190924202-1289a268-c3b5-40ef-bf36-f02e442a2bae.jpg)
.
.
.
also small detail:
bios show timings 5-5-5-18
![xxxx4520220918_211247](https://user-images.githubusercontent.com/9746260/190924592-a7153aa1-7fcd-470c-b32c-4888c92794a9.jpg)
.
memtest show 5-4-4-14
and if I set manually in bios to 5-5-5-15(which value taken from the sticker on memory module) then memtest also show 5-4-4-14
![620220918_204553](https://user-images.githubusercontent.com/9746260/190924620-cd3bf408-423f-44d1-af86-557b6bee1c7f.jpg)
.
.
.
specs:
Asus P5Q-E, socket 775, P45, latest bios 2101,
core2quad Q9450
3x corsair dominator 2gb 1066 cl 5-5-5-15, 2.1V 
CM2X2048-8500C5D

**Comment by x86fr** [comment]
Please try the latest nightly build available here: https://memtest.org/dev

**Comment by debrouxl** [comment]
Interesting. I've never noticed similar hangs on my P5QC with BIOS version 2103, I'll have to double-check :)

**Comment by psycodeoday** [comment]
> Please try the latest nightly build available here: https://memtest.org/dev

I found in my flat, second, exactly the same motherboard P5Q-E, and this time I've used Core2Duo E8400 and it is the same freeze with default bios settings. So we can exclude idea that maybe motherboard is faulty.

Now I will try use nightly build...

**Comment by psycodeoday** [comment]
> Please try the latest nightly build available here: https://memtest.org/dev

yes, nightly build fixed the issue.
no freeze (with usb 2.0 enabled and hi speed enabled) anymore.
.
also cas timings are displayed correctly now.

![memtestfix](https://user-images.githubusercontent.com/9746260/191096962-9055e70b-fe5b-46bd-9472-9faa3eccbe7d.jpg)
.
.
thank you for very quick reaciton and 100% fix
