### ISSUE TITLE
Don't display banner after keypress

### ISSUE THREAD

**Issue by psycodeoday** [memtest86plus/memtest86plus#173]
Current PASS message, covers RAM module speed, model, and manufacturer.

![pass](https://user-images.githubusercontent.com/9746260/191292354-f1baf76d-f0e5-4bec-beb5-fbe6f3c673c7.jpg)

Please consider making it smaller to not cover important information.
I made an example:
![pass-fix](https://user-images.githubusercontent.com/9746260/191292532-e626433e-1843-48a8-bbc5-686a9ab477ca.jpg)
.
.
The reason is that a lot of people is using Memtest PASS screenshot to prove that RAM stick is good, during sell auction on internet. It always helps to convince buyer that RAM was tested.

Current large Pass message is giving a reason to buyer, to suspect that seller provides fake passed test using different RAM sticks (because true speed, model, manufacturer can be hidden behind that large message)

**Comment by 01e3** [comment]
Would it make sense to add " [Press any key to remove the banner] "?

Just a question if this is really "any" key? Some of them (Esc, space, etc) have different meeting. So, maybe:  " [Press Enter key to remove the banner] "?

**Comment by x86fr** [comment]
Any key will remove the banner, including Esc, Space or F1.

**Comment by 01e3** [comment]
Yes, but I think esc will also terminate the test (which I think is intended)? As we may also use other keys in the future, I think it may make sense to "reserve" a dedicated for this, like Enter?

```
void check_input(void)
{
    char input_key = get_key();

    if (input_key == '\0') {
        return;
    } else if (big_status_displayed) {
        restore_big_status();
    }

    switch (input_key) {
      case ESC:
        clear_message_area();
        display_notice("Rebooting...");
        reboot();
        break;
      case '1':
        config_menu(false);
        break;
      case ' ':
        set_scroll_lock(!scroll_lock);
        break;
      case '\n':
        scroll_wait = false;
        break;
      default:
        break;
    }
}
```

**Comment by x86fr** [comment]
Really no needs for this now. Enter is within "any" and pressing any key to remove the banner is obvious.

**Comment by 01e3** [comment]
To be honest, I was not ware that the banner can be removed until I looked at the code. Given the question in this bug, I suspect I may not be the only one, which is why I suggested adding the message. 

The reason why I proposed a dedicated key is to avoid a situation where some setting get accidentally changed. For example, even today one may press space (which changes scrolling) or escape (that terminates Memtest86) and these seem like common choices.

Happy to provide a patch, we can discuss it there, unless this is a "strong NO" to leave this as is?

**Comment by 01e3** [comment]
Ah, I'm blind, "Enter" is already used:

```
      case '\n':
        scroll_wait = false;
        break;
```

**Comment by OneOfMany07** [comment]
I can see having the PASS result visible when the screen image is small would be nice.  And yes the picture after removing PASS would still include the word pass somewhere, but it would take more work to see it (opening the image to zoom in by the buyer).

I'm against requiring one specific key.  I don't see a reason to limit it.

I don't follow the issue if the user happens to pick a key that normally does something else.  I mean it shouldn't stop the run until the message is gone, but... it's not hard to hit it a second time.

A note telling the user how to remove the banner might be handy for nervous people, but it's also obvious once you try to do anything.

As another way to show the run finished at a distance, you could also change the background color or change part of it (make a ring on the outside reflect overall status).  Though then you get into dealing with colorblindness settings to tweak them (red/green is common, but others happen too).

You could even get fancy and as the runs progress the screen changes color.  Pass 2 gets another change, etc.

But I see this all as behind anything truly functional still needed.  Even code cleanup tasks.

**Comment by 01e3** [comment]
The problem with "any" key is that if may have a function defined - either currently or in the future.

Today, when a key is pressed, Memtest86+ removes the banner but *also* at the same time executes the action assigned to that key, such as terminates for Esc, changes scrolling for space / Enter, etc. Having two actions triggered by a single event is one of the basic UX anti-patterns.

We can change the code to only remove the banner and stop there, but it means changing the actions depending on the context - for example, in one situation Esc will terminate the test, in other - just remove the banner. This is another UX anti-pattern.

Especially that a user may not have an intention to remove the banner.

IMO, the easiest solution that also guarantees no UX changes in the future would be to assigned a dedicated key, such as "x" or "tab" to remove the banner, and this is why I suggested that path.

**Comment by hfath** [comment]
Things are actually worse for the FAIL banner, in that it obscures the list of failures and which memory module they are in - and a keypress does not make it go away.

![memtest86+-v6-fail-cropped](https://user-images.githubusercontent.com/13416150/198024270-ca535ec1-0df6-496b-9425-f58433cf9646.jpg)

**Comment by x86fr** [comment]
I will definitely remove the banner definitely after any keypress.

**Comment by Spainman** [comment]
> I will definitely remove the banner definitely after any keypress.

Is a fix for this to be expected any time soon? 
Not impatient but it's a deal breaker for my use case and I'm considering buying passmark's memtest86 because I need to see the error details, so info regarding the time frame would be helpful. Thanks.

**Comment by x86fr** [comment]
Within 2 weeks. #34 is the priority right now but this will be added soon.

**Comment by thamesynne** [comment]
In the latest version (6.01.036922a.x64 GRUB ISO) the FAIL banner still doesn't go away after any key is pressed. Or rather, it does, but some bit of code is going "Oh no, we've detected a failure but the banner isn't showing!" and putting it straight back again.

**Comment by x86fr** [comment]
Got it. Will check & correct this week.

**Comment by kammerjaeger** [comment]
I still have the bug in version 6.10.ce2c29e.x64 . When is it planned that this is fixed? It overlaps the information about the error. Or which earlier version does not have the banner so I can use that to see the problem of my ram?

**Comment by martinwhitaker** [comment]
You can use the `nobigstatus` boot command line option to disable the big status banner.

**Comment by ccrvlh** [comment]
Adding to the current issue, if you disconnect the keyboard and then connect it again, it seems the keyboard doesn't work anymore, so it's impossible to exit the pass banner, and it's not possible to take a picture with the memory module and name.

The reason I connect/disconnect the keyboard is that I have a test PC, and usually run Memtest in this test PC instead of the main workstation. The monitor receives both inputs and I switch the keyboard as needed.
