### ISSUE TITLE
HP DL360 Gen9, no keyboard via ILO

### ISSUE THREAD

**Issue by dchard** [memtest86plus/memtest86plus#179]
Dear Developers,

Running Memtest86+ version 6 beta03 with latest ILO4 (version 2.81) yields no keyboard support, none of the keys work. Memtest86+ is running fine. Both HTML5 and the Java based ILO consoles were tested.

MOD2: if the remote console is open from boot, then the virtual keyboard does work, but if I close the remote console and then reopen it, the keyboard does not work anymore. So this seems to confirm that the issue is that ILO attaches and detaches the virtual keyboard (and mouse) every time the remote console is opened or closed.

![image](https://user-images.githubusercontent.com/8152156/194530248-50b420de-83e4-4b54-9225-782bf5370897.png)

BIOS is P89 v2.90 (04/29/2021), the server was UEFI booted with the Linux x64 Memtest ISO (via virtual media).

I have a feeling that this is a general ILO issue, as it usually attaches a virtual USB device (keyboard + mouse) on the fly, when the remote console is opened.

MOD:

This is how it looks in dmesg, when an ILO console is opened:

```
[Fri Oct  7 12:51:22 2022] usb 3-1: new full-speed USB device number 2 using uhci_hcd
[Fri Oct  7 12:51:22 2022] usb 3-1: New USB device found, idVendor=03f0, idProduct=7029, bcdDevice= 0.02
[Fri Oct  7 12:51:22 2022] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[Fri Oct  7 12:51:22 2022] usb 3-1: Product: Virtual Keyboard
[Fri Oct  7 12:51:22 2022] usb 3-1: Manufacturer: BMC
[Fri Oct  7 12:51:22 2022] input: BMC Virtual Keyboard  as /devices/pci0000:00/0000:00:1c.2/0000:01:00.4/usb3/3-1/3-1:1.0/0003:03F0:7029.0001/input/input2
[Fri Oct  7 12:51:22 2022] hid-generic 0003:03F0:7029.0001: input,hidraw0: USB HID v1.01 Keyboard [BMC Virtual Keyboard ] on usb-0000:01:00.4-1/input0
[Fri Oct  7 12:51:22 2022] input: BMC Virtual Keyboard  as /devices/pci0000:00/0000:00:1c.2/0000:01:00.4/usb3/3-1/3-1:1.1/0003:03F0:7029.0002/input/input3
[Fri Oct  7 12:51:22 2022] hid-generic 0003:03F0:7029.0002: input,hidraw1: USB HID v1.01 Mouse [BMC Virtual Keyboard ] on usb-0000:01:00.4-1/input1

```

The two USB devices created by ILO:

```
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=uhci_hcd/2p, 12M
    |__ Port 1: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 1: Dev 2, If 1, Class=Human Interface Device, Driver=usbhid, 12M

```

```
Bus 003 Device 003: ID 03f0:7029 HP, Inc
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x03f0 HP, Inc
  idProduct          0x7029
  bcdDevice            0.02
  iManufacturer           1 BMC
  iProduct                2 Virtual Keyboard
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           59
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x40
      (Missing must-be-set bit!)
      Self Powered
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface             16 Virtual Keyboard
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      65
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface             32 Virtual Mouse
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      60
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0005  1x 5 bytes
        bInterval              10
Device Status:     0x0001
  Self Powered

```

**Comment by martinwhitaker** [comment]
USB hotplug is not supported. I guess I should mention this in the README.

**Comment by dchard** [comment]
@martinwhitaker thanks for the answer.

Quite obviously this is no place for feature request, but you might want to consider to add this (have no idea how complicated it would be), as at least all HP Gen8/Gen9 (ILO4) servers are all affected by this, likely other BMC vendors do the same thing. If you combine this the fact for how long a proper amount of Memtest needs to run on a server with 128GB of RAM, you really dont want to keep the remote console open for that long time :-)

**Comment by 01e3** [comment]
Would using serial emulation in iLO or keyboard=legacy be an acceptable workaround?

**Comment by dchard** [comment]
I think serial emulation is not an option, "keyboard=legacy" is a memtest option? 

If I recall it correctly I have seen an option somewhere on another vendors BMC that the virtual keyboard stays attached all the time, but I think that was SuperMicro and not HP.

**Comment by martinwhitaker** [comment]
Supporting hotplug would be quite a lot of extra work, but would also significantly increase the amount of memory reserved for use by the USB controllers and drivers, and hence not tested,

**Comment by dchard** [comment]
@martinwhitaker well, the commercial version does support this, and I have a feeling that the main reason on their side was exactly the same as here: servers. I understand the required effort, don't get me wrong, but despite the fact it takes more reserved memory, this may still be considered in the (hopefully near) future. I wonder how much extra memory would this feature take?

**Comment by martinwhitaker** [comment]
I have added a note in the README and also started an enhancement discussion (#182).

The commercial version supports it because it is an UEFI application, and so can use the UEFI BIOS services. The downside of that is that (as far as I know) it can't then test the memory reserved by the UEFI BIOS, which can be several hundred megabytes. That's why I went to the considerable effort and pain of implementing a set of minimal USB drivers from scratch.

Perhaps you could ask HP to add an option to leave the virtual keyboard permanently attached.

**Comment by debrouxl** [comment]
As for SPD information not being read by memtest86+ on your computer: `decode-dimms` 4.2 running on a recent Linux kernel doesn't do it on a DL380 Gen9 I have access to. The DL360 Gen9 and the DL380 Gen9 are very close, they use the same BIOS.
I'd think that is a variant of #65 : among others, many newer Xeon-based platforms, even uniprocessor ones, require special handling to select, set up and access the right i2c bus .
