### ISSUE TITLE
Unable to select usb in windows installer

### ISSUE THREAD

**Issue by lhwn5407** [memtest86plus/memtest86plus#181]
Version : Memtest86+ 6.00 beta 3
Platform : windows 10 pro 21H2 19044.2006

The windows installer of memtest86+ does not recognize a 32GB USB formatted in fat32.
I tried:
- Plug in the USB and re-run the windows installer
- Computer reboot
- Plug it into both the front USB port and the rear USB port

Since the same USB is recognized by rufus, I do not think it is a problem with my computer or a problem with the USB.
I hope the screenshots are helpful.

![image](https://user-images.githubusercontent.com/69153553/194704907-81de2889-3b54-450b-8a3f-ff56ccfca7e6.png)

**Comment by epman100** [comment]
confirmed.  I am also getting the same issue as the OP as the windows installer of memtest86+ won't recognize my Philips 64Gb USB Flash drive formatted as either NTFS or exFAT.

only workaround is to use "smaller" usb drives less than 32Gb (ex. 16Gb) as the memtest86+ installer won't find any usb drives 32gb or bigger (like my 64Gb flash drive)

**Comment by OneOfMany07** [comment]
They have a separate project for the installer.  https://github.com/memtest86plus/windows-installer

I also suggested they consider reusing an existing ISO to USB project.  Though I have no idea if their needs are unusual.

**Comment by lhwn5407** [comment]
After many tries, I found out about RMB (Removable Media Bit).  RMB is used by Windows to determine whether the storage device is removable or fixed.  The two SanDisk usbs I had were for some reason all marked as fixed storage (RMB = 0), so Memtest86plus windows installer didn't show my usb in the usb list.  My other 32GB usb had RMB=1 and it worked fine.
