### ISSUE TITLE
add logging to usb drive

### ISSUE THREAD

**Issue by wearepariah** [memtest86plus/memtest86plus#184]
it's a 'nice to have', but it would be great to have results for the test logged to the USB drive that memtest86+ is being run from
apologies if this is already implemented/ (i couldn't find it in the docs/other issues)

default off, turned on by command line or a setting?
named.. memtest86+{timestamp}.log ?

**Comment by debrouxl** [comment]
Indeed, it's not implemented and has no tracking _issue_. I'll rename the current tracking discussion of sorts, #164 , to a slightly more descriptive name. Thanks for the report :)

**Comment by martinwhitaker** [comment]
As @debrouxl said, this is already covered in the enhancement discussion #164, so closing this issue.

**Comment by wearepariah** [comment]
thanks @martinwhitaker @debrouxl, appreciate it.
