### ISSUE TITLE
memory speed detected incorrectly

### ISSUE THREAD

**Issue by wearepariah** [memtest86plus/memtest86plus#185]
DDR4 memory speed is detected at DDR4-4000, 15-15-15-35
'actual' memory speed is set at DDR4-3600, 14-14-14-28
JEDEC memory speed for this set is DDR4-2133, 15-15-15-35
XMP memory speed for this set is DDR4-4000, 16-16-16-36 (Corsair CMK16GX4M2G4000C16)
![20221015_113218](https://user-images.githubusercontent.com/66043052/195961086-27916eca-c060-469d-bc2a-8e29b6b4744a.jpg)

Seems like the speed it's showing is a mix of the XMP and JEDEC specs of the modules, rather than the 'actual' speed things are running at.
Ryzen 5600X on a MSI X570S Tomahawk with BIOS 7D54v14 with 32GB/4 sticks of CMK16GX4M2G4000C16

**Comment by 01e3** [comment]
Unfortunately, this is "WAI" (Working As *Implemented*), see: https://github.com/memtest86plus/memtest86plus/discussions/165

**Comment by wearepariah** [comment]
Thanks for that

> it is planned for Memtest86+ 6.10, starting with the newer platforms like AM5 and LGA1700

Consider this one closed :)
