### ISSUE TITLE
[feature request] Add ISO checksum

### ISSUE THREAD

**Issue by InfoLibre** [memtest86plus/memtest86plus#192]
On first web page, near download links, could you add the ISO checksum? I did not find them.

**Comment by x86fr** [comment]
MD5 checksum are just below the link:

![image](https://user-images.githubusercontent.com/38105886/197845308-348765db-38d8-4c97-9353-b6badeabd28e.png)

**Comment by InfoLibre** [comment]
Oooh, I'm tired. Sorry for wasted your time.

**Comment by debrouxl** [comment]
Maybe the SHA256 hashes could be added as well ? MD5 is a poor quality hash, by now.

**Comment by InfoLibre** [comment]
We don't know if checksum is for ISO or for Zip. You should propose to download directly .iso file, not .zip, even if its size is bigger.
