### ISSUE TITLE
Wrong memory detected on Gigabyte (813MB instead 64/32GB) from PXE Boot

### ISSUE THREAD

**Issue by Mtinejakydalsi** [memtest86plus/memtest86plus#196]
I have tried new and shiny memtest86+ v.6.00 happily on UEFI MB with network boot (pxe).... lazy to search for flashdisk. It reports 810MB of RAM. (loaded with syslinux.efi)
Not expecting problem with network boot (linux images boots fine). I have tried to flash MB to latest uefi... (from F6 to F8), even removed one module... only visible change - after uefi upgrade, it detects 813MB for my effort...so I ged 3MB. Ok, I must say, test passes and wery fast.... so, what am I comlaining with? :-)

After some spent time I have digged for usb flashdisk, booted it and it reports correct numbers... so, there is workaround for me. 

MB - Gigabyte B560M DH3  , originally with bios/uefi version F6 (reported 810MB with 64 or 32GB installed), updatet to latest F8 (and there is no way back, as stated in description; 813MB reported)...no bigger change.
CPU - Intel I3-10100F
RAM reported as: 2x 32GB DDR4-3200 XMP Kingston KF3200C16D4/32GX (2022-w02) , Text "Kingston Furry" on heatsink.
I can not "borrow" smaller memory modules at the moment.

I expect, my englis is not good enough, so ... picture for illustration:
![IMG_20221026_102140620x](https://user-images.githubusercontent.com/116720522/198221185-c94b9d01-726c-42ad-ac5b-19be5d12c817.jpg)

Is there something more to try?

On older UEFI machine with I5-7500, Gigabyte B250M-DH3-CF, 16GB Ram (2x8GB Crucial) , is everything detected ok, test passes. Including network boot from same dhcp/ftfp server. 
Older machines running in BIOS mode have no problems....to its age. :-/

**Comment by x86fr** [comment]
Can you try to load the .efi directly via PXE without any chaining (so without syslinux)?

**Comment by Mtinejakydalsi** [comment]
Yes, good point. I will try it on monday.

**Comment by Mtinejakydalsi** [comment]
OK. After some try/fail it booted nicely and memory is reported correctly (64GB)....and test takes much more time. 

(in short... downloaded non-grub(!) iso, extracted  bootx64.efi, placed somewhere into tftproot and referred from dhcp instead of syslinux ).

So. A bit more comfortable than flashdisk, because I do know, where dhcp config is all the time. :-D Other users do not. There is pxe boot menu for them. Is there better/more reliable way for pxe to try?
At now, only one MB reports memory incorrectly (is already tested and it will not be opareted by "public" here), so I am returning syslinux back, before somebody reports problem on network  .... because it is my problem on network :) ... and will try to look for another (better?) way to pxe boot.

Or is there something more, what can I try here?

**Comment by Mtinejakydalsi** [comment]
I have experimented with grub a little. Memtest v6 reports correct amount of memory, when chainloaded from grub instead of syslinux. It is sufficient for me now. Thank you. I am going to migrate all my syslinux`s menu.cfg to grub.cfg :-)

**Comment by x86fr** [comment]
Syslinux is used by the Windows USB Drive Installer without issues so far, so it seems the root cause of the issue is the chainloading of syslinux and Memtest86+ with PXE. Maybe you should try PXELinux instead of syslinux?
