### ISSUE TITLE
RAM name isn't displayed on HP Z420 computer

### ISSUE THREAD

**Issue by InfoLibre** [memtest86plus/memtest86plus#197]
When I test RAM on my HP Z420 computer, RAM name isn't displayed.

![IMG_20221101_153813](https://user-images.githubusercontent.com/3955499/199317194-658ebc94-f075-42b8-ac2e-d762066be438.jpg)

[lspci.txt](https://github.com/memtest86plus/memtest86plus/files/9913585/lspci.txt)

**Comment by debrouxl** [comment]
Thanks for the report.
This is SNB Xeon E, so it may be the same root cause as #65 , and possibly another known computer model to test a fix on. Sam ?

**Comment by InfoLibre** [comment]
![Capture d’écran du 2022-11-01 22-32-48](https://user-images.githubusercontent.com/3955499/199345903-483ab8b6-ed21-47ca-a624-e5ac1bb597c5.png)

**Comment by InfoLibre** [comment]
![Capture d’écran du 2022-11-01 23-12-41](https://user-images.githubusercontent.com/3955499/199351900-355f6a3d-7640-4d88-b029-e6b72cdf418a.png)

**Comment by debrouxl** [comment]
Right, Linux + i2c-tools can't do it either. Therefore, I think that what I suspected based on #65 is correct.
The respective i801 i2c SMBus controller models in the Z420 and Z440 are already supported by memtest86+, which is necessary, but not sufficient. Being necessary for recent hardware, this extra support for peculiarities of the Xeon E* families is likely to be implemented in memtest86+ much earlier than support for old SMBus controllers such as ali15*, viapro and sis96x SMBus controllers in your ( #126 ) and my computers. Outside surprise external contributions, that is.

**Comment by InfoLibre** [comment]
Do you need other informations about my computer?

**Comment by debrouxl** [comment]
For now, I don't think so. Thanks :)

**Comment by x86fr** [comment]
Duplicate #65 . This is in the pipeline for fix, but these platforms are less common nowadays.
