### ISSUE TITLE
SPD information gathering, decoding and printing

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#2]
Older memtest86+ versions support printing a subset of the SPD information available for DDR2 and DDR3 memory sticks. I think it's useful functionality to have in a memory testing tool, without booting up a full-featured general purpose OS. Some classic BIOS or UEFI implementations can do it too, especially recent ones.

The harder part of the work is reliably gathering said SPD data. There are multiple chipset and SMBus controllers in the wild, which have normal behaviour, quirks... and then some computers certainly have further quirks. For instance, bank switching, which may be more complex on multi-CPU socket computers, and may require fiddling with EC / power management stuff...

Once it is gathered, decoding and printing the SPD data isn't too hard, though it requires vertical scrolling, or other forms of paging. Besides, there's already some suitably licensed open source code implementing (part of) that functionality, e.g.:
* the decode-dimms tool ( https://www.kernel.org/pub/software/utils/i2c-tools/ ), which uses Linux kernel modules such as eeprom, at24 and several others;
* consumers of U-Boot headers such as https://github.com/u-boot/u-boot/blob/master/include/spd.h & https://github.com/u-boot/u-boot/blob/master/include/ddr_spd.h ;
* (there's also https://github.com/X0rg/CPU-X, but that's both abandoned since early 2021, despite some recent commits, and under the GPLv3).

I recently updated the list of SMBus controllers in https://github.com/anphsw/memtest86/blob/master/spd.c . Apart from the modern AMD SMBus controller with PCI IDs 1022:790b & 1d94:790b, most SMBus controller models not currently handled by memtest86+ and its open source forks are older or even old hardware, e.g. the ones by SiS and Nvidia, at the time Intel and AMD still made it possible for third parties to produce x86 chipsets... i.e. around 20 years ago by now.
Even with the backing of Linux kernel code, implementing support for these old controller models nowadays wouldn't help a great many real-world users, plus testing the code would require the appropriate MBs (I should have one with 1039:0016, but still) - so it's likely that most of the old models should effectively remain unimplemented in memtest86+, unless they matter to someone who contributes their support, of course :)

**Comment by x86fr** [comment]
PS : Plugfest postponed for a week. Too much work at factories this week. :-/

**Comment by x86fr** [comment]
We now support ~99% of currently used SMBUS controllers (#86).
