### ISSUE TITLE
Feature request : adding Hardware Detection Tool on your website

### ISSUE THREAD

**Issue by InfoLibre** [memtest86plus/memtest86plus#200]
Hello,

Are Hardware Detection Tool technologies very different from Memtest86+ technologies? It would be great to have the 2 projects on your website, is you find people to continue this project.

https://web.archive.org/web/20170104071223/http://www.hdt-project.org/

https://git.zytor.com/syslinux/syslinux.git/tag/?h=hdt/0.5.2

**Comment by debrouxl** [comment]
HDT is indeed nice, and I've looked at it in the past. However, it's been stagnating for quite a while... and in the meantime, Linux-based hardware detection tools (e.g. lshw, hwinfo) have kept up with the times.
Going forward, a small Linux image containing those, dmidecode, acpica-tools, and several others, or a large image such as the Ubuntu-based https://wiki.ubuntu.com/FirmwareTestSuite/FirmwareTestSuiteLive occasionally mentioned by Sam in other tickets, are probably better fits for hardware detection, especially on modern hardware.

**Comment by InfoLibre** [comment]
Thank you for FirmwareTest Suite Live. I didn't know it. I will ask them if they agree to add hardware detection.

**Comment by debrouxl** [comment]
I didn't know about it either until Sam wrote about it.
The `fwts --dump` mode (see https://wiki.ubuntu.com/FirmwareTestSuite/Reference ) already does part of the hardware detection report job.
