### ISSUE TITLE
doesn't boot

### ISSUE THREAD

**Issue by BegaDrive** [memtest86plus/memtest86plus#201]
Motherboard: MSI X470 Gaming Pro Carbon (bios: 7B78v2I).
Secure boot: disabled.

- tried 2 different usb flash sticks, passmarks memtest boots fine.
- it doesnt even show it as a boot option.

**Comment by debrouxl** [comment]
Are you using the GRUB ISO ?
If not, is there any difference when you use that ISO ?

**Comment by BegaDrive** [comment]
usb stick is GPT/Fat32, bios is on UEFI only. I used the [Windows USB Installer (32/64 bits) with the format option ticked.

**Comment by x86fr** [comment]
Can you show the content of the key?

**Comment by BegaDrive** [comment]
![εικόνα](https://user-images.githubusercontent.com/97917453/200651582-9e28e40a-b526-4655-9f34-b1138b0fffa7.png)

**Comment by x86fr** [comment]
There is no magic with uefi boot. The firmware only looks for any drive it's able to read and a file called BOOTX64.EFI in a directory named EFI. 

It seems your motherboard is not able to read the USB Drive for some reasons.

**Comment by BegaDrive** [comment]
yes

**Comment by x86fr** [comment]
Can you please show the property of the USB drive and its exact model?

**Comment by BegaDrive** [comment]
one is 'Samsung Bar Plus 64GB USB 3.1' and the other 'Sandisk Ultra 32GB USB 3.0'.

**Comment by debrouxl** [comment]
Have you been able to try using the GRUB ISO yet ? :)

**Comment by BegaDrive** [comment]
it runs with grub, keyboard didnt work when the test started, also no SPD detected

**Comment by debrouxl** [comment]
Interesting. For now we'll try to gather more information :)

* memtest86+ running when launched by GRUB but not when launched directly by the UEFI BIOS is the same symptom as #199 , in which case the fix could be the one described in #202 ;
* no SPD on a recent Ryzen motherboard was also reported as #203 later. Could you create and post a validation link with CPU-Z ( https://www.cpuid.com/softwares/cpu-z.html ) ? Other Windows options for (hopefully) displaying SPD data and gathering the PCI ID of the SMBus controller (should be 1022:780b or 1022:790b) include https://www.hwinfo.com/ and http://rh-software.com/ .
* from the GRUB menu, could you edit memtest86+'s command line to pass the `usbdebug` information and post a picture of your screen ? Also, does the keyboard work if you enable legacy USB emulation in your BIOS, if supported (many BIOS implementations provide the option) ?

Thanks in advance :)

**Comment by BegaDrive** [comment]
[cpuz validation, hwinfo report.zip](https://github.com/memtest86plus/memtest86plus/files/9979007/cpuz.validation.hwinfo.report.zip)

-legacy USB emulation is on by default

-and from the GRUB menu, i can access the command line, the real question is what command to type, i have zero knowledge on it.

**Comment by x86fr** [comment]
After debugging the issue, this is a MSI BIOS issue. Secure boot seems always enabled on BIOS 7B78v2I, no matter what the option actually is set to. Downgrading to 7B78v2D solve the issue.
