### ISSUE TITLE
memtest86+ EFI PE image does not load on some firmware

### ISSUE THREAD

**Issue by medhefgo** [memtest86plus/memtest86plus#202]
On some firmware, the memtest efi binary trips up the firmware when loaded using the provided boot service `LoadImage` (for example by systemd-boot).

This is likely due to the PE optional header being too small (sbverify doesn't like this binary because of this). The efi binary can be fixed and made to boot with `objecopy memtest.efi memtest-fixed.efi`.

Grub does not exhibit this behavior as it presumably does not use `LoadImage` to boot.

Discussed in https://github.com/memtest86plus/memtest86plus/discussions/199
Arch bug: https://bugs.archlinux.org/task/76390

**Comment by x86fr** [comment]
This might be solved by #34

**Comment by mattia-b89** [comment]
> This might be solved by #34
> 
> Update: It seems fixed with #34, but another confirmation would be nice :)

As soon as it hits upstream release

**Comment by mattia-b89** [comment]
Just an update: v6.01 does not fix the issue.

**Comment by debrouxl** [comment]
Indeed, the commits from #34 were only integrated after v6.01 . You may test the nightly build, available from https://memtest.org/dev/  :)

**Comment by medhefgo** [comment]
Yikes, from that nightly build:
```sh
$ sbverify --list bootx64.efi 
warning: gap in section table:
    datadir[CERT]->headers: 0x0000012a - 0x00000200,
    .text   : 0x00000600 - 0x00022400,
warning: gap in section table:
    .reloc  : 0x00022400 - 0x0002240a,
    .sbat   : 0x00022600 - 0x00022800,
gaps in the section table may result in different checksums
warning: data remaining[139786 vs 141312]: gaps between PE/COFF sections?
No signature table present
```

That really should be fixed, as there is firmware that will choke on that. (Calling `strip` would do.)

**Comment by x86fr** [comment]
Do you have any real-world exemple? We started a lengthy betatesting process on numerous Secureboot platforms without related issues so far. Maybe we're missing something.

**Comment by medhefgo** [comment]
https://github.com/systemd/systemd/issues/21956

**Comment by WinterStar2** [comment]
Signing and booting the .EFI file works with the latest version (6.10, on Arch).

**Comment by mattia-b89** [comment]
Latest 6.10 version fixes issue.  
If @medhefgo confirm, we can close here.

**Comment by medhefgo** [comment]
Looks good.
