### ISSUE TITLE
Memtest86+ 6,0 does not show memory DIMM info when started from GRUB 2.06

### ISSUE THREAD

**Issue by andrew64k** [memtest86plus/memtest86plus#203]
memtest86+ 6.0 boots from UEFI GRUB 2.06 and runs but does
not display DIMM SPD info as it does on other machines.

The display space for the memory info is just empty (blank)
rather than wrong.

System:
 ASRock Industrial 4x4 BOX-5600U
 BIOS version 1.30
 AMD Ryzen 5 5600U
 2x16G DDR4 GSkill DIMMs (PN below)

Linux dmidecode can see  the DIMMS and reports correct information including "Part Number: F4-3200C22-16GRS".

```
Handle 0x002D, DMI type 17, 92 bytes
Memory Device
        Array Handle: 0x0023
        Error Information Handle: 0x002C
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 16384 MB
        Form Factor: SODIMM
        Set: None
        Locator: DIMM 0
        Bank Locator: P0 CHANNEL B
        Type: DDR4
        Type Detail: Synchronous Unbuffered (Unregistered)
        Speed: 3200 MHz
        Manufacturer: Unknown
        Serial Number: 09132596
        Asset Tag: Not Specified
        Part Number: F4-3200C22-16GRS
        Rank: 1
        Configured Clock Speed: 3200 MHz
        Minimum Voltage: 1.2 V
        Maximum Voltage: 1.2 V
        Configured Voltage: 1.2 V
```

**Comment by andrew64k** [comment]
Update... Booting the memtest86+ ISO directly from UEFI BIOS *does* work (no GRUB)..... so I guess it's a GRUB interaction issue.

Any idea of options to include to make memtest86+ happy reading DIMM SPD?

**Comment by andrew64k** [comment]
I edited the title to directly state the actual issue. No mem info when starting from GRUB.

This is not just a problem with ASRock, it happens to everything I tried. Booting the ISO (no GRUB) shows the mem info. When starting memtest86+ 6.0 from GRUB 2.06 the mem info is no longer displayed. This happens when directly using your ISO with GRUB and when building for source and installing into /boot and using GRUB from the hard disk.

When booting Linux from GRUB on the same machine I am able to get mem info from the OS.

**Comment by martinwhitaker** [comment]
In the GRUB menu, edit the boot command line and replace `linux` with `insmod linuxefi; linuxefi`. Does that make a difference?

**Comment by andrew64k** [comment]
Yes, ```linuxefi``` does help on most machines with UEFI boot.
I just used your ISO to boot and changed the GRUB command to start memtest.

It worked correctly on ASRock Box 4x4 5600U and Intel NUC10 with UEFI boot (memory info shows up).
It did not seem to help on the HP EliteDesk 800 G3, but it did not hurt (memory info still does not show up).

**Comment by obiwan-bartek** [comment]
I had similar problem, but replaced the `linux` to `chainloader` _(and added `insmod chainloader` of course)_ and it helped.

Why use the old linux kernel booting way in GRUB (with `linux` command) instead `chainloader` anyway? Since the memtest in /BOOT/EFI is a standard standalone EFI binary, it could (and probably should) be just chainloaded...

**Comment by martinwhitaker** [comment]
> Why use the old linux kernel booting way in GRUB (with `linux` command) instead `chainloader` anyway? Since the memtest in /BOOT/EFI is a standard standalone EFI binary, it could (and probably should) be just chainloaded...

If you are asking about the GRUB ISO, it's because I originally created it solely for the purpose of testing the different ways of starting memtest. The standard ISO tests the standalone EFI loader method..

**Comment by obiwan-bartek** [comment]
@martinwhitaker Thanks for reply. 
Yes, I had the GRUB ISO in my mind with that question. Anyway, I think it should be changed to `chainloader` method anyway, which is more natural for booting EFI binaries. Do you agree? Or even add both options to GRUB menu, for fallback reasons, if chainloading for whatever reason fails.

**Comment by andrew64k** [comment]
```chainloader``` works for me and I don't have to build in any patches. Why am I using GRUB? Because I'm booting a normal Linux system and I want memtest to be an option at boot time (from GRUB). The problem with my HP is not solved so I'll open a new issue on that.

**Comment by martinwhitaker** [comment]
Nevertheless, this should still work when booted via GRUB.
