### ISSUE TITLE
Wrong amount of memory is detected (8Gb of 32Gb) on Dell XPS 9560

### ISSUE THREAD

**Issue by Sergey1Fox** [memtest86plus/memtest86plus#218]
Memtest cannot test all amount of memory. It can access only to 8Gb from installed 32Gb. Patriot Viper DDR4 2x16Gb 2400 C15
With previous memory Hynix DDR4 2x8Gb 2400 C17 everything is ok.
Boot from ISO file through GRUB 0.4.6a

Notebook Dell XPS 9560
i7 7700HQ 2.8GHz
Chipset Kaby lake, HM175
Installed latest BIOS 1.24.1

**Comment by x86fr** [comment]
Can you please: 
- Post a screenshot
- Describe your boot method precisely (USB Drive, optical drive, PXE, etc)
- Try another boot method (eg: without GRUB)

**Comment by martinwhitaker** [comment]
I note that GRUB 0.4.6a is not GRUB, but GRUB4DOS, which I know little about.
The memory map is passed to Memtest86+ by the bootloader, so it seems most likely GRUB4DOS is not passing it correctly. Please do try starting Memtest86+ directly from the BIOS.

**Comment by Sergey1Fox** [comment]
It looks like that you are right. I tried to boot from UEFI BIOS and MemTest works correctly (see attached screen shot, first from Grub4Dos, second from UEFI)
![IMG_20221205_025753_](https://user-images.githubusercontent.com/116572262/206869581-c708bbcb-5d6f-46d8-be1f-4e75bda8f75b.jpg)
![IMG_20221207_030537_](https://user-images.githubusercontent.com/116572262/206869586-a7bc5909-1b30-47e1-941a-ecec96aca732.jpg)

**Comment by 01e3** [comment]
Any chance you can boot a Linux kernel using both methods and see how much memory does it report?

If you have a serial port, you may just need a kernel image only and grab the "BIOS-provided physical RAM map" section and "Memory:" from dmesg via Serial.

**Comment by x86fr** [comment]
Issue related to GRUB4DOS
