### ISSUE TITLE
Press [F5] (Skip current test) ERROR occurs

### ISSUE THREAD

**Issue by Davis0725** [memtest86plus/memtest86plus#224]
Please forgive my poor English
After repeatedly pressing【F5】(more than 10 Press), the system will appear continuous errors that cannot be stopped.
(Can only be exited by pressing ESC.)

**Comment by martinwhitaker** [comment]
After testing, I believe this only affects test 2 (own address + window). PR #219 already fixed it for 64-bit builds. I have updated the PR to also fix it for 32-bit builds.

**Comment by Davis0725** [comment]
Hi
Confirmation that the problem has been fixed
thank you very much



________________________________
寄件者: martinwhitaker ***@***.***>
寄件日期: 2022年12月29日 下午 09:49
收件者: memtest86plus/memtest86plus ***@***.***>
副本: Davis0725 ***@***.***>; Author ***@***.***>
主旨: Re: [memtest86plus/memtest86plus] Press [F5] (Skip current test) ERROR occurs (Issue #224)


After testing, I believe this only affects test 2 (own address + window). PR #219<https://github.com/memtest86plus/memtest86plus/pull/219> already fixed it for 64-bit builds. I have updated the PR to also fix it for 32-bit builds.

**Comment by martinwhitaker** [comment]
Thanks for testing. Closing as fixed.
