### ISSUE TITLE
Test Fails and prints giant FAIL notice blocking critical information about the error

### ISSUE THREAD

**Issue by heston88** [memtest86plus/memtest86plus#226]
Pressing Esc reboots the system, pressing enter does nothing. There does not appear to be a way to remove the FAIL logo so that I can read the error information(such as the location).

Using V6.00 Linux 64bit

**Comment by x86fr** [comment]
Please use the latest nightly build or wait for v6.01 release (soon).

**Comment by heston88** [comment]
I found a solution actually. Activating scroll lock with space bar removes it.

**Comment by ar1a** [comment]
This still happens on 6.0.1! it seems to go away once there's a *second* error, but if there's only one it won't go away at all
