### ISSUE TITLE
memtest86+ v6.00: display crazy DIMM settings and fails with ASUS ROG Strix B650E-F, Ryzen 9 7950X

### ISSUE THREAD

**Issue by JuLuers** [memtest86plus/memtest86plus#228]
Memtest86+ v6.00 always fails in test #9 at address "0000ba1fed..." with 496 errors - regardless of whether 4 DIMMS are used or any of these DIMMs alone (placed in DIMM_A2). In the internet I saw similar screenshots showing same address with similar hardware. With that memtest displays crazy DIMM settings: "RAM: 19600MHz (DDR5-39200) CAS 386-1064-553-553". Mainboard default settings are used. The failure is displayed also if memory frequency explicitly is set to 3600 or 4800MHz.

64GB: Kingston Fury Beast RGB EX, DDR5-6000, CL36
CPU: Ryzen 9 7950X
Mainboard: ASUS ROG Strix B650E-F Gaming WiFi
BIOS Version 0613 x64, Build Date 09/22/2022, AGESA Version ComboAM5PI_1002, LED EC Version AULA3-AR32-0213, Version 2.22.1284 (c) 2022 AMI
![1dimm](https://user-images.githubusercontent.com/53289679/210064746-16af3ec4-8811-4281-ba6b-4c9bea89006b.jpg)
![4dimms](https://user-images.githubusercontent.com/53289679/210064747-07389cf8-8456-468c-82bb-629f010cdb83.jpg)

1dimm.jpg shows situation with one dimm and is similar with any of the 4 dimms

**Comment by x86fr** [comment]
Can you please try the latest nightly build?

**Comment by JuLuers** [comment]
Is there an ISO-file of latest nightly build available?

**Comment by martinwhitaker** [comment]
Nightly build ISOs are available at https://memtest.org/dev

**Comment by JuLuers** [comment]
Test passed. Great! Thank you!

By the way: 
It shows same DIMMs information (i.e. "RAM: 19600MHz (DDR5-39200) CAS 386-1064-553-553" and "DDR5-39200 XMP - Kingston KF560C36-16 (2022-W42)"). This is not correct, is it? 
Displayed memory bandwidth fits to 3600MHz, which is standard for this hardware.
My understanding is that the uppest frequency for these DIMMs is 4800MHz.

**Comment by debrouxl** [comment]
The DIMM data can be retrieved on some computers by `decode-dimms` from Linux i2c-tools. See [#203](https://github.com/memtest86plus/memtest86plus/issues/203#issuecomment-1309425190) for the commands you'll need to run, after installing i2c-tools through your package manager or compiling it.
Alternatively, for Windows, could you post a CPU-Z "validation link" for your computer ?

**Comment by x86fr** [comment]
SPD decode issue is a duplicate for #110. If Asus can't solve this quickly, I will try to find a workaround (but this involve proprietary code that I would like to avoid if possible).
