### ISSUE TITLE
memtest86plus is not testing all RAM memory

### ISSUE THREAD

**Issue by UttarwarSunil** [memtest86plus/memtest86plus#239]
Hi Team,

I have 32GB installed system. I am running mt86plus64.grub.iso from bootable USB and observed that below memory range it is not running all 10 algorithms.
Memory Range - 1GB - 2GB (but running the test from 1GB to 1.93GB), please find below snapshot.

![Capture](https://user-images.githubusercontent.com/70257439/213163545-462d244f-a02c-4b7d-8df5-05f94e3cdd86.JPG)

I selected the address range from 1.93GB to 2GB, but it is not dispalying testing address range and running below 2 algorithms.
Test 1 : Address test, own address in window
Test 2 : Address test, own address + window

Please let us know if this is expected behaviour.

How can we run all 10 algorithms for 1.93GB - 2GB?

**Comment by x86fr** [comment]
The memory on a modern computer is not necessarily mapped in a linear way. E.g.: 16GB of RAM can be virtually mapped from 0-15GB and then to 16-17GB with a hole between 15GB and 16GB.

It seems that your computer uses a memory map with a hole between 1.93GB and 2GB (which is very common). The whole physical memory is still being tested.

**Comment by debrouxl** [comment]
A variant of a FAQ entry and #193 , indeed.
