### ISSUE TITLE
Serial Output does not work on headless UEFI platform without GOP

### ISSUE THREAD

**Issue by yoshinoyatoko** [memtest86plus/memtest86plus#240]
Hi
I found a problem during i tested memtest86plus.
On a platform without GFX/VGA function, i tried to use ttyS0 as memtest86plus output device, but failed.
When i run it in a uefi shell environment without GFX/VGA functions but with a serial console as a interactive console, it displays:
"not find GOP!"

Maybe we can enhance it that it doesn't need to rely on GOP closely.
Maybe user could select memtest86plus just output UI&progress info just through serial port.

best wishes

**Comment by x86fr** [comment]
That's correct, but the serial output is just a copy of the content of the framebuffer. 
I'm not sure how this can work without GOP. The change is probably not trivial.

**Comment by martinwhitaker** [comment]
The screen output is first written to a shadow buffer, then copied to or rendered to the real video buffer. The serial output comes from the shadow buffer, so all we need to do is bypass the copy/render to the real video buffer if there isn't one. This shouldn't be too hard. We should also output a suitable message to the EFI console, which is presumably routed somewhere else in a headless system.

@x86fr , don't know why you added the bug label - it looks like an enhancement request to me.

**Comment by x86fr** [comment]
yes, I hesitated. Technically "bug" is for "something isn(t working", which is the case here. But it could be seen as an enghancement.

**Comment by yoshinoyatoko** [comment]
Thank you very  much!

**Comment by yoshinoyatoko** [comment]
Hi
I tested v6.10 on my real motherboard, it failed to run.
On the uart console, it tips:
set_screen_info() failed
efi_setup() failed

My test steps as below:
1. Disable UMA(motherboard integrated GFX card) by BIOS Setup UI
2. Enable console redirection by BIOS Setup UI
3. Run memtest plus tool on this uart console

in the same test steps, run commercial memtest version is ok.

**Comment by x86fr** [comment]
Did you enabled the serial console?

**Comment by yoshinoyatoko** [comment]
Hi, Martin:
Thanks a lot!
It works

**Comment by martinwhitaker** [comment]
The fix will be included in the next release.
