### ISSUE TITLE
Direct boot on 32-bit EFI systems is broken

### ISSUE THREAD

**Issue by martinwhitaker** [memtest86plus/memtest86plus#243]
When booting the standard memtest.iso on a real 32-bit EFI system or using qemu with the OVMF ia32 BIOS, boot fails with the message "failed to get handle for loaded image protocol". Booting via GRUB is not affected.

git bisect indicates this regression was introduced by commit 04980dfda346fd0f7e6cb51d8e5b1ea88327b9c4.

**Comment by x86fr** [comment]
Beside Atom N270/N280s, are you aware of any other 32-bit UEFI platform? I'm trying to find a board to check.

**Comment by martinwhitaker** [comment]
My understanding is that anything based on the Intel Bay Trail platform was obliged (by Intel) to use 32-bit EFI. I have an Asus X205TA which has a Z3735 CPU.

**Comment by x86fr** [comment]
I've just plugged a MSI J1800I board featuring a Celeron J1800 (Bay Trail). Unfortunately, the EFI is 64-bit (v2.31).
I have an older D510 board (Pineview 64-bit) and also a N270 board (Diamondville 32-bit). Will try.

**Comment by x86fr** [comment]
The Intel D510MO board (based on Atom D510) can't boot anymore :-/
The Intel D945GSEJT board (based on Atom N270) does not use EFI (BIOS only, which works fine).
Will dig more in the closet... 🤔

**Comment by x86fr** [comment]
Finally resurrected the D510MO using black magic. Its EFI BIOS (circa 2001) is very archaic, with very few options related to EFI and no shell. 

The PXE/gPXE options still uses legacy BIOS, but I'm able to boot a .efi file when placed in /EFI/BOOT. 
Unfortunately, it only load bootx64.efi (works fine) and ignore bootia32.efi, so I suppose the UEFI on this board is 64 bit.

**Comment by martinwhitaker** [comment]
You want an Intel Atom Bay Trail tablet from circa 2013 to 2015. I bought mine to enable me to add/test support for 32-bit UEFI in Mageia.

**Comment by x86fr** [comment]
Finding one able to boot the 32bit .efi via PXE would be great. I'll dig eBay...

**Comment by martinwhitaker** [comment]
Fixed in 6.10.
