### ISSUE TITLE
Support for MMIO-based UART

### ISSUE THREAD

**Issue by UttarwarSunil** [memtest86plus/memtest86plus#249]
Hi Team,

We are using headless system and want to run memtest86plus in UART MMIO mode. We are able to run memtest86plus in UART legacy IO mode using below steps
# kexec -l memtest.bin
# kexec -e

Is memtest86plus is supported in MMIO mode? If yes, please shared steps for running it.

**Comment by x86fr** [comment]
PS : Can you please describe how you use Serial MMIO?

**Comment by UttarwarSunil** [comment]
Thanks, I will work on the shared patch and see if it works.

**Comment by UttarwarSunil** [comment]
I verified the shared patch is already integrated in the latest version. I am able to find all the changes in system/serial.c file. I think there is a flag available to set mmio mode in system/serial.c file(console_serial.is_mmio).

Tried with console_serial.is_mmio flag set to true but unable to see memtest running from console. Do we have any other changes for MMIO mode to work?

Thanks
Sunil

**Comment by anarsoul** [comment]
> Tried with console_serial.is_mmio flag set to true but unable to see memtest running from console. Do we have any other changes for MMIO mode to work?

It's not enough to set it to true, you also need to get base address from somewhere and likely base clock, since it is likely to be different from 1843200 Hz.

As a quick hack you can set your base address to something with this patch:

```
diff --git a/system/serial.c b/system/serial.c
index a825318..8c196cb 100644
--- a/system/serial.c
+++ b/system/serial.c
@@ -101,13 +101,13 @@ void tty_init(void)
     unsigned char lcr;
 
     console_serial.enable       = true;
-    console_serial.is_mmio      = false;
+    console_serial.is_mmio      = true;
     console_serial.parity       = SERIAL_DEFAULT_PARITY;
     console_serial.bits         = SERIAL_DEFAULT_BITS;
     console_serial.baudrate     = tty_params_baud;
     console_serial.reg_width    = 1;
-    console_serial.refclk       = UART_REF_CLK;
-    console_serial.base_addr    = serial_base_ports[tty_params_port];
+    console_serial.refclk       = UART_REF_CLK; // you may want to update it
+    console_serial.base_addr    = (uniptr_t)0x90e1d000;
 
     /* read the Divisor Latch */
     uart_status = serial_read_reg(&console_serial, UART_LCR);
```

But for a proper fix you'll have to implement UART enumeration - it's either PCI (for Intel) or ACPI (for AMD) device.

**Comment by x86fr** [comment]
I'm working on a more complete implementation. It will be pushed in a few days.

**Comment by anarsoul** [comment]
> I'm working on a more complete implementation. It will be pushed in a few days.

Feel free to ping me if you need to test it. I have a headless system with UART over MMIO
