### ISSUE TITLE
Dealing with Secure Boot

### ISSUE THREAD

**Issue by x86fr** [memtest86plus/memtest86plus#25]
Secure Boot-enabled PCs (now mandatory since Windows 11) will be a major issue for Memtest86+. 

As a GPL software, we can't have our binary signed by Microsoft for a fee like passmark's closed-source memtest. 
(Well, every GPLv3 software are clearly blacklisted, but it seems there is a (tiny) possibility to have a GPLv2 software signed by Microsoft.)

shim is another option but the process looks harsh. 

We will probably need the support of a major distro (Debian?) to be able to chain-load Memtest86+ from a signed GRUB. 

I'm also thinking about some hack to bypass Secure Boot in last resort... Doable but very dirty.

Any idea?

**Comment by gordboy** [comment]
What about just making the header big enough for the users to sign their own binaries with their own MOK, for now. And look at other options later.

I was horrified when I went thru all the palaver of creating and enrolling keys only to find that the efi binary was unsuitable for signing ... :)

**Comment by x86fr** [comment]
@vathpela is working on this on PR #34

**Comment by corvus1** [comment]
Secure Boot is not mandatory with win11. UEFI booting is, if you want to upgrade from win10. For a fresh install, nothing is mandatory, you can install on a core2duo if you like pain and suffering. :-) 

But point is, the actual requirement is the PC being booted in UEFI mode at the time you're upgrading. After you've done that, you can boot in CSM for memtesting purposes if you want to.

**Comment by AADJND5** [comment]
Sorry if it's off topic. Why in BIOS the program is loaded on the whole screen, but not on the whole in UEFI, black stripes on top and bottom, like a wide screen.

**Comment by AADJND5** [comment]
Can this be fixed ?

**Comment by corvus1** [comment]
I have a very old laptop that does that in text mode. There is a setting in BIOS to stretch the image to the full size of the screen, but I wouldn't say it makes it look any better. 

Why, though? Does it interfere with the function?

**Comment by AADJND5** [comment]
No, it doesn't interfere with work. It just looks more comfortable. Can I add automatic loading of the screen resolution ? It's just a wish. Thank you for your work and your program.

**Comment by martinwhitaker** [comment]
> Sorry if it's off topic. 
Please don't hijack issues. Start a new thread in the discussions section.

**Comment by corvus1** [comment]
@martinwhitaker  Sorry. :-)

**Comment by x86fr** [comment]
Secure Boot is mandatory for any SI (system integrator) that install Windows 11 on their PCs. 
That mean every computer assembled by a third party with a Microsoft licence must have SecureBoot and TPM enabled. 

And so, these computers can't run Memtest86+ out of the box. That's why supporting secure boot is the top priority.

**Comment by gordboy** [comment]
This has been dragging on for months with no sign of any progress, let alone resolution.

Top Priority implies some sort of continuous action, and a concerted effort. I am seeing neither.

**Comment by x86fr** [comment]
I don't have the knowledge to do it right now.

But of course, feel free to help!

**Comment by obiwan-bartek** [comment]
Are there any plans to remove support for "Disabling Secure Boot" in UEFI Setup for new PCs? If not, then it will be still possible to boot memtest+ with a little effort of disabling Secure Boot once. MemTest+ is most likely used mainly by power users, not newbies, who do not know how to disable Secure Boot.

**Comment by x86fr** [comment]
The plan is to work with secure boot enabled and the default Microsoft key (directly or via chainloading)

**Comment by lranixonl** [comment]
A clarification for Secure Boot in Windows 11. The UEFI must support Secure Boot, but it may be disabled and Windows 11 can be installed and boot with no problem. It would be imposible to use Windows 11 and Linux (or other OS) otherwise.

For OEMs is Secure Boot must be enabled, but end users can disable it.

**Comment by ValZapod** [comment]
Are the latest binaries on the site signed? Will update then.

**Comment by x86fr** [comment]
They're not signed but they support signing.

**Comment by eduarddejong** [comment]
Hi! Today I tried to sign the memtest.efi binary file from memtest86+ using my own created MOK key and this kind of worked, in the sense that the message did not indicate an error like with pcmemtest (with which any attempt to sign it always resulted in an error about header size).

This is all the same way how I sign Linux kernel binaries, all following the instructions described on: https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot.

The next step I do here is renaming the signed binary to grubx64.efi and placing Fedora's Shim loader in the same directory, which is signed with the proper Microsoft key.
I use https://aur.archlinux.org/packages/shim-signed for this, which is also a hyperlink on the above mentioned instructions page.

However this does not work, when booting I am still getting a validation error on the binary.
Is there something I need to do differently in order to make this work or is this still a kind of limitation of memtest86+?

**Comment by x86fr** [comment]
This can't work because the chain of trust is broken: shim is not able to chainload your signed binary because it doesn't trust your personal MOK Key. It only trusts binaries signed by arch.

You must enroll your MOK key (same used to sign the memtest86+ binary) directly in your BIOS and boot the memtest86+ binary directly. 

(At some point, we'll ask the shim team for a signed shim binary with our own key. Then we'll be able to sign memtest86+ binaries and boot directly - using shim - on any Secureboot-enabled PCs)

**Comment by sskras** [comment]
@x86fr commented [Mar 25, 2022](https://github.com/memtest86plus/memtest86plus/issues/25#issue-1180198051):

> As a GPL software, we can't have our binary signed by Microsoft for a fee like passmark's closed-source memtest. (Well, every GPLv3 software are clearly blacklisted, but it seems there is a (tiny) possibility to have a GPLv2 software signed by Microsoft.)

Any pointers on the difference? I thought binary code distribution has nothing to do with adding binary data to it.
It would be interesting to read about specific restrictions raised by Microsoft here.

**Comment by howl** [comment]
I'm using sometime ago sudo mokutil --disable-validation.

That is only needed to be executed one time and make all shims that boot in the computer where it was executed to show a warning at boot "Booting in insecure mode" and to be able to boot unsigned binaries under Secure Boot. I started to use it because now GRUB2 doesn't load fonts that are not signed, but also makes memtest86+ to boot with Secure Boot enabled. The only issue I have encountered is booting efi shell as it fails, but is the only thing I haven't been able to boot.

**Comment by howl** [comment]
Forget to mention that booting Windows within a GRUB2 booted that way make Windows unable to use memory protection or something like that, a warning appears in windows security center.

**Comment by speculatrix** [comment]
I was recently issued with a Dell Precision 5690, and I was able to install Fedora 41 (x86-64) without any significant problem. (see below for a comment), and installed the package memtest86+-7.20-1.fc41.x86_64

it is not possible to disable secure boot at all. I can disable the TPM but that doesn't cause secure boot to then ignore the lack of a sig on the memtest86+. So I would like to find a way to use the shim to chainload memtest, and hence arrived here.

----
Aside:

main problem with dual boot:  I set up a fat32 partition so I can share data between windows and linux. I have to boot windows each week to pass the required mandatory laptop audit process for the IT department. Windows then turns on bitlocker on the fat32 partition. Fortunately I have local admin so I can stop it, but then have to wait for bitlocker to reverse the encryption in progress. Also, I have accidentally tripped bitlocker auto unlock and now have to enter the bitlocker recovery key each time I boot windows, which is a PITA. Remember to save the recovery key before installing linux!!

**Comment by x86fr** [comment]
You can generate a key pair, then sign a version of Memtest86+ yourself. Next time you deal with a computer where secureboot is impossible to disable, you just have to enroll your public key in the BIOS of your motherboard. 

Any way, on latest Dell BIOS, the Secure boot disable option is often still there, but hidden under the "Advanced Setup" switch (usually on top left corner).

**Comment by epman100** [comment]
> I was recently issued with a Dell Precision 5690, and I was able to install Fedora 41 (x86-64) without any significant problem. (see below for a comment), and installed the package memtest86+-7.20-1.fc41.x86_64
> 
> it is not possible to disable secure boot at all.

read [this section of the Dell Precision 5690 manual](https://www.dell.com/support/manuals/en-us/precision-16-5690-laptop/precision-5690_owners_manual/system-setup-options?guid=guid-f1d455fe-7eea-4b29-8e25-432814b632ce&lang=en-us) on how to either disable or enable secure boot in the UEFI/BIOS setup

**Comment by crkinard** [comment]
> Secure Boot is not mandatory with win11. UEFI booting is, if you want to upgrade from win10. For a fresh install, nothing is mandatory, you can install on a core2duo if you like pain and suffering. :-)
> 
> But point is, the actual requirement is the PC being booted in UEFI mode at the time you're upgrading. After you've done that, you can boot in CSM for memtesting purposes if you want to.

It is a requirement of many institutions. Tired of this being a cop out because commenters only load computers in their basement.
