### ISSUE TITLE
Add support for newer VIA CPUs (like Eden X2 U4200)

### ISSUE THREAD

**Issue by thamesynne** [memtest86plus/memtest86plus#250]
Running Memtest86+ on an HP T510 thin client, which is powered by a VIA Eden x2 U4200, it gets the speed right (1000MHz), but cannot detect the temperature or the cache layout (reports all cache as 'N/A') or memory layout, nor any bandwidths. It also reports the CPU as having 1 core and 2 threads, rather than 2 & 2.

(Is this OK as an issue, or should it be a feature request?)

**Comment by x86fr** [comment]
Added to my TODO list :)

**Comment by x86fr** [comment]
Fortunately, I found a EPIA M900 motherboard with a Quad Core and the same issue. I'll correct this just after 6.10 release. 😀 
![image](https://user-images.githubusercontent.com/38105886/216141747-dbd6c47d-bf18-4ffc-aa95-979ef2cbe64d.jpeg)

**Comment by x86fr** [comment]
Fixed. ![image](https://user-images.githubusercontent.com/38105886/218273925-984a5d2d-8562-4822-a294-599c447c5698.jpeg)

**Comment by thamesynne** [comment]
Thanks - just tried it, and it works a treat!
