### ISSUE TITLE
Old versions missing in downloads - 486 and Pentium-1 compatible

### ISSUE THREAD

**Issue by perchrh** [memtest86plus/memtest86plus#252]
Hi, 
thanks for making some older versions available for download. 
memtest86+ is super for testing vintage computers too. 

For old computers versions 4.10 and 5.01 are especially relevant, and are missing from the new download section at memtest.org

The reason why is because 4.10 is the last version to work on 486 and below, and 5.01 is the last version shipped as a floppy-boot image. That one works with Pentium-1 and later. Please make the mentioned two floppy images available :)

Here, at an older version of the site they are available: 
https://web.archive.org/web/20211208174208/http://www.memtest.org/#downiso

**Comment by x86fr** [comment]
Old version are available here : https://memtest.org/archives

Memtest86+ v6 should also work on any P5 (Pentium) motherboard and probably also on 486 motherboard.

Legacy floppy images are available here:
https://memtest.org/download/archives/5.01/memtest86+-5.01.floppy.zip
https://memtest.org/download/archives/4.20/memtest86+-4.20.floppy.zip

Floppy image for v6 can be compiled using `make floppy.img`

**Comment by perchrh** [comment]
Thanks. The mentioned version 4.10 ia not found there. V 4.20 requires
Pentium I've read.

**Comment by debrouxl** [comment]
There's #120 for improving 486 support in v6+, but it's not ready yet.

**Comment by perchrh** [comment]
Nice! I did the 'make floppy.img' from HEAD of master and it worked on my Pentium-100 :) :)

Master sets march=i586 in CFLAGS, so it won't work on 486. I modified it to i486 and the build was clean and it ran well on this machine. 

![pentium100](https://user-images.githubusercontent.com/222589/215999150-22d261ca-d01d-40bf-85aa-0c69eca81561.jpg)

**Comment by x86fr** [comment]
Even with `march=i586`, it should probably work on 486 (we have various examples).
