### ISSUE TITLE
Please, publish sha512 checksums for published ISO files

### ISSUE THREAD

**Issue by ImustBuySomeBreadToday** [memtest86plus/memtest86plus#256]
sha512 is better than sha256 and files are too small for any meaningful difference in speed of verification

**Comment by x86fr** [comment]
Glad you found the link :)

There is no known collision or vulnerabilities on sha256 to date, so I don't think sha512 will have any real benefit, but it's easy to add, so it's now added ;)

**Comment by debrouxl** [comment]
Maybe the hashes should be added to https://github.com/memtest86plus/memtest86plus/releases/tag/v6.10 as well ?
