### ISSUE TITLE
PXE Files Missing on Main Web Page

### ISSUE THREAD

**Issue by steve1515** [memtest86plus/memtest86plus#257]
Under the FAQ on the main www.memtest.org page, one of the questions is listed as:
```
Q: Can I launch Memtet86+ using **PXE?**
A: Yes. Just use memtest.bin (for BIOS PXE) or memtest.efi (for UEFI PXE) as payload for iPXE or PXELINUX. Don't forget to disable Secure Boot. 
```
I don't see a download package for PXE and looking in the other zip files, I don't see `memtest.bin` or `memtest.efi`. This seems a little confusing. Can this be clarified or a PXE zip package be added?

**Comment by x86fr** [comment]
That's correct. They're now added as a "binary" build. (They were built and present on the checksum files, but not present as links.)
![image](https://user-images.githubusercontent.com/38105886/216822970-13cbf5c0-f6d7-400d-aac5-d776b96d12c5.png)
