### ISSUE TITLE
iPXE Graphics Issue

### ISSUE THREAD

**Issue by Seth772** [memtest86plus/memtest86plus#264]
When using:

kernel http://{url}/pxe/memtest.efi
boot

It works, however the screen resolution is messed up. Is there a way to fix this or an argument to set a fixed resolution?

**Comment by debrouxl** [comment]
Could you post a picture of the "messed up" screen, give some basic hardware information about the computer on which you're running memtest86+, and mention the memtest86+ version, unless it's visible in the picture ?

**Comment by Seth772** [comment]
This is on a lenovo T440s laptop:
i5-4300U
4gb RAM
Intel HD Graphics 4400
![20230210_122722](https://user-images.githubusercontent.com/102336139/218160176-182cb27a-09d3-495a-9f11-a9c325bfa106.jpg)

**Comment by x86fr** [comment]
I already saw a similar scrambled screen on Lenovo laptop (T430/T440 series) while booting Win PE over PXE :-/ 
Unfortunately, it looks like a BIOS issue to me. Does Memtest86+ runs correctly when booted from USB? Do you have the latest BIOS installed?

**Comment by Seth772** [comment]
It seems you are correct, just used a VM and there are no issues there. The bios is from 2019, without installing windows it is a pain to get the bios updated since they only have a CD or Application method. I do not have a drive in this laptop.
