### ISSUE TITLE
No start on upsquare

### ISSUE THREAD

**Issue by montjoie** [memtest86plus/memtest86plus#270]
On upsquared (https://up-board.org/upsquared/specifications/) memtest does not boot at all.
I tried fresh memtest git master. (started either with grub/PXE)
I tried also bullseyes memtest86+

Nothing on screen, nothing on serial.
The board fines with debian/gentoo.

**Comment by debrouxl** [comment]
Thanks for the report. Complete lack of output might make this one great "fun" to debug...
Have you tried the usual `nobench nosm nosmp powersave=off`... though if nothing is getting displayed, it may mean that something's going wrong before entering `config_init()` ?

**Comment by montjoie** [comment]
No I dont try all of them, but I will.
Note that even on Linux, this board needed some extra config (on top of x86_64_defconfig) to work.
See https://gerrit.automotivelinux.org/gerrit/gitweb?p=AGL%2Fmeta-agl.git;hb=refs%2Fchanges%2F93%2F20993%2F5;f=meta-agl-bsp%2Fmeta-intel%2Frecipes-kernel%2Flinux%2Ffiles%2Fupsquare.cfg
Perhaps it could help diagnose the problem, need extra tweek to boot ?

**Comment by yoshinoyatoko** [comment]
Maybe you could try to boot with a uefi memtest86+ app in a uefi shell environment?

**Comment by montjoie** [comment]
I tried also EFI memtest.
I tried EFI/non-EFI with nosm nosmp powersave=off nobench.
No change

**Comment by montjoie** [comment]
I finally found the last remaining problem for booting Linux on this board, it NEEDS EFI FrameBuffer.
So I start to believe that perhaps the problem is the memtest86 EFI video.

**Comment by x86fr** [comment]
Without GOP, it can't display at boot.

**Comment by martinwhitaker** [comment]
Near the top of `boot/efisetup.c` change `#define DEBUG 0` to `#define DEBUG 1` and rebuild, then boot in EFI mode. Is anything displayed?
