### ISSUE TITLE
Minor Documentation Error - Boot Options

### ISSUE THREAD

**Issue by NIronwolf** [memtest86plus/memtest86plus#271]
In the list of speeds for activating the serial console port, one of them reads 54600. I believe this is just a typo for the common 57600. But as it says an invalid entry will set another speed, it may be important to have a correct list of options.
I did not try either parameter nor look at any code, but it just looks like a typo.

**Comment by x86fr** [comment]
Fixed in commit  #[a1d046f](https://github.com/memtest86plus/memtest86plus/commit/a1d046fc3ade2b60f5051175e66011774f0d258e)
