### ISSUE TITLE
Odd SMP behavior? "SMP: 1T"

### ISSUE THREAD

**Issue by Hypoon** [memtest86plus/memtest86plus#274]
Background:
- Memtest86+ v6.01
- 2x Xeon E5-2683 v4 (16 cores each)
- Booting the official ISO from a flash device (BMC feature)
- Not Supermicro (I saw something that mentioned a bug on Supermicro hardware)

When I boot, I press F2 a handful of times, making sure I leave it so the text says that I should press F2 to **disable** SMP. I assume that means that SMP is currently **enabled**. I browse through the other configuration options, but I don't change any of them. The menu where I can select the CPU cores only lists two: 0 and 1, with "B" underneath the 0 (presumably this indicates that it booted on core 0). When the test starts, the text says this:
```
CPU: 16 Cores 32 Threads  SMP: 1T (PAR)
Using: All Cores
```
Is that what it should say? 1T instead of 32T?

I have multiple of these systems, and they all behave the same _now_, but I originally acquired them with the BIOS in an unknown configuration. At least one system formerly listed all the individual cores in the configuration menu (not just 0 and 1), until I updated the BIOS and reset all settings to the defaults. Do I need to tweak a BIOS setting?

I get the same behavior regardless of whether I boot using BIOS mode or UEFI mode.

What's the expected behavior? What might have changed when I updated/reset the BIOS? If this is a bug, is there anything I can contribute to help debug it?

**Comment by debrouxl** [comment]
The likely cause of the behaviour you're experiencing is that processor x2APIC mode (which must be the default on that computer model) is not supported by memtest86+ yet :)
For memtest86+ to be able to run in SMP mode, you need to disable it in the BIOS settings menu. For instance, on a HPE DL360 / DL380 Gen9, it's in F9, BIOS settings (RBSU), System Options -> Processor Options.

**Comment by Hypoon** [comment]
After reading the other discussions on x2APIC in Memtest86+, I agree that's likely to be the problem.

I don't want to actually disable x2APIC for the main operating system (even though I'm not approaching 256 cores, I read that it's still useful), but I can try temporarily toggling it to confirm it's responsible.

**Comment by x86fr** [comment]
Please confirm if the issue is linked to x2APIC if possible. 
Anyway, I pushed a PR (#277) that should enable SMT testing on your server.

**Comment by Hypoon** [comment]
Yes, disabling x2APIC in the bios caused it to recognize 64 threads: "CPU: 2S / 32C / 64T       SMP: 64T (PAR)". Also tried the PR. I'll add a comment there.

**Comment by x86fr** [comment]
Duplicate (#70)
