### ISSUE TITLE
Wrong L1 Cache on R5 5600x

### ISSUE THREAD

**Issue by CaptainCoward** [memtest86plus/memtest86plus#278]
Memtest v6.10
The L1 Cache seems to get wrongly reported as 32K though the Processor has 64K of L1 Cache.

**Comment by x86fr** [comment]
Like on many modern CPUs, Zen3 CPUs have a shared L1 cache : 32 KB Data + 32 KB Instructions. 
We only show the Data Cache (the Instruction cache is irrelevant)

**Comment by CaptainCoward** [comment]
Ah sorry,i was confused since Memtest86 (non +) showed 64K.
