### ISSUE TITLE
Keyboard not working on Toshiba Satellite L505 when booting with version 4.3

### ISSUE THREAD

**Issue by rgiuffre** [memtest86plus/memtest86plus#282]
Hello all:
I downloaded version 4.3 to test some newly-installed RAM in a Toshiba Satellite L505.
It boots into the USB Memtest86 V4.3, but the keyboard is not working. So I cannot choose options 1-5.
The keyboard is brand new, and it works otherwise. (BIOS, Windows, etc.)
Is there a way to let it automatically choose the Option 1 (Default) with a countdown to abort?

Thank you for your assistance!

**Comment by x86fr** [comment]
Memtest86 (not +) is a different tool from a commercial company. But you can try our tool. Check https://memtest.org.
