### ISSUE TITLE
Support non-x86 architecture

### ISSUE THREAD

**Issue by yetist** [memtest86plus/memtest86plus#285]
Are there any plans to support non-x86 architectures? For example, use `memtest.efi` on arm64, riscv and loongarch.

**Comment by debrouxl** [comment]
Although it should be technically feasible, the maintainers do not currently have concrete plans to support AArch64, RISC-V or LoongArch, because that's a lot of work, and we simply do not have the appropriate hardware for performing tests. The situation hasn't changed since #147, AFAICT.

**Comment by yetist** [comment]
Perhaps it is possible to prepare for multi-architecture support without hardware.
For example, separate the code related to the architecture and put it in the `arch` subdirectory.

**Comment by yetist** [comment]
There is [memtest](https://github.com/atrosinenko/memtest86-plus-riscv) for riscv, but it is based on an old version and is no longer maintained.
If memtest can provide multi-architecture support, I believe that people with hardware in hand will be happy to add new architectures to it.

**Comment by x86fr** [comment]
As @debrouxl said, it's a significant work and not planned at this time.

**Comment by debrouxl** [comment]
There's nothing stopping third parties, be them employed by a RISC-V / AArch64 / Loongson solution vendor or not, from rebasing the work in that repository onto recent, pcmemtest-derived memtest86+.
