### ISSUE TITLE
Program hangs on a corrupted module

### ISSUE THREAD

**Issue by virxkane** [memtest86plus/memtest86plus#286]
When trying to test some obviously faulty memory module, the program hangs.
Program version 6.10.
Hangs in any tests except 0.
It hangs both in SMP mode and without it.
Expected behavior: the program does not freeze and shows the problem memory area.

Version 5.31b without SMP reboots the computer right away in test 0.
Version 5.31b in SMP mode passes test 0 and hangs in test 1.
The red '+' symbol blinks in the text 'Memtest86+ 5.31b'.

Version 6.00b3 passes test #0 and hangs in test 1 with and without SMP.

PassMark memtest also freezes.

![IMG_0422_sz](https://user-images.githubusercontent.com/36960933/227191814-af8dfa7a-1a17-467b-96af-612a1282fc31.JPG)

![IMG_0437_sz](https://user-images.githubusercontent.com/36960933/227191855-0c93f4f6-f64e-48e5-a0b1-4bf8db2038cb.JPG)

**Comment by x86fr** [comment]
Unfortunately, if the memory subsystem is so unstable that any small program can't run reliably, there is nothing to do.
As you said, the hardware issue is obvious.
