### ISSUE TITLE
"FAIL" banner not closeable and covers important error information

### ISSUE THREAD

**Issue by Qtax** [memtest86plus/memtest86plus#289]
The FAIL banner displays "Press any key to remove this banner" but whatever key you press nothing happens, it's still showing.

The worst part is that it's covering important information about the memory error:

![fail-banner](https://user-images.githubusercontent.com/1556175/227936484-05e8fe6b-c3ad-4b35-b9a3-7be5eeee857d.jpg)

Version: `6.10.ce2c29e.x64`

**Comment by x86fr** [comment]
Is your keyboard working at all within Memtest86+? Eg: pressing F1 displays menu?

**Comment by Qtax** [comment]
Keyboard is working. F1 and esc for example keys are doing what I assume they should, space toggles the text in the status bar.

**Comment by x86fr** [comment]
When you press F1, the banner is still displayed?

**Comment by x86fr** [comment]
Yes, but this has been fixed (and confirmed fixed). But I will check again soon.

**Comment by x86fr** [comment]
I was referring to that specific comment. Many betatesters reported this as fixed, so I will check again asap.

**Comment by martinwhitaker** [comment]
In the meantime, you can use the `nobigstatus` boot command line option to disable the big status banner.

**Comment by x86fr** [comment]
I pushed a more radical fix to main (#[c6b04e5](https://github.com/memtest86plus/memtest86plus/commit/c6b04e5414c0872cf845cbd0f3c12d46d2839239)). 

@Qtax> Please confirm if this works for you.

**Comment by Qtax** [comment]
@x86fr unfortunately I no longer have the defective memory module, so I cannot test the fix.

**Comment by evpustovalov** [comment]
I have the same, can't remove the FAIL banner. F1 or SPACE go to menu or switch scroll, but do not remove the banner. It looks like any key remove the banner but it appears again (shows as banner blink).
