### ISSUE TITLE
Can't boot into Intel D845GVAD2 (Pentium 4)

### ISSUE THREAD

**Issue by matthuszagh** [memtest86plus/memtest86plus#293]
I'm trying to create a bootable memtest86+ USB for an Intel D845GVAD2. I downloaded the 32-bit Linux ISO (https://www.memtest.org/download/v6.10/mt86plus_6.10_32.iso.zip), unzipped wrote it to a USB (`sudo dd if=mt86plus_6.10_32.iso of=/dev/sde status=progress bs=4096`), and tried to boot, but it's not working. In fact, plugging in the USB drive appears to somewhat freeze the boot process. I see the following screen but my keyboard is unresponsive.

![bios](https://user-images.githubusercontent.com/7377393/229912893-1ca48ee2-4f69-4106-8404-5cda9bdf28c3.jpg)

If I repeatedly press F2 early in the boot process I see that same screen except instead of "Press <F2> to Run SETUP" I see something about entering setup, but it never does. I guess this indicates the PS2 keyboard is visible for at least some amount of time.

I was able to boot successfully into xubuntu 18 from the same flash drive.

If I check the USB partitions after installation I see:

```
$ parted /dev/sde print
WARNING: You are not superuser.  Watch out for permissions.
Model: Samsung Flash Drive FIT (scsi)
Disk /dev/sde: 32.1GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End     Size    Type     File system  Flags
 2      1688kB  5882kB  4194kB  primary               esp
```

Will esp work with BIOS? I didn't see a separate installation ISO for BIOS.

Any ideas about what I can do to run memtest86+? Maybe I should try an old version? Did I make an error in the installation process? Thanks!

**Comment by x86fr** [comment]
Can you try the Windows USB creator tool?

**Comment by matthuszagh** [comment]
Just tried, same result.

**Comment by x86fr** [comment]
Can you show the partition table of the USB Key after being formatted by the Windows USB Creation tool?

Also, if available, please try with a smaller usb key (2 or 4GB)

**Comment by matthuszagh** [comment]
Well I just tried again (Windows USB Creation tool) and it worked. Not sure what I did differently but I guess I must have done something wrong the first time. Here's the resulting partition table in case you still want to see it.

```
$ sudo parted /dev/sde print
Model: Samsung Flash Drive FIT (scsi)
Disk /dev/sde: 32.1GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End     Size    Type     File system  Flags
 1      32.8kB  1553MB  1553MB  primary  fat32        boot, lba
```

Does the Windows creation tool have better support than the Linux installation method?

**Comment by x86fr** [comment]
Yes. Some old BIOS (earlier than 2005) have issues booting from a dd'ed ISO image
