### ISSUE TITLE
"Wrong" RAM Slots detected?

### ISSUE THREAD

**Issue by CaptainCoward** [memtest86plus/memtest86plus#294]
Not sure if this is even worth creating an issue.
But it seems like Memtest is reporting the false Ram Slots on my B550 A Pro Board
For example: Memtest would report that i have RAM in slot2&3  in use when in reality i have my Ramsticks in 2&4 (CPU-Z reports that as well). I'm not sure if this is a bug. Though i didn't read any other report about that so i thought i would report it.

**Comment by x86fr** [comment]
RAM slot are ordered from the addresses on the SMBUS chain (of SPD EEPROMs). Manufactures can then choose to call them whatever they want for marketing or other purposes. Eg : on silkscreen, from nearest to farthest from the CPU, some of them use a real physical banks numbering dram slots like 1,2,3,4/4,3,2,1, while other prefer to use 1,3,2,4/4,2,3,1. The later is often considered easier for the end-user to understand (ie: in which order he must populate the dram modules).
