### ISSUE TITLE
VirusTotal Flagged Installer

### ISSUE THREAD

**Issue by WJS11** [memtest86plus/memtest86plus#295]
Hello, hopefully this is a false positive, but the site VirusTotal flagged the installer as from two of its vendors. The results can be seen here:
https://www.virustotal.com/gui/file/00b4f3886785aba95855116af21f90a814517d94fca0a861e7ee737df8125662

Thanks!

**Comment by x86fr** [comment]
False positive on 3 obscure AV out of 70.
