### ISSUE TITLE
Clarify in v6.10 changelog that Memtest86+ binaries are NOT signed by Microsoft

### ISSUE THREAD

**Issue by Trikenstein** [memtest86plus/memtest86plus#298]
The [V6.10 Changelog](https://www.memtest.org/) states

```
Add support for Secure Boot Signing
```

is confusing as this could be mis-interpreted as Memtest86+ v6.10 is ready on system with Secureboot enabled. After experiencing  "error: bad shim signature" a friend had directed my to #283 

> While Memtest86+ 6.10 now supports Secureboot signing, the binary is not currently signed by Microsoft. To use Memtest86+ 6.10 with a Secureboot-enabled computer, you have to sign the binary by yourself, then enroll the private key to your Secureboot key library ... or wait until we find a more universal solution on your side. We're working on it.

In the meantime, I think it would be helpful to indicate this detail in the v6.10 changelog

**Comment by x86fr** [comment]
This is already added to memtest.org as the main FAQ "Booting Issues". 

I'll add a note about Secureboot in README.md
