### ISSUE TITLE
Memtest86+ 5.01 hangs in Test #7 (block move) 

### ISSUE THREAD

**Issue by ahmogit** [memtest86plus/memtest86plus#299]
The following behavior was reported on the Arch linux bug tracker several years ago:

    https://bugs.archlinux.org/task/65466

Just stumbled upon it myself, same symptom, same method of reproduction. Hardware: Lenovo T-510 4940-4VU, with two banks of 4 GB each. More info upon request if anyone's interested.

Note that the test is not _explicitly_ failing per se; the memtest86 program simply hangs, i.e. stops displaying any sign of activity, other than the little "+" at the top left (in the string "Memtest86+") which remains flashing at about 1 Hz rate. But there is no explicit declaration of any RAM error, and no sign of any other activity going on.

**Comment by Nable80** [comment]
I think you came across a well-known issue: https://web.archive.org/web/20191216000815/http://forum.canardpc.com/threads/117454-PATCH-Fix-for-Freeze-on-test-7-in-SMP-mode

There's a patch for it but it wasn't deployed widely and branch 5.x seems to be abandoned. Did you try an up-to-date version, i.e. memtest86+ v6.x?

**Comment by ahmogit** [comment]
Thanks for the info, sounds like it is indeed the same issue.

No, I have not tried memtest86+ 6.anything, but will do so when time permits and post results here.

Thanks.

**Comment by debrouxl** [comment]
Yup, trying a newer version is the way to go, and that way, you'll also be able to take advantage of the improved capabilities of the newer version: native 64-bit binary, BIOS+UEFI compatibility (including UEFI Secure Boot, though you'll have to sign the binary yourself), support for more simultaneous cores, USB keyboard support, SPD reporting working on a wider range of hardware, etc.

**Comment by x86fr** [comment]
Memtest86+ v5 is now outdated and unsupported. Please switch to v6, which is much stronger regarding to SMP support.

**Comment by ahmogit** [comment]
Thanks, and sorry for the noise in reporting this. I had been running memtest86+ from the current version of UBCD,  and mistakenly assumed that the memtest86+ version installed there (V5.01) was up to date.

I just tried V6.10 and it works fine.

Apologies for the noise.
