### ISSUE TITLE
Temperature display for more CPU models

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#3]
pcmemtest-derived memtest86+ does not yet support temperature display for some processor models, e.g. from AMD.

NOTE: making a reliable implementation of such functionality can be nontrivial, and in fact, even the Linux temperature drivers can return dubious data for some models. In the output of `sensors` on Linux 5.10 kernel + Debian 10/11 amd64, I can still see one air-cooled computer equipped with an AMD Bulldozer processor pretend that its current CPU temperature at idle operation is around or below ambient room temperature. With cryogenic cooling, sure, but with air cooling ?

**Comment by martinwhitaker** [comment]
At f7ae4dd, my Athlon 7750 still reports ~7 degrees below room temperature at the start of testing.

**Comment by x86fr** [comment]
Which motherboard do you use?

**Comment by martinwhitaker** [comment]
ASUS M4N72-E

**Comment by x86fr** [comment]
I probably can't fix that because it looks like an errata on AM2 CPU. 😕

From: https://developer.amd.com/wordpress/media/2012/10/41322.pdf

![image](https://user-images.githubusercontent.com/38105886/160303150-45d61b99-9d8f-4604-9397-e2c3359d5ff6.png)

It seems that even the linux hwtemp kernel module disable the temperature measurement on your CPU:

From: https://github.com/torvalds/linux/blob/master/drivers/hwmon/k10temp.c 

```
static bool has_erratum_319(struct pci_dev *pdev)
{
	u32 pkg_type, reg_dram_cfg;

	if (boot_cpu_data.x86 != 0x10)
		return false;

	/*
	 * Erratum 319: The thermal sensor of Socket F/AM2+ processors
	 *              may be unreliable.
	 */
	pkg_type = cpuid_ebx(0x80000001) & CPUID_PKGTYPE_MASK;
	if (pkg_type == CPUID_PKGTYPE_F)
		return true;
	if (pkg_type != CPUID_PKGTYPE_AM2R2_AM3)
		return false;

	/* DDR3 memory implies socket AM3, which is good */
	pci_bus_read_config_dword(pdev->bus,
				  PCI_DEVFN(PCI_SLOT(pdev->devfn), 2),
				  REG_DCT0_CONFIG_HIGH, &reg_dram_cfg);
	if (reg_dram_cfg & DDR3_MODE)
		return false;

	/*
	 * Unfortunately it is possible to run a socket AM3 CPU with DDR2
	 * memory. We blacklist all the cores which do exist in socket AM2+
	 * format. It still isn't perfect, as RB-C2 cores exist in both AM2+
	 * and AM3 formats, but that's the best we can do.
	 */
	return boot_cpu_data.x86_model < 4 ||
	       (boot_cpu_data.x86_model == 4 && boot_cpu_data.x86_stepping <= 2);
}
```

Are you aware of any software reporting a correct temperature on your CPU?

**Comment by x86fr** [comment]
About the Athlon 7750, I've checked many entries in the CPU-Z database and it seems that almost all of them report an erroneous temperature around 18°C. Ex: https://valid.x86.fr/4p3dav

**Comment by martinwhitaker** [comment]
Hmm, yes, `sensors` on Linux reports the correct temperature, but it is using the ACPI interface. k10temp does indeed give the low temperature reading. Seems like we need to disable temperature reporting on the affected AMD CPUs.

**Comment by x86fr** [comment]
Closing this as Memtest86+ now supports temperature display on a lot of different platforms from the last 20 years. 

If any need related to CPU temp detection, a more specific issue must be open.
