### ISSUE TITLE
32bit binary give unexpected interrupt on cpu 0

### ISSUE THREAD

**Issue by Fantu** [memtest86plus/memtest86plus#30]
Hi, I'm doing some tests for first build for debian experimental (https://salsa.debian.org/debian/memtest86plus/-/tree/debian/experimental), based on snapshot from commit 88017f007fb07b3e92fdc3baea45b2d11d5e9000
Testing on "msi gp62 2qe leopard pro" notebook on bios mode the 32bit binary give "unexpected interrupt on cpu 0", the 64bit one instead works (compiled on same device)
https://imgur.com/a/W4trF1X

besides this problem it is better if in the grub I force the 64bit and 32bit binary only if the cpu does not support the 64bit?

thanks for any reply and sorry for my bad english

**Comment by x86fr** [comment]
Commit b6e2a2ace8fbeb318030fe63d2f442ce47c5d7b1 should solve this. can you please try?

About grub yes :  best solution would be to use 64 bit by default, and 32 bit if CPU doesn't support 64 bit.

**Comment by x86fr** [comment]
@Fantu Can you try if the issue is solved with latest commit?

**Comment by Fantu** [comment]
sorry but I was/I'm busy on other thing in these days and I not have time to continue with memtest86+ package (do a new snapshot, add serial console on grub configuration and doing other tests)
I suppose I'll have enough time only next week

**Comment by Fantu** [comment]
I done a new snapshot and tested today and I confirm the bug is solved
we did also a first upload to debian experimental (will be available shortly)
