### ISSUE TITLE
v6.20 crashes on startup (Acer Aspire One/Atom N270)

### ISSUE THREAD

**Issue by nelsonhef** [memtest86plus/memtest86plus#309]
Booted Memtest86+ v6.20 on an Acer Aspire One D250 (KAV60) with an Intel Atom N270 CPU and it crashes right at startup. Tried to pass _nosmp_, _nobench_ and _nosm_ boot options but none of them worked. v6.10 works fine and passes all tests.
 
![IMG_20230517_091820750](https://github.com/memtest86plus/memtest86plus/assets/87081197/825f7e93-3254-4629-a977-065adf184eee)

**Comment by x86fr** [comment]
Is it UEFI or BIOS/CSM boot? It's probably linked to commit #1a38f513 (MSR is probably not available on your CPUs). If you can access to the initial config menu (before test start), can you try to disable temperature reporting?

**Comment by nelsonhef** [comment]
It's BIOS boot. It crashes before the config menu, so i can't disable the temperature reading, but you're probably right at the culpirit commit. I've found an old thread from lm-sensors and indeed these old Atom CPUs don't have this register, coretemp sets it at 90ºC as per Intel docs.

https://lore.kernel.org/lkml/20100517094340.900829891@osadl.org/

[lscpu.txt](https://github.com/memtest86plus/memtest86plus/files/11499336/lscpu.txt)
[sensors.txt](https://github.com/memtest86plus/memtest86plus/files/11499337/sensors.txt)

**Comment by x86fr** [comment]
I will push a fix soon for this.

**Comment by x86fr** [comment]
Issue confirmed to be the MSR read here:
https://github.com/memtest86plus/memtest86plus/blob/0b251df68d2111760ae2324da1f4618c5f85bacf/system/temperature.c#L64-L67

I will implement a safe MSR read and/or fix this read for Atom (today or tomorrow).

**Comment by nelsonhef** [comment]
Understood. I saw that you already have implemented a function workaround (get_specific_TjMax) for Yonah CPUs, maybe these older Atom cores can be added there. As I understood a similar aproach was made in the Linux kernel.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hwmon/coretemp.c#n103

**Comment by x86fr** [comment]
A cleaner generic solution for GPF consecutive to unsafe MSR read is available on PR #310. 
Now I'm adding the specific TjMax for these CPUs to main.

**Comment by nelsonhef** [comment]
Booted and worked fine with commit de4f476. Thank you.

![IMG_20230518_121126942](https://github.com/memtest86plus/memtest86plus/assets/87081197/b69f7f61-0d0d-4d70-b923-7d7075903b29)

**Comment by pavtm** [comment]
Hello. I'm dowloaded new version 6.20 stable, and last nightly. It's crashed from start.
Motherboard (intel) w integrated atom d2500. I'm run tests in any modes (grub) and legacy/uefi
![2023-05-18 23-06-11](https://github.com/memtest86plus/memtest86plus/assets/54793916/1dd75252-12be-4960-b074-794c3c1b94b8)

**Comment by x86fr** [comment]
The fix has been pushed today. It will be available on tomorrow nightly build. (or right now if you can build from source)

**Comment by pavtm** [comment]
Sorry, I didn't read carefully. I'm wait tomorrow.

**Comment by x86fr** [comment]
Should be OK now.
