### ISSUE TITLE
Boot ISOs Don't Work on UEFI TianoCore edk2-ovmf 20230301gitf80f052277c8

### ISSUE THREAD

**Issue by damaestro** [memtest86plus/memtest86plus#311]
The v6.20 boot ISOs don't boot via UEFI currently when using edk2-ovmf 20230301gitf80f052277c8. They do boot via BIOS seabios-bin-1.16.2-1.fc38.noarch.

Tested booting these via gnome-boxes UEFI on F38:

* https://www.memtest.org/download/v6.20/mt86plus_6.20_64.iso.zip
* https://www.memtest.org/download/v6.20/mt86plus_6.20_64.grub.iso.zip

**Comment by martinwhitaker** [comment]
They do boot using edk2-ovmf-20201127stable-1.mga8, tested with the following commands:
````
qemu-system-x86_64 --enable-kvm -m 3G -vga std -cdrom ~/tmp/mt86plus_6.20_64.iso -boot d -bios /usr/share/edk2/ovmf/OVMF_CODE.fd
qemu-system-x86_64 --enable-kvm -m 3G -vga std -cdrom ~/tmp/mt86plus_6.20_64.grub.iso -boot d -bios /usr/share/edk2/ovmf/OVMF_CODE.fd
````

**Comment by damaestro** [comment]
@martinwhitaker apologies. It does work, secure boot was turned on. UEFI and BIOS boot both work.

Thanks.
