### ISSUE TITLE
Double time speed on AMD 3D processor

### ISSUE THREAD

**Issue by Bahram-Alinezhad** [memtest86plus/memtest86plus#315]
UPDATE: The same problem with Memtest86+ 6.2!

Hi
Thank you very much for developing this very useful memory test tool.

As you know, AMD 3D processors (with extra 3D V-Cache) are one of best gaming workstation processors so that it can beat even Intel gen-13 (Raptor Lake) core-i processors in some games. For example see the reviews below:

https://www.anandtech.com/show/17337/the-amd-ryzen-7-5800x3d-review-96-mb-of-l3-3d-v-cache-designed-for-gamers
https://www.techpowerup.com/review/rtx-4090-53-games-core-i9-13900k-vs-ryzen-7-5800x3d/

Due to a bug in Memtest86+, the memory speed shows half of the real speed and this is a bad impact to this processor family as well as to its manufacturer's reputation. As you see in attached video, The wall-time of Memtest86+ 6.1 passes double speed of video time which equals to real time. This results in half value calculation of memory speed. For the same reason, it shows CPU clock (CLK) half the real value.
Please remove this bug (as soon as possible) to avoid its great affect on CPU market and buyer choice.

Thank you for your notice,
Bahram Alinezhad,
Rudehen, Tehran, Iran.

https://github.com/memtest86plus/memtest86plus/assets/22405142/56aec98d-6367-44d1-a0cb-4a45dc31246f

![IMG_20230512_141858_604](https://github.com/memtest86plus/memtest86plus/assets/22405142/346a3815-bc78-46e3-8ba9-45414feb3a4c)

**Comment by Bahram-Alinezhad** [comment]
Known Limitations and Bugs

Please see the list of [open issues](https://github.com/memtest86plus/memtest86plus/issues) and [enhancement requests](https://github.com/memtest86plus/memtest86plus/discussions) on GitHub.

Feel free to submit bug reports!

**Comment by Bahram-Alinezhad** [comment]
Closing absolutely without giving any discussion or reason?!

**Comment by Bahram-Alinezhad** [comment]
Please see the attached video. The wall-time of Memtest86+ passes double speed of video time (or real time). This results in half value calculation of memory speed. For the same reason, it shows CPU clock (CLK) half the real value.
Not fixed on Memtest86+ 6.20!

**Comment by x86fr** [comment]
There is an open issue for this ; #601

**Comment by Bahram-Alinezhad** [comment]
I appreciate your reminder that there's a more recent issue related to this. Considering the original issue I reported three years ago had additional context such as screenshots and screen recordings, it might have been more efficient to mark this as a duplicate of the older issue. Nevertheless, I appreciate you bringing this to my attention and I'll follow the progress of the new issue as well.
