### ISSUE TITLE
4 wrong symbols on the display in the time-status area. Samsung R505, DDR2

### ISSUE THREAD

**Issue by 3pt142** [memtest86plus/memtest86plus#319]
On the Samsung R505 laptop, I have a bug in the time-status area with all 10+ my 1 or 2 GiB memory sticks in any combinatoin (1, 1+1, 1+2 etc.). There are static 4 wrong symbols, photo attached. These symbols do not appear immediately after starting the program, but when the invitation to press the F-key disappears and the testing itself begins. Time remains readable. With rare 4 GiB sticks or with any sticks in 32-bit mode, there is no bag.
Bug with 2 GiB stick in 64-bit mode:
![20230623_073305](https://github.com/memtest86plus/memtest86plus/assets/10545550/9ad7ed26-8bd8-40c5-b038-e0648d6af5c8)
No bug with 4+4 GiB sticks:
![20230623_224246](https://github.com/memtest86plus/memtest86plus/assets/10545550/78944b70-99aa-413c-871c-1ab595df4f58)

**Comment by debrouxl** [comment]
Thanks for the report.
Do the spurious symbols change from one run to another ?

**Comment by 3pt142** [comment]
I tried 10 times not changing the memory.
"8:37" and "9:00" got caught twice:
9:00
8:37
9:07
0:16
8:37
3:31
9:58
3:00
2:48
9:00
