### ISSUE TITLE
Authenticode signing

### ISSUE THREAD

**Issue by UniqueUserName333** [memtest86plus/memtest86plus#322]
Hi,

Posting a hash of the executable is not effective if your site is hacked and both the executable and hash are replaced.

Please sign your executables.

Thank you,

Fan of MemTest86+

**Comment by x86fr** [comment]
EV Code Certificate requires to be linked to an established company, which Memtest86+ isn't.

If EV Signing becomes strictly mandatory in the future for Windows, I may ask the (big) company I'm working for if they're willing to help our FOSS project. I have access to their EV Certificate but won't do it without approval. 

Anyway, if you're paranoid about security, you can easily compile the NSIS script yourself (with https://nsis.sourceforge.io/Download).

**Comment by UniqueUserName333** [comment]
Hi Sam,

Thanks for responding. I know signing code is more painful than not, but several publicly available, wonderful tools have been compromised in the past. Recovering from an incident like that is painful.

I understand about the company requirement  for MS Authenticode or EV code signing, but a plain code signing certificate accomplishes the basic requirement of ensuring your code has not been tampered with - just not the Smart Screen. It is better than nothing.

Comodo: $313 for one year, or $219 per year for three years.
https://comodosslstore.com/codesigning.aspx

[from Comodo's site] Unfortunately, unlike SSL/TLS, there is no free variant of a code signing certificate. Owing to the amount of trust given to a digital signature made by a trusted signing certificate, the certificate authorities (CAs) need to spend time vetting your organization (_or the individual developer_) before they’re willing (or allowed) to issue a code signing certificate.

I love your tool (have used Memtest86+ over the years to troubleshoot). I appreciate your efforts to keep it going. When you're able to accept donations again, shoot me an email. I'm happy to support.

Best Regards,

Neil


----- Original message -----
