### ISSUE TITLE
Memtest86+ v6.20 displays v6.10 on screen

### ISSUE THREAD

**Issue by Trikenstein** [memtest86plus/memtest86plus#326]
- Downloaded Linux ISO 64 bits: [mt86plus_6.20_64.iso.zip](https://www.memtest.org/download/v6.20/mt86plus_6.20_64.iso.zip)
- Checked SHA512 matched

```
shasum -a 512 ./mt86plus_6.20_64.iso.zip

87494a3225f12db5c9bb4429368cd5a63fbcad15ea8e2a34c92fa930fb64dfc7d558def07133edcbffa80bd8eb101d4f91233c09fffb614c5c261c42bf67a466  ./mt86plus_6.20_64.iso.zip
```

- Copy ISO to USB, booted successfully, memtest86+ started, tests running OK. But the display shows v6.10 (instead of v6.20)

![memtest86Plus_6-20_displayed_as_6-10](https://github.com/memtest86plus/memtest86plus/assets/72353094/7f4306e4-8c62-49c6-8810-896c3a62f199)

**Comment by martinwhitaker** [comment]
Downloaded from the link you gave and got the same SHA512 checksum. Unzipped and booted in a VirtualBox VM. This was the result:
![memtest-6 20-screenshot](https://github.com/memtest86plus/memtest86plus/assets/4000916/fdc2c8ba-9591-4a00-9c24-948af78494cd)
So I don't know how you got a different version on your USB stick.

**Comment by Trikenstein** [comment]
Hi, 

It was a mistake from my part. A bug in Ventoy USB which somehow still displays deleted ISO in its menu list. After cleaning up the deleted files in the `.Trash-1000` dir in the Ventoy USB. Recopied the MemTestPlus 6.20 ISO again and now Memtest v6.20 shows up correctly.
