### ISSUE TITLE
effective used RAM system memory clock speed +timings shown wrong

### ISSUE THREAD

**Issue by igpit** [memtest86plus/memtest86plus#327]
Although used module vendor name and model is correctly shown, on the left the effective used speed is shown wrong. e.g. when in BIOS set to DDR4-2133 (1066 MHz), it still shows in the UI as 1600MHz. verified effective settings with BIOS/hwinfo. 

expected: show effective system memory clock speed as product of set ratio and base clock + correct timings, compare hwinfo output

Running on 16000MHz
![image](https://github.com/memtest86plus/memtest86plus/assets/31316031/366fa9e4-7394-4d38-a81f-4e534056c6ed)
![image](https://github.com/memtest86plus/memtest86plus/assets/31316031/b33e17ed-ab8f-4651-bf69-0756279b640e)

Running on 1066MHz
![image](https://github.com/memtest86plus/memtest86plus/assets/31316031/be704707-1776-4dca-ae12-f89f3e028372)
![image](https://github.com/memtest86plus/memtest86plus/assets/31316031/7abfbbe6-81d1-4fae-b7f8-0860c0a6ff65)

**Comment by debrouxl** [comment]
I guess you're using the 6.20 release version.
The Core i5-9600K is a desktop part, and the development version contains support for reading from the IMC of most desktop Core i* and Zen 1-4 processors. Could you try a nightly build from https://www.memtest.org/dev and report back ? Thanks in advance :)

**Comment by igpit** [comment]
yes, its fixed in the dev version. wasn't expecting that change just in the last weeks since last release o.O
great job with the tool!

**Comment by debrouxl** [comment]
Good, thanks for the confirmation. Sam had tested the code anyway.
As for cache and memory bandwidth benchmarks, you might have noticed that memtest86+ usually reports lower figures than most other tools, because memtest86+ does not (yet) use SIMD.
I'll close the issue, unless you want to add something ?
