### ISSUE TITLE
Incorrect BadRAM address being generated

### ISSUE THREAD

**Issue by Modoh** [memtest86plus/memtest86plus#328]
The address of a memory error isn't matching between the BadRAM report mode and the standard address reporting mode. 

![54556ce1-b79c-45e6-8682-bb7e440e5494](https://github.com/memtest86plus/memtest86plus/assets/88527532/40629e02-c0f2-4adf-9945-9865aac13cd2)
![20230719_052030](https://github.com/memtest86plus/memtest86plus/assets/88527532/2321979f-c96e-414e-8c2a-e99624b78dc2)

Notice the address reported between the two address modes is different.   The BadRAM address is missing the leading 3.

**Comment by debrouxl** [comment]
That's #308 , fixed by #313 , which I recently merged to the main branch. Please try using the nightly build from https://www.memtest.org/dev :)

**Comment by chiajung91** [comment]
![MB_1000709011(Prov10 2)](https://github.com/memtest86plus/memtest86plus/assets/144084387/67d8b874-ab84-4284-8fb9-69bd726e01c1)
![MB_1000709011(Plusv6 20)](https://github.com/memtest86plus/memtest86plus/assets/144084387/d9025ff7-fb53-4572-a4da-7f95c95cc11a)
I use MemoryTest86+ will have block move error, but MemoryTest86Pro not. Do you have any idea why this happened?

**Comment by martinwhitaker** [comment]
No response from @Modoh , so assuming this was fixed by #313.
