### ISSUE TITLE
Version identified as 6.10 failed to remove giant "FAIL" banner when pressing any tried keys.

### ISSUE THREAD

**Issue by ghchris2021** [memtest86plus/memtest86plus#329]
Version identified as 6.10 failed to remove giant "FAIL" banner when pressing any tried keys.

Numerous key entries were tried to get the banner out of the way but none were successful.
Even using "F1...F10" to force the screen to redraw after presenting the configuration menu (and going back to the test log screen) did not help -- the "FAIL" banner would redraw a little bit in geometry presenting a view of some obscured address hexdigits but never would the "FAIL" banner go away while the same test & report configuration was active.  e.g. space, tab, F1, F10, CTRL, ALT, alphabetic, probably many other keys tried.

I see from the documentation that if run from a CLI there's a way to force this banner off but there was no apparent way within the TUI even using the F1 configuration menu to just turn OFF this banner.  IMHO having a giant banner that obscures 100% of the actually critical statistics (bad RAM patterns or indivudually listed errors or whatever) by default is not a reasonable design decision especially if there may be some (corner case?!) or other bugs that make it impossible to get the obscuring banner out of the way of the configured diagnostic error report statistics / metrics.

I think I must have been running "Test 5" (without other enabled tests) and had it configured to show individual errors in single CPU only non-parallel non-rotating mode on 128GBy RAM over 4 DIMMS.  

I had started a new test session (after reboot or something) on pass 0 of test-5-only showing only individual errors and 3% / 0:22:20:14 into pass 0 it displayed the FAIL banner (Errors: 1) which simply wouldn't go away despite my key inputs.

Subsequently it looks like I reset the PC for another Test 5 loop and eventually got two errors displayed in "log indivudual errors" mode and didn't end up with a FAIL banner obscuring the metrics somehow so I'm not sure what I might have done any differently in that case other than IIRC quickly going into configuration mode and reconfiguring the selected test, error display mode, CPU execution properties very soon after the memtest program was launched from the boot media (a LINUX CD / install which had it).

So I guess it may be a corner case or intermittent error but it wasn't locked up or otherwise acting strangely when it happened, it just detected my keys and neglected to clear the banner.

I suggest a TUI option to disable  the banner or maybe alternating 5 seconds off, 1-second on banner or something if it must default to ON so one has a chance to see the metrics if and when this happens.

**Comment by martinwhitaker** [comment]
The option to disable it is a boot command line option, so the workaround is to use the GRUB ISO and add "nobanner" to the boot command line.

There was a bug with the banner not being removed when there was only one error. I think that was fixed in v6.20.

Personally I agree that it would be better to default to no banner, but I use memtest86+ for testing my personal computers. People doing batch testing of new builds may disagree. You can't please everybody...
