### ISSUE TITLE
Grub default boot changed to memtest

### ISSUE THREAD

**Issue by 0-ALM-0** [memtest86plus/memtest86plus#337]
I picked the version ' Linux ISO w/ GRUB (64 bits)' and after successfully running it I can only boot from three memtest86 options. I cannot boot normally anymore (debian 11)  How can I revert this? What happened to my OS?

**Comment by debrouxl** [comment]
By itself, memtest86+ does not interfere with your computer's persistent boot configuration, as it does not have the concepts of storage driver, filesystem driver, EFI variables driver, BIOS configuration driver, etc.

Did you unplug the storage media on which you wrote the ISO, and which you used to successfully boot memtest86+ ?

**Comment by gordboy** [comment]
Some people should never be let near computers ... what they actually need is therapy for their propensity to file issues that are the result of their own ignorance and stupidity, rather than actual bugs that need fixing.

**Comment by debrouxl** [comment]
That's a rude comment, gordboy.

**Comment by 0-ALM-0** [comment]
Hi debrouxl, thank you very much for your reply. Yes, I did unplug the USB. When restarting the laptop (even though there's no USB stick in it) I'm given three options to boot and all of them of memtest only. I also tried to check the partitions, whether I could change something here, but I couldn't interpret the text that I got back (no identified path to 'boot' for example, like I saw on other people's posts addressing the same issue). I have indeed very little experience with this, I'm not able to express the problem. I can send these two pictures, maybe you spot the red flag on it. Knowing what is wrong would already be super helpful. Thanks Xx

![20230902_151747](https://github.com/memtest86plus/memtest86plus/assets/131782465/f892d123-38b4-4cb3-97fc-992b068b945b)

![20230902_174237](https://github.com/memtest86plus/memtest86plus/assets/131782465/f9402058-d530-433d-9510-af0e5cf0b360)

**Comment by debrouxl** [comment]
That still looks very much like a memtest86+ boot medium, so... how did you write the ISO to the USB mass storage device ? Using `dd` ?

**Comment by 0-ALM-0** [comment]
Yes, using dd (https://mattkomarnicki.com/articles/bootable-usb-flash-drive-with-debian). After I did it I restarted the pc and when I did so the memtest86 started immediately. I took the USB out while the test was still running, which didn't interfere with the process. Since then I only have those options to booth. I picked the memtest image that includes grub (I don't know why I did it) instead of the regular one. Could that be the problem?

**Comment by 0-ALM-0** [comment]
(thanks a lot for looking this up...)

**Comment by 01e3** [comment]
Do you happen to remember the exact command you ran? Asking as it seems to me that you wrote the image into your hard drive (sda?) instead of the usb pendrive which means the starting portion of your drive (~20MB assuming you used mt86plus_6.20_64.grub.iso) has been overwritten.

Now.. do you happen remember your partition / fs layout? Was this MBR or GPT? How many partitions / filesystem did you have. GPT has a backup partition stored at the final LBA so it would be easier to recover. If your system / data lives of filesystems beyond 20MB something should survive.

**Comment by 0-ALM-0** [comment]
Hi 01e3, thanks. 
I have two hard drives (original HDD and new SSD) and no partitions in it. The laptop was booting from the ssd (1TB).

Sda sounds too familiar and I'm afraid I really screw it up like that. I cannot check the USB anymore because I formatted it on another computer, thinking of using it to install Ubuntu.

If this really happened, can I just start from scratch (I have a backup of the files)? I tried to boot (BIOS) from a USB with Debian (a USB that I got from a vendor) and I just got the screen back with the three memtest-booting options.

**Comment by debrouxl** [comment]
You could indeed start from scratch, but most of the data on your disk is undamaged, unless for instance, the ~10 MB which were overwritten by `dd` contain a LUKS volume header.

Make sure that in your boot sequence, your USB devices are enabled and have higher priority than your internal mass storage devices, and/or use a one-time boot menu. The key combo and method to access the boot menu and BIOS configuration vary greatly across computer models and vendors.

**Comment by 0-ALM-0** [comment]
Hi debrouxl, thank you very much for your message, it gave me some hope. My system was booting from one hard drive, but all my files and Linux were on another. The memtest86 image got stored in this last one (I really messed up with the 'dd' command). The partition that allowed the boot was gone. It's all solved now and due to the two hard drives I could reinstall from scratch without loosing my files.
