### ISSUE TITLE
False errors on some Pomme computers and workaround

### ISSUE THREAD

**Issue by philectro** [memtest86plus/memtest86plus#340]
Hi Sir CanardPC hardware and others people, i have found a weird behaviour on my old macbook pro mid 2012 (9.2 IIRC).
It shows errors quickly after starting a mem test.
I made some search online and i have found this https://beetstech.com/blog/memtest86-bug-discovery-and-workaround
I adjusted the lower range to 4KB and let it run for few minutes (because the fan don't spin up under memtest86+ and the cpu is getting hot!) and no errors anymore.

**Comment by x86fr** [comment]
That's not our software but the commercial clone without the '+'. Maybe you can ask them directly.

**Comment by debrouxl** [comment]
Maybe philectro meant that memtest86+ behaves the same way as '2018 versions of PassMark's commercial, proprietary software, on Apple's buggy firmware ?

**Comment by martinwhitaker** [comment]
It would seem Apple's EFI BIOS doesn't flag the memory below 4KB as reserved.

**Comment by philectro** [comment]
Yes, i have a service running under my debian to manage it. I tuned it a bit.
