### ISSUE TITLE
To the experts

### ISSUE THREAD

**Issue by ralfulrich** [memtest86plus/memtest86plus#350]
This is not a bug, but I would be super happy to hear from you. 

I can run memtest86+ for hours without any ram-errors. Many passes done. 

Please think about what could cause the following crash, while running memtest86+ after a long time: 

"Unexpected interrupt on CPU1
Type: Invalid Op
IP: 10b974
CS: 10
Flag: 10002
Code: 0
DS: 18
ES: 18
SS: 18
rax: 75c08445
rbx: 0
rcx: 1
rdx: 0
rdi: 4b
rsi: 1151ce
rbp: 116019
rsp: 12b220" 

To me this look very much like a clear problem of the CPU. Btw. the PSU is new, so no PSU problems. The cooling is excellent, reported temperature is <50deg. I also touched everything and nothing is really warm. 

Thanks a lot!

**Comment by x86fr** [comment]
We need a screenshot to check where the invalid op occurred in the opcode flow, but usually, these crash are linked to a stability issue on the motherboard or CPU.

**Comment by debrouxl** [comment]
Additionally, a screenshot would give some information about both the hardware (processor model, sometimes system identification if the BIOS exposes proper DMI data) and the exact memtest86+ version :)

On some processors, a reported temperature of 50°C means overheating. The K8 & K10 processors affected by this limitation are 64-bit capable, though.

**Comment by x86fr** [comment]
More details needed
