### ISSUE TITLE
Website: 3.iii => 3.3

### ISSUE THREAD

**Issue by prosaole** [memtest86plus/memtest86plus#352]
https://memtest.org/readme#memory-testing-philosophy renders like this in Brave and Firefox:

<img width="242" alt="image" src="https://github.com/memtest86plus/memtest86plus/assets/57133213/f34505b2-ff18-4bab-8cec-293e55efad29">

The 2.i, 2.iii, 3.i and 3.iii should probably be changed to pure numbers.

**Comment by martinwhitaker** [comment]
Well, I changed it, but on checking in Firefox 115, I find that the nested lists are being numbered with roman numerals, so it still isn't right for everyone.

**Comment by jonathan-teh** [comment]
FWIW, I do get regular Arabic numerals, even for nested lists, on Firefox 115.4 ESR and 119 on Linux.
