### ISSUE TITLE
GDB TUI shows "[ No Source Available ]" when running ./debug_memtest.sh for debugging

### ISSUE THREAD

**Issue by GianMeng** [memtest86plus/memtest86plus#363]
Hi, after I run ./debug_memtest.sh for debugging with GDB & qemu. I got a problem when view the source code of the program, as shown below:
<img width="638" alt="1703469739744" src="https://github.com/memtest86plus/memtest86plus/assets/33340241/bd52a2c7-8ca1-4f21-84be-483bf06f0ca7">
I have seen the GDB output "add symbol table from file "memtest.debug" at". However, it seems doesn't work. I am not familiar with GDB & qemu. Could anybody tell me how to view the source code in this kind of situation? Thx.

**Comment by debrouxl** [comment]
Did you use `make clean` before `debug_memtest.sh` ? Building non-debug objects before using `debug_memtest.sh` is the most common way, in my experience, not to have usable debugging information in the GDB TUI. One needs to clean up when switching between debug and non-debug builds.

**Comment by GianMeng** [comment]
This fix the problem. Thx a lot :).

**Comment by debrouxl** [comment]
You're welcome :)
