### ISSUE TITLE
Defective RAM passed test on another machine

### ISSUE THREAD

**Issue by segfault-bilibili** [memtest86plus/memtest86plus#368]
I now have two laptops at hand. One is GE60-16GC with i7-4810MQ quad-core processor, and another is Dell E6430 with i3-3110M dual-core processor. Both use SO-DIMM DDR3L memory.

Several days ago I found that, a 8GB memory module is defective, because it has one-bit error on certain address (with a probability of about 1/6, one error per 6 passes/cycles). I discovered this fact on the Haswell i7 machine. When this memory module is replaced with another one, that address no longer has error.

However, after  I unplugged this defective memory module and then plugged it into the i3-3110M laptop, the i3 laptop cannot detect the error. I have left it to run overnight. I also tried to narrow down the test range, however it still cannot discover the error.

**Comment by 01e3** [comment]
Is the memory running with the same speed and voltage on both laptops? Could you check with CPU-Z?

**Comment by segfault-bilibili** [comment]
Both should be running at 800MHz (DDR3-1600). Either memtest86+ or the memory tab CPU-Z shows that.

I can't be sure about voltage. The SPD tab of CPU-Z shows 1.35V, but I don't know whether it's actually running at that voltage.

**Comment by segfault-bilibili** [comment]
By the way I have another question: does cache affect the results?

If I recalled correctly, when I narrowed down the test range to something like 1MB, which is less than L3 cache, it didn't report error as expected.

I'll redo that test if I have time.

**Comment by segfault-bilibili** [comment]
I replaced i3-3110M with quad core i7-4740QM. Now it can detect the error with a probability of around 2%.
