### ISSUE TITLE
dmidecode information in table

### ISSUE THREAD

**Issue by ole-tange** [memtest86plus/memtest86plus#373]
I am upgrading old laptops and test the memory using memtest86+

I am often in the situation, that I have a single small module that works, but I want to upgrade it to another. And not all modules are compatible. Some modules are completely refused. Others cause some computers to crash when reaching a certain address. These are all perfectly good modules if tested in other machines.

It would be really nice if I could have `dmidecode` info shown in a table (such as rank), so I can compare the different modules before starting the test.

**Comment by debrouxl** [comment]
Unfortunately, even for a number of recent computers, the SMBIOS / DMI information is often at best incomplete, if not wrong in an obvious way (say, 4 type 17 struct instances on a motherbord with 2 physical RAM slots...). I've posted at the bottom of this message two examples of incompleteness found in the first few dmidecode dumps from my collection I browsed; the processor model from the first computer first hit the market in 2005, the processor model from the second one became available in 2016.

In fact, displaying a subset of SMBIOS / DMI information was left as future improvement in #1 (contains implementation notes) :)
On the one hand, doing a decent job decoding and displaying the whole subset of memory-relevant struct types I've listed there would bloat the memtest86+ code base significantly, for a feature which is only tangentially related to the core feature of a memory testing program, and can only output whatever often unreliable information is exposed by the BIOS.
On the other hand, decoding a very narrow subset (say, struct types 6 and 17) would be more palatable, and might even be enough for your use case if your computers' respective BIOS implementations provide accurate information... but then that wouldn't be doing a decent job displaying DMI information in general.

The way to obtain reliable information about memory - parsing SPD data read from most RDRAM, SDR SDRAM, or newer DDR* SDRAM sticks - is known, but it's also a whole lot of complexity in general. By now, memtest86+ implements pretty good coverage for common SMBus controllers in desktops and laptops. There are still coverage holes for old computers whose SMBus controllers are neither PIIX4, nor i801, or for Xeon-equipped workstations and servers, and/or on computers which have more than 8 memory slots. decode-dimms on Linux doesn't do better.
I recently posted an overview of the SMBIOS / DMI / SPD information gathering and printing limitations, at https://www.phoronix.com/forums/node/1434483 .

```
Handle 0x0012, DMI type 17, 27 bytes
Memory Device
        Array Handle: 0x0011
        Error Information Handle: No Error
        Total Width: 128 bits
        Data Width: 64 bits
        Size: 1 GB
        Form Factor: DIMM
        Set: 1
        Locator: S0
        Bank Locator: Bank 0
        Type: DRAM
        Type Detail: Synchronous
        Speed: Unknown
        Manufacturer: Not Specified
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
```

```
Handle 0x000C, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x000A
        Error Information Handle: Not Provided
        Total Width: 72 bits
        Data Width: 64 bits
        Size: 16 GB
        Form Factor: DIMM
        Set: None
        Locator: PROC 1 DIMM 1
        Bank Locator: Not Specified
        Type: DDR4
        Type Detail: Synchronous Registered (Buffered)
        Speed: 2400 MT/s
        Manufacturer: HP     
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: 809081-081
        Rank: 2
        Configured Memory Speed: 2400 MT/s
        Minimum Voltage: 1.2 V
        Maximum Voltage: 1.2 V
        Configured Voltage: 1.2 V
```
