### ISSUE TITLE
Where is info on 'bit mode' (e.g. 64 bit, 128 bit, 192 bit, etc) [version 7.00]

### ISSUE THREAD

**Issue by spamrefuse** [memtest86plus/memtest86plus#382]
Hi,

I'm using memtest86+ version 7.00. The output screen does not have information on the bit-mode of data transfer.

In older versions there used to be a line like with CAS with some number sequence, followed by, for example, "@ bit 64 mode".

The mode information helps determining whether the ram operates in single, dual, triple channel mode (64, 128, 192).

Version 7.00 does not have this anymore; or am I missing something?

Thank you.
-S.R.

**Comment by debrouxl** [comment]
Hi,

You're right, at the time of this writing, versions 6.00 and later do not expose this information - yet, that is. See #348 for the rationale, as well as, down the comments, a patch you can apply if you really need this piece of information to be displayed on the supported IMC models, currently desktop Core i* and desktop Zen * :)

**Comment by spamrefuse** [comment]
Thanks for the explanation.

Instead of patching the current version, I can use the 5.31-beta version, the last one before 6.00 (with Ventoy on a USB stick I can run 7.00 and 5.31 easily without too much hassle).

Or is it a bad idea using 5.31 for the bit mode of the ram?
-S.R.

**Comment by debrouxl** [comment]
In general, I wouldn't recommend using the older code base, which wasn't as clean as the pcmemtest-derived code base of versions 6.00 and later :)

**Comment by x86fr** [comment]
duplicate #348
