### ISSUE TITLE
badram range too narrow

### ISSUE THREAD

**Issue by tormodvolden** [memtest86plus/memtest86plus#384]
I am running 7.00 and also tried the nightly build 2024-03-04 so I don't think it is the same issue as #328.

There are RAM errors that are quite reproducible, and failing addresses are:
```
00027ca9f010 (9.94GB) test 7
(10 other in between)
00027ca9f510 (9.94GB) test 7
000274a9eed0 (9.82GB) test 8
```

However, the badram pattern is only:
`badram=0x0000000274a9eed0,0xfffffffffffffff8`
and remains the same even if I let it run a complete new pass after switching to badram pattern mode. I can see the error count counting though.

In "individual error" mode I also see the error counting but no new errors displayed (I suppose `<Space> Scroll lock` means that the scroll is currently unlocked, but I tried both anyway). I don't know if this is related. Even with only the errors listed above, I would expect a broader badram pattern.

On another day I was also using the "summary" mode:
```
lowest  00026fa9ef50 (9.74GB)
highest 000274aa0290 (9.82GB)
bits in error mask 0000008000000000
bits in error - total 1 min 1 max 1 avg 1

badram patterns:
badram=0x0000000274a9eed0,0xfffffffffffffff8
```

This is a failing 8GB Kingston 99U5428-018.A00LF (2019-W02) tested on top of on-board 2GB. i7-3517U CPU @ 1.90 GHz.

**Comment by martinwhitaker** [comment]
Errors detected in the block move test (test 7) are not included in the badram pattern. See the README for an explanation.

**Comment by tormodvolden** [comment]
Ah, thanks. I see now it is mentioned in the detailed explanation of tests 0 and 7. Maybe it could be mentioned in the "BadRAM Patterns" section that not all tests are included.

What about the (lack of) scrolling in "individual error" mode? Or is the same address only listed once, but counted on repeats?

**Comment by martinwhitaker** [comment]
I don't have any faulty RAM modules so can only test the error reporting by artificially injecting failures. Scrolling is behaving as expected when I do that - each pass causes a new set of errors to be reported and scrolls the display.

**Comment by tormodvolden** [comment]
Thanks for the documentation improvement!

I will rerun the scan with those tests disabled and see how it goes.

**Comment by tormodvolden** [comment]
When I run with test 7 (and 0) disabled, there is only one address appearing, so the narrow badram range was correct. And since we have in error.c:
```
        // Skip duplicates.
        if (!new_header && addr == error_info.last_addr && xor == error_info.last_xor) {
            break;
        }
```
there is no more reporting even if the test or pass changes. So that's why I see the error count ticking but no new errors reported. It is not clear to me if this is the ideal behavior or if the failing address should be reported again on a new test or pass.

Finally, when I include test 7, there are 12 errors coming almost at the same time, which is exactly the number of lines in the scrolling window. So only the "pass" number changes on the screen, which I didn't notice when I tested this earlier.
