### ISSUE TITLE
monitor turned OFF during Memtest (perhaps) prevents Memtest from being displayed again?

### ISSUE THREAD

**Issue by karel201712** [memtest86plus/memtest86plus#386]
Hi,
my reproducible issue:
Memtest86+ 7.00 started from a boot DVD
when I turn OFF the monitor (while Memtest is running) and after some time (did not try variable times) turn it back ON, the monitor will not come back to the Memtest screen, it only briefly displays a message saying there is no DP signal from the PC. At this point no keypress or mouse move/press will bring the Memtest on my screen again. If I remember correctly, ESC press will restart the PC.
Is it possible Memtest is somehow affected by the monitor being turned OFF (can't imagine how) or is it perhaps a matter of the DP signal not being restarted for some reason or something completely different, pls?
Many thanks for Memtest and for your kind help!
Best :)
Karel

**Comment by martinwhitaker** [comment]
Apart from writing to the frame buffer, Memtest86+ does not interact with the video hardware. This behaviour must be a function of the hardware or BIOS. I've tried turning the monitor off and on on my machine (only with a short delay) and don't see this.

If pressing ESC restarts the PC, that does indicate Memtest86+ is still running.

**Comment by karel201712** [comment]
@martinwhitaker 
thank you very much for your kind reply!
i have tested it on another pc and it works as expected. must be something set on my pc just as you have stated.
many thanks for your kind help!!!
best regards,
karel
