### ISSUE TITLE
About the address out of bounds

### ISSUE THREAD

**Issue by kilaterlee** [memtest86plus/memtest86plus#392]
Hi,
In the system/pmem.c function sort_pm_map, there may be a hidden danger of address out-of-bounds:
```
static void sort_pm_map(void)
{
    // Do an insertion sort on the pm_map. On an already sorted list this should be a O(n) algorithm.
    for (int i = 0; i < pm_map_size; i++) {
        // Find where to insert the current element.
        int j = i - 1;
        while (j >= 0) {
            if (pm_map[i].start > pm_map[j].start) {
                j++;
                break;
            }
            j--;
        }
        // Insert the current element.
        if (i != j) {
            pm_map_t temp;
            temp = pm_map[i];
            memmove(&pm_map[j], &pm_map[j+1], (i - j) * sizeof(temp));
            pm_map[j] = temp;
        }
    }
}
```
In the first time loop, i == 0, j == -1, and in the insert process, &pm_map[j] must be out of bonds I guess.

**Comment by kilaterlee** [comment]
> Yes, you're right. I missed that when cleaning up the original (v5) code. What is more, it looks like the source and destination arguments to memmove are swapped

Yes, it may overwrite the pm_map_size, because the pm_map_size is in front of the pm_map.

**Comment by 7rick03ligh7** [comment]
Are you talking about this kind of problem?
![image](https://github.com/memtest86plus/memtest86plus/assets/15386257/8a6459de-4cbb-4e25-8406-e738a27f3c57)

**Comment by martinwhitaker** [comment]
@7rick03ligh7 , no, that's quite normal. See #193.

**Comment by martinwhitaker** [comment]
I've pushed a fix to the main branch. I've tested the revised sort_pm_map() function in isolation on a 4 element array containing all combinations of the values 1,2,3,4 and all combinations of the values 1,2,2,4, with added assertions to check the array indices are always in bounds.
