### ISSUE TITLE
Unable to check the binary files archive with the checksum file

### ISSUE THREAD

**Issue by belsunce** [memtest86plus/memtest86plus#394]
Binary Files (.bin/.efi) For PXE and chainloading
https://www.memtest.org/download/v7.00/**mt86plus_7.00.binaries.zip**

https://www.memtest.org/download/v7.00/sha256sum.txt
19894151788a99c25c42644696527aba18cb210b2f9bca4a60e73586a6d78286  **mt86plus_7.00_binaries.zip**

- file names are different from download url and checksum file
=> checksum fails: "Unable to find a checksum for file 'mt86plus_7.00.binaries.zip' in 'https://www.memtest.org/download/v7.00/sha256sum.txt'

**Comment by x86fr** [comment]
Fixed. Thanks for the report.
