### ISSUE TITLE
Adding sounds (BEEPs)

### ISSUE THREAD

**Issue by demiurg-spb** [memtest86plus/memtest86plus#398]
I would really like it if, after a given number of cycles, the program would signal with a sound signal the end of the test. Perhaps it would not be bad and when an error was detected, a sound signal would also sound. The OK signal and the Error signal must be different...

**Comment by debrouxl** [comment]
Unfortunately, this is harder than many people think.
That is already tracked by #172 , so I'll close this issue as duplicate :)

**Comment by demiurg-spb** [comment]
II just proposed a solution to this problem: pull request https://github.com/memtest86plus/memtest86plus/pull/404 ( [Issue https://github.com/memtest86plus/memtest86plus/issues/172] add beep sound)
