### ISSUE TITLE
PIT Counter broken on Framework Laptop

### ISSUE THREAD

**Issue by chirs241097** [memtest86plus/memtest86plus#40]
On Gentoo, the `iso` target fails because `sys-fs/dosfstools` does not provide `/sbin/mkdosfs`. Instead it uses `/usr/sbin/mkfs.fat`. Simply changing the path to the correct executable would fix it, and produces an image that seems to work on a ThinkPad X60 Tablet (legacy BIOS) and ThinkPad X1 yoga 1st gen (UEFI w/o CSM).

However the said image does not work on a Framework Laptop. After loaded it just gets stuck in a blank screen. I've also tried booting with `smp` or `nosm` (as well as both), none of which has any effect on the result. The machine has an i7-1185G7 processor and 64 GB of DDR4 RAM (in 2*32 GB configuration). I'm not familiar with the process memtest86+ should be debugged, but if provided with instructions I would happily report the results.

**Comment by x86fr** [comment]
Can you try the 32bit build, directly started from the UEFI shell. 

Also a copy of `memmap` and `acpiview` from the UEFI shell can help.

**Comment by martinwhitaker** [comment]
The 32-bit build only supports 32-bit UEFI systems, and I'll be surprised if the Framework laptop is that.

Please try changing the line `#define DEBUG 0` near the top of `boot/efisetup.c` to `#define DEBUG 1`. Does that cause any diagnostic messages to be displayed?

**Comment by martinwhitaker** [comment]
OK, that shows the Framework laptop hasn't provided a usable address for the graphics frame buffer. Unless I've misinterpreted the UEFI spec., that's a firmware bug. Without a usable frame buffer, Memtest86+ can't display anything.

**Comment by chirs241097** [comment]
Thanks. I'll report this to the Framework team.

**Comment by martinwhitaker** [comment]
Could you retest with this patch, just to make sure it isn't a 64-bit address aligned on a 4GB boundary:
````
--- a/boot/efisetup.c
+++ b/boot/efisetup.c
@@ -366,7 +366,7 @@ static efi_status_t set_screen_info_from_gop(screen_info_t *si, efi_handle_t *ha
 
 #if DEBUG
     print_string("FB base   : ");
-    print_hex(si->lfb_base);
+    print_hex((uintptr_t)lfb_base);
     print_string("\n");
     print_string("FB size   : ");
     print_dec(si->lfb_width);
````

**Comment by chirs241097** [comment]
After applying the patch, the message printed at boot changed to:
```
BGR32 mode
FB base   : 4000000000
FB size   : 2256 x 1504
FB format : R8 G8 B8 A8
FB stride : 9024
Press any key to continue...
```

Everything else was the unchanged.

**Comment by martinwhitaker** [comment]
Thanks. In that case it's a bug in our code, not the firmware.

**Comment by martinwhitaker** [comment]
I've reconfigured my PC to map the frame buffer above 4GB, and it still works, so that's not the problem.

**Comment by chirs241097** [comment]
Is there a way I can help to further identify the issue? Just FYI, the latest commit ([9f92ecf](https://github.com/memtest86plus/memtest86plus/commit/9f92ecf761a190c162a7f55e1525e4e070a6605b)) did not fix the problem.

**Comment by martinwhitaker** [comment]
Please test my latest commits to the main branch, again changing the line `#define DEBUG 0` in `boot/efisetup.c` to `#define DEBUG 1`. The information displayed should have changed. After you press any key to continue, it should then display a black screen at the selected resolution with red bars top and bottom and pause until you press any key again, after which it will continue on with the normal startup. I'm not expecting this to fix the problem (although it might); it's more to get the extra information, and test if we can access the framebuffer.

**Comment by chirs241097** [comment]
The debug output is now:

```
Found GOP with 8 modes
This GOP implements the ConOut protocol
BGR32 mode
FB base   : 4000000000
FB size   : 640 x 480
FB format : R8 G8 B8 A8
FB stride : 2560
Press any key to continue...
```

The red bars are displayed correctly. After that it again goes into a blank screen.

**Comment by martinwhitaker** [comment]
Please try making this change:
````
--- a/system/screen.c
+++ b/system/screen.c
@@ -211,7 +211,7 @@ void screen_init(void)
         uint32_t *line = (uint32_t *)lfb_base;
         for (int y = 0; y < lfb_height; y++) {
             for (int x = 0; x < (lfb_width / pixels_per_word); x++) {
-                line[x] = 0;
+                line[x] = 0xffffff;
             }
             line += lfb_stride / sizeof(uint32_t);
         }
````
Does that make the screen go white instead of blank?

**Comment by chirs241097** [comment]
Yes. The screen is now white after the second test screen with red bars.

**Comment by chirs241097** [comment]
Ah, yes. The good old "print("here")" debugger...

Jokes aside, with your help I've narrowed down the search area to the `measure_cpu_speed` function in `cpuinfo.c`. The following loop
```C
    do {
        loops++;
    } while ((inb(0x61) & 0x20) == 0);
```
never exited.

I messed around in the code a little bit more, and tried the following (without any real knowledge about such low-level x86 stuff, especially what's io port 0x61 doing here, so take it for what it is)
```diff
diff --git a/system/cpuinfo.c b/system/cpuinfo.c
index 7d3a943..6ca1e4d 100644
--- a/system/cpuinfo.c
+++ b/system/cpuinfo.c
@@ -19,6 +19,7 @@
 #include "cpuid.h"
 #include "io.h"
 #include "tsc.h"
+#include "print.h"
 
 #include "boot.h"
 #include "config.h"
@@ -876,9 +877,12 @@ static void measure_cpu_speed(void)
     rdtscl(start_time);
 
     int loops = 0;
+    int t;
     do {
         loops++;
-    } while ((inb(0x61) & 0x20) == 0);
+        printi(1, 0, loops, 8, 0, 0);
+        printx(2, 0, t = inb(0x61), 8, 0, 0);
+    } while ((t & 0x20) == 0 && loops < 100000);
 
     uint32_t end_time;
     rdtscl(end_time);
@@ -886,7 +890,7 @@ static void measure_cpu_speed(void)
     uint32_t run_time = end_time - start_time;
 
     // Make sure we have a credible result
-    if (loops >= 4 && run_time >= 50000) {
+    if (loops < 100000 && loops >= 4 && run_time >= 50000) {
        clks_per_msec = run_time / 50;
     }
 }
```

The value of `t` seems to flip between 0x01 and 0x11 very quickly. After a long wait for `loops` to reach 100000, it proceeds to boot into the memtest application, which seems to function correctly (except memory speeds are not displayed of course).

**Comment by x86fr** [comment]
Can you post a screenshot?

PS : We will really have to use more modern ways for this (ie: perf counters) but you can't imagine how hard and CPU-specific it is to determine the CPU frequency on modern CPUs these days...

**Comment by x86fr** [comment]
Anyway, port 0x61 is the PIT Timer and bit 5 indicates when the counter is exhausted. It's pretty basic functions. I don't really understand how it can trigger a reset.

**Comment by martinwhitaker** [comment]
It's not triggering a reset, it's getting stuck in an infinite loop. I guess that machine doesn't have a PIT, so bit 5 never gets set.

**Comment by chirs241097** [comment]
Which screen do you want the screenshot of? Asking since there are quite a few new screen for debug purposes added here.

Just to be clear, the computer isn't resetting. The code is checking for bit 5 but only bit 4 is changing on this laptop.

**Comment by x86fr** [comment]
Just the main "running" screen (please try without nosm if you still used it).

About PIT, we will have to move to APIC Timer to avoid issue, but it's the first time I see a x86 computer without a (at least emulated) PIT.

**Comment by martinwhitaker** [comment]
Moving to the APIC timer will mean we need to parse the ACPI tables earlier in the startup sequence. We need to know the CPU frequency before we scan for USB keyboards, because the USB drivers need accurate delays.

**Comment by chirs241097** [comment]
![IMG_20220413_132627](https://user-images.githubusercontent.com/11586814/163236728-45834f98-81cc-4f58-991b-8c4f9b9307b6.jpg)
This is the application running (without using any boot options), with my changes above.

At least [according to intel](https://edc.intel.com/content/www/us/en/design/ipla/software-development-platforms/client/platforms/tiger-lake-mobile-y/intel-500-series-chipset-family-on-package-platform-controller-hub-datasheet-v/006/8254-timers/), the PIT is still present on tigerlake. I don't know whether the following information is helpful, but I do know the Framework Laptop does not have a PC Speaker (or an emulated one).

**Comment by martinwhitaker** [comment]
Reading [Volume 2 of the PCH datasheet ](https://cdrdv2.intel.com/v1/dl/getContent/636174?explicitVersion=true&wapkw=500%20series%20pch), it states that when writing to port 0x61, the upper 4 bits should be zero. We don't currently enforce this, so you could try:
````
--- a/system/cpuinfo.c
+++ b/system/cpuinfo.c
@@ -867,7 +867,7 @@ static void measure_cpu_speed(void)
     }
 
     // Set up timer
-    outb((inb(0x61) & ~0x02) | 0x01, 0x61);
+    outb((inb(0x61) & 0x0c) | 0x01, 0x61);
     outb(0xb0, 0x43);
     outb(PIT_TICKS_50mS & 0xff, 0x42);
     outb(PIT_TICKS_50mS >> 8, 0x42);
````
in case it makes a difference.

It could just be a faulty device.

**Comment by chirs241097** [comment]
The change above did not have any effect on my machine.

I played around with the counter a little bit more. I've pushed the code to [this branch](https://github.com/chirs241097/memtest86plus/tree/tgl_pit_test). This code still gets the correct CPU clock on the ThinkPad X60.

On the Framework Laptop its behavior is very wonky. The PIT counter was decreasing, but much slower than what it is supposed to. The counter took around 8 seconds to reach 0 (before `loops` reaches 100000), after which the PIT fired and bit 5 of ioport 0x61 readout changed to 1. But this obviously resulted in a grossly wrong clock measurement.

What makes everything even more strange is that if I comment out the third and fourth `printf` in the loop (and therefore do not try to read the PIT counter in the loop), the timer doesn't seem to do anything. Now the loop just sits there until `loops` hit 100000. And the final value of the counter after leaving the loop decreased only by 3 (not always precisely this number, but very small anyway) compared to its initial value.

My current guess is that PIT channel 2 is still present in this laptop, but non-functional for some reason. I think I'll reach out to other users of the same laptop to check whether this is a widespread problem.

**Comment by chirs241097** [comment]
I've just checked with another Framework user, and their machine showed the exact same symptoms. So the issue with the timer can't just be specific to my unit.

**Comment by x86fr** [comment]
Can you try with this order:

```
    outb(0xb0, 0x43);
    outb((inb(0x61) & 0x0c) | 0x01, 0x61);
    outb(PIT_TICKS_50mS & 0xff, 0x42);
```

**Comment by chirs241097** [comment]
That doesn't work either.
I also tried this order:
```C
    outb(0xb0, 0x43);
    outb((uint8_t)(PIT_TICKS & 0xff), 0x42);
    outb((uint8_t)(PIT_TICKS >> 8), 0x42);
    outb((inb(0x61) & 0x0c) | 0x01, 0x61);
```
in my fork, which didn't work.

I think I'll try the latch command next.

Btw is there a reason that PIT channel 0 is not used here (besides its output status can't be read with a simple io read)? Is it used for something else?

**Comment by x86fr** [comment]
Channel 0 generates IRQ and need an handler for IRQ0, so it's much easier to use Channel 2. 

Just trying: Can you disable Hyper-Threading, set `Active Processor Cores` to 1, and `AP threads Idle Manner` to `HLT Loop` in your BIOS and try again?

**Comment by x86fr** [comment]
Can you also try this?

```
    // Set up timer
    outb(inb(0x61) & 0xC, 0x61);
    outb(0xb0, 0x43);
    outb(inb(0x61) | 0x03, 0x61);
    outb(PIT_TICKS_50mS & 0xff, 0x42);
    outb(PIT_TICKS_50mS >> 8, 0x42);
```

**Comment by chirs241097** [comment]
No dice... The code change alone didn't work, neither did the BIOS settings change have any effect (tested with the code above).

**Comment by chirs241097** [comment]
I've tried switching to using the read back command (0b11xxxxxx to port 0x43) with both PIT channel 0 and 2. Neither gave the correct timing (still ~8 sec for 50ms). The code using the read back command worked fine on the X60 with both PIT channels.

**Comment by chirs241097** [comment]
I got in touch with someone on the Framework engineering team, and here's a quote from their response:

> I met with our lead engineer and he's stated that this shouldn't be anything related specifically to our laptop. Have you confirmed this only affects Framework Laptops or does it affect other 11th gen Intel CPUs as well?

So apparently the next step should be to test on some other laptops with 11th gen Intel CPU (especially ones with on-package PCH I presume), which I unfortunately don't have access to right now.

**Comment by x86fr** [comment]
Memtest86+ v6.00pre has been tested on numerous motherboards based on 10th/11th/12th/13th Gen Intel CPUs without issue related to the PIT timer to date. 

This said, this issue probably come from your firmware putting the PIT timer in power gating mode before passing control to the OS. This can be done, but not recommended: according to Intel, that will generate major issues with legacy OS. The correct strategy to ensure maximum compatibility is to set `8254CGE` at 0 at POST and let the OS set it to 1 at later stage.

Can you please check with the Framework team if they enabled `8254 Static Clock Gating` in their BIOS/firmware? 
If they need more information, send them this link: https://raw.githubusercontent.com/intel/FSP/master/TigerLakeFspBinPkg/Docs/TigerLake_FSP_Integration_Guide.pdf with a reference to point 15.130.2.1 (page 266). 

The only way to solve this on our side is to switch to HPET or ACPI PM Timer.

**Comment by chirs241097** [comment]
Thanks -- I've send this to the team.

**Comment by x86fr** [comment]
Do you get any reply from them?

**Comment by chirs241097** [comment]
Sorry for the recent inactivity. I got the following reply from the team:

> Per our lead engineer, the current setting for the PIT is to be clock gated by default when the system boots. This is required to support Modern Standby.
>
> Since we do not support legacy OS officially, this is the current setting in our BIOS.
>
> You may be able to turn off the clock gate before launching memtest in the EFI shell if you so wanted.
We reviewed Intel RC code and found below description :
>
> Setting 8254CGE is required to support SLP_S0.
>
> That should be necessary for OS support S0ix.

**Comment by x86fr** [comment]
Firmware issue.
