### ISSUE TITLE
Linux ISO w/ GRUB (64 bits) does not support gpt partition table

### ISSUE THREAD

**Issue by fengchen-github** [memtest86plus/memtest86plus#402]
The USB disk is a gpt partition table and a fat32 partition. 
Copy the efi folder to the partition. 
After starting, it will enter the grub command line. After executing the ls / command, it will prompt an unknown file system.
Change the partition table to mbr and it will boot normally

**Comment by martinwhitaker** [comment]
Note that the Linux ISO is a hybrid ISO designed to be copied directly to the raw USB device using the `dd` command or similar method.

**Comment by fengchen-github** [comment]
Maybe the problem is that grub here does not support gpt partition table

**Comment by martinwhitaker** [comment]
What problem? Please describe exactly what you do to create your bootable Memtest86+ USB stick.

**Comment by martinwhitaker** [comment]
My question was never answered, but commit 3f86696f00bd5054a73d3eb9246f871f26e4d477 added GPT support to the GRUB image used on the memtest86+ ISOs.
