### ISSUE TITLE
Memory SPD Information presented on screen is incorrect

### ISSUE THREAD

**Issue by FMBrownBear** [memtest86plus/memtest86plus#407]
I am building a new desktop PC and I always run your memory test as the first burn-in test.  The key parts for this PC are
Motherboard	Gigabyte Z790 AORUS Elite X AX
Intel CPU	        I5-14600KF (6 P, 8 E-cores)
Memory	        Corsair Vengeance DIMM5 6400 32GB (2 x 16GB)
The memory parameters reported on the IMC line are correct.  However the SPD information is incorrect.

I have attached a picture of the test screen for you to see.
![Picture of Memtest86+ screen with SPD Error_20240530_093758](https://github.com/memtest86plus/memtest86plus/assets/171290212/a90dd587-3693-4963-bc3b-29588f6ed75e)

**Comment by debrouxl** [comment]
Thanks for the report.
This looks like the same symptom as multiple other computers in #110 ... but this is a Gigabyte MB, instead of an ASUS MB. If the issue is spreading, that's no fun.

**Comment by chrfranke** [comment]
I observed the same issue using Memtest86+ 7.00 (part of recent grml.org live Linux) on
ASUS ROG Strix Z790-E Gaming WiFi
Intel i7-14700K
Kingston Fury KF556C36BBEK2-32 (2x16GB DDR5-5600 CL36-38-38-80 XMP, SPD reports manufacturer: Micron & SpecTek)

"IMC" is correct, "Memory SPD Information" is exactly as in the above picture.
