### ISSUE TITLE
hangs on S3420GPV because tests a forbidden range

### ISSUE THREAD

**Issue by jt-fuw** [memtest86plus/memtest86plus#409]
Hardware: mainboard S3420GPV with i3-550 and 2x 2GB UDIMM RAM modules.
The memtest86+ 7.00 (and many prevoius versions, too) hangs on address ranges
0x9f600000-0x9f700000 (2550-2551 MiB) and 0x9f700000-0x9f800000 (2551-2552 MiB).

BIOS (INT 0x15 f.E820) reports there are ACPI and reserved areas withing these ranges:
`[mem 0x0000000000000000-0x000000000009bfff] usable`
`[mem 0x000000000009c000-0x000000000009ffff] reserved`
`[mem 0x00000000000e0000-0x00000000000fffff] reserved`
`[mem 0x0000000000100000-0x000000009d7c7fff] usable`
`[mem 0x000000009d7c8000-0x000000009d89bfff] ACPI NVS`
`[mem 0x000000009d89c000-0x000000009f6a3fff] ACPI data   **`
`[mem 0x000000009f6a4000-0x000000009f6defff] reserved    **`
`[mem 0x000000009f6df000-0x000000009f789fff] ACPI data   **`
`[mem 0x000000009f78a000-0x000000009f7defff] ACPI NVS    **`
`[mem 0x000000009f7df000-0x000000009f7fffff] ACPI data   **`
`[mem 0x000000009f800000-0x00000000afffffff] reserved`
`[mem 0x00000000fed1c000-0x00000000fed1ffff] reserved`
`[mem 0x00000000ff800000-0x00000000ffffffff] reserved`
`[mem 0x0000000100000000-0x000000015bffffff] usable`
The ** mark areas in ranges that cause hang; the memtest86+ doesn't test range
0x9f800000-0x100000000 (2552-4096 MiB), and test of range 0-2550 MiB doesn't
show any problems in spite it conflicts with 2 ACPI ranges.

Seems the memtest86+ doesn't use the BIOS memory mapping information -
it should limit test to ranges shown as 'usable', at least for default setting;
it may allow testing RAM in ACPI areas, but with a warning it can cause hang.

**Comment by martinwhitaker** [comment]
memtest86+ most certainly does use the BIOS memory mapping information.
I take it this is a legacy BIOS, not UEFI.
Please enable tracing, either by adding the boot command line option `trace`, or from the F1 configuration menu before testing starts, and take a photo of the memory map information that is displayed. You may need to single step a few times and take a second photo if there are too many lines to show at once.

**Comment by jt-fuw** [comment]
Here is the screen photo: ![mt1](https://github.com/memtest86plus/memtest86plus/assets/6706545/3d0d85b3-3273-428c-8cc6-b352c5f15807)

**Comment by martinwhitaker** [comment]
I had forgotten one little wrinkle - to avoid the first few trace lines scrolling off the top of the screen, you need to disable SMP. But fortunately we can see all we need.

The "pm" traces show the physical memory map that will be used for testing. This matches pretty well with the map you report in your first comment. The only discrepancy is that your map shows the first ACPI NVS region at 0x9d7c8000-0x9d89bfff, but the corresponding hole in the memtest86+ map is at 0x9d7ac000-0x9d87ffff.  That's a different start address but the same size. Please could you retest using the nightly build, which does include a fix to the pm map calculations.

ACPI data regions are reclaimable memory regions, so memtest86+ will test those regions.

**Comment by jt-fuw** [comment]
For memtest from 2024-06-18 00:20 list of "pm"-s is: 0-9b, 100-9d740, 9d814-9f6a4, 9f6df-9f78a, 9f7df-9f800, 100000-15c000. ACPI RSDP/FADT lines are tha same, additional lines "ACPI SRAT found at 0", "start test 0". And hangs.

I started the memtest using PXELINUX - it took me some time to find it must be invoked using "LINUX memtest" - I tried "KERNEL memtest" and this was wrong.

**Comment by jt-fuw** [comment]
I wrote a program that runs under DOS and shows info from INT 0x15 0xE820 function; under FreeDOS it displays:
` 0000000000000000 000000000009B000 0000000100000001`
` 000000000009B000 0000000000005000 0000000100000002`
` 00000000000E0000 0000000000020000 0000000100000002`
` 0000000000100000 000000009B71F000 0000000100000001`
` 000000009B81F000 0000000001F00000 0000000100000002`
` 000000009D71F000 0000000000021000 0000000100000001`
` 000000009D740000 00000000000D4000 0000000100000004`
` 000000009D814000 0000000001E90000 0000000100000003`
` 000000009F6A4000 000000000003B000 0000000100000002`
` 000000009F6DF000 00000000000AB000 0000000100000003`
` 000000009F78A000 0000000000055000 0000000100000004`
` 000000009F7DF000 0000000000021000 0000000100000003`
` 000000009F800000 0000000010800000 0000000100000002`
` 00000000FED1C000 0000000000004000 0000000100000002`
` 00000000FF800000 0000000000800000 0000000100000002`
` 0000000100000000 000000005C000000 0000000100000001`
(the values listed are just 64-bit values as the function returns, 3 values per entry)

In SystemRescue (Linux) 'dmesg' lists the following:
`[    0.000000] BIOS-provided physical RAM map:`
`[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009bfff] usable`
`[    0.000000] BIOS-e820: [mem 0x000000000009c000-0x000000000009ffff] reserved`
`[    0.000000] BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved`
`[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000009d73ffff] usable`
`[    0.000000] BIOS-e820: [mem 0x000000009d740000-0x000000009d813fff] ACPI NVS`
`[    0.000000] BIOS-e820: [mem 0x000000009d814000-0x000000009f6a3fff] ACPI data`
`[    0.000000] BIOS-e820: [mem 0x000000009f6a4000-0x000000009f6defff] reserved`
`[    0.000000] BIOS-e820: [mem 0x000000009f6df000-0x000000009f789fff] ACPI data`
`[    0.000000] BIOS-e820: [mem 0x000000009f78a000-0x000000009f7defff] ACPI NVS`
`[    0.000000] BIOS-e820: [mem 0x000000009f7df000-0x000000009f7fffff] ACPI data`
`[    0.000000] BIOS-e820: [mem 0x000000009f800000-0x00000000afffffff] reserved`
`[    0.000000] BIOS-e820: [mem 0x00000000fed1c000-0x00000000fed1ffff] reserved`
`[    0.000000] BIOS-e820: [mem 0x00000000ff800000-0x00000000ffffffff] reserved`
`[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000015bffffff] usable`

The "memtest" from 2024-06-18 00:20 night build shows ranges ("pm" lines):
0-9b, 100-9d740, 9d814-9f6a4, 9f6df-9f78a, 9f7df-9f800, 100000-15c000;
these lines are followed by ACPI RSDP, ACPI FADT (both the same as on the photo),
"ACP SRAT found at 0", and "start test 0". And the test hangs.
(the "memtest" SHA1 = ca3caf5f3554cec39a8c66416017ec8fc4af6b6e)

**Comment by martinwhitaker** [comment]
So memtest86+ has correctly excluded the reserved and ACPI NVS regions from its memory map. If your machine hangs when memtest86+ tests the ACPI data regions, the BIOS isn't labelling the regions correctly. Are there any BIOS updates available for that machine that might fix it?

**Comment by jt-fuw** [comment]
I hasn't investigate BIOS updates - maybe i will try now...
I made yet another program which was started from disk bootsector, its values differs from these shown under FreeDOS (the FreeDOS was started from network and used a ramdisk):

- the usable area starting from 0 extends till 0x9c000;
- the usable area starting from 0x100000 extends till 0x9d725000;
- a type 4 area is from 0x9d725000 to 0x9d7f9000;
- a type 3 area is from 0x9d7f9000 to 9f6a4000;
- a type 2 area from 0x9f800000 is divided to two areas - both type 2, 8 MiB + 256 MiB.
Info from INT 0x15 0xE820 function; from bootsector:
` 0000000000000000 000000000009C000 0000000100000001`
` 000000000009C000 0000000000004000 0000000100000002`
` 00000000000E0000 0000000000020000 0000000100000002`
` 0000000000100000 000000009D625000 0000000100000001`
` 000000009D725000 00000000000D4000 0000000100000004`
` 000000009D7F9000 0000000001EAB000 0000000100000003`
` 000000009F6A4000 000000000003B000 0000000100000002`
` 000000009F6DF000 00000000000AB000 0000000100000003`
` 000000009F78A000 0000000000055000 0000000100000004`
` 000000009F7DF000 0000000000021000 0000000100000003`
` 000000009F800000 0000000000800000 0000000100000002`
` 00000000A0000000 0000000010000000 0000000100000002` 
` 00000000FED1C000 0000000000004000 0000000100000002`
` 00000000FF800000 0000000000800000 0000000100000002`
` 0000000100000000 000000005C000000 0000000100000001`
Hangs are caused by testing any of ranges:
- 0x9f600000-0x9f700000 (contains region types 3, 2, 3);
- 0x9f700000-0x9f800000 (contains region types 3, 4, 3).

I don't see a possibility to select test range with finer granularity, therefore I cannot tell which regions cause hangs - each of these ranges overlaps with 3 regions.

**Comment by martinwhitaker** [comment]
> I don't see a possibility to select test range with finer granularity, therefore I cannot tell which regions cause hangs - each of these ranges overlaps with 3 regions.

Ah, there was a bug in the code that read the address values, which I've just fixed in the main branch. You should now be able to specify addresses with a granularity of 4KB (1 page). Either check out and build from git or wait for the next nightly build.

**Comment by jt-fuw** [comment]
I used it and determined which pages cause the hang: 0x9F68E000 (= 2611768 KiB) and 9F7FF000 (= 2613244 KiB). Both in regions type 3 = ACPI reclaimable memory.

**Comment by debrouxl** [comment]
Well... for a BIOS implementation, screwing up the DMI data in multiple ways is routine, but screwing up the PM map by declaring as reclaimable memory ranges which do not behave as normal memory is pretty infrequent... It could be due to another device, built-in or on an expansion slot, whose buggy firmware fails to report its memory areas properly.

Maybe the other OS do not reuse small ACPI reclaimable memory ranges for their purposes, but attempting to test those ranges is what one would expect from a memory testing program such as memtest86+...
In order to make memtest86+ work on that MB without user intervention, special-casing the model and/or set of BIOS versions would theoretically be _possible_, assuming these pieces of information can be accurately retrieved through the DMI data or another source of information... but is it worth the trouble ?

**Comment by jt-fuw** [comment]
Excerpt from /proc/iomem of Linux SystemRescue 11.0 started from DVD:
`00100000-9d740fff : System RAM`
(code in bootsector reports region type 4 from 9d725000)
`9d741000-9d814fff : ACPI Non-volatile Storage`
(code in bootsector reports region type 4 to 9d7f9000
 and region type 3 from this address to 9f6a4000)
`9d815000-9f6a3fff : ACPI Tables`
(still in the region type 3, contains 0x9F68Exxx page)
`9f6a4000-9f6defff : Reserved`
(code in bootsector reports region type 2 just here)
`  9f6d3018-9f6d3067 : APEI ERST`
`  9f6d3070-9f6d3077 : APEI ERST`
`  9f6d3078-9f6d5017 : APEI ERST`
`9f6df000-9f789fff : ACPI Tables`
(code in bootsector reports region type 3 just here)
`9f78a000-9f7defff : ACPI Non-volatile Storage`
(code in bootsector reports region type 4 just here)
`9f7df000-9f7fffff : ACPI Tables`
(reported region type 3, contains 9F7FFxxx page)
`9f800000-afffffff : Reserved`
(code in bootsector reports 2 consecutive regions type 2)

I guess a network boot may use some memory, and using a ramdisk for FreeDOS must use it - but here I am comparing areas shown by a code put in bootsector of a hard disk partition, and shown by Linux bootsed from a DVD. Strange...

Is it hard to add a selection of E820-reported region types like tests are selected?

**Comment by martinwhitaker** [comment]
Adjacent usable regions are merged to make testing more efficient. This is done early in the startup process, so we would have to make significant changes to allow user selection of which regions are tested.

**Comment by x86fr** [comment]
hardware/BIOS issue
