### ISSUE TITLE
memtest64.efi and ipxe

### ISSUE THREAD

**Issue by Unikat2000** [memtest86plus/memtest86plus#413]
Hello,

I'm trying to boot memtest64.efi via ipxe over network with following configuration The file itself got loaded, but then a black screen is shown and nothing happens. Secure Boot is disabled!

:memtest_efi
echo uefi-mode 
kernel ${root-path}/memtest64.efi
boot || goto failed

**Comment by debrouxl** [comment]
Thanks for the report.
Could you give us some information about the version of memtest you're running, and the computer(s) you're running it on ?

**Comment by Unikat2000** [comment]
Hi,

I tried latest 7.00 and the previous 6.20. The uefi PC that I'm using is a AMD Ryzen 7 7800X3D running on a MSI B650 Tomahawk Motherboard with 64GB DDR5 RAM. Graphics in nvidia RTX 2070.

The other PC in the network is non-uefi using the floppy.img, which works fine.

**Comment by x86fr** [comment]
Can you to load another uefi binary (like a shell)?

**Comment by Unikat2000** [comment]
yes...  I can load the ipxe shell or what you do mean? You can give me an example and I will try it....

**Comment by martinwhitaker** [comment]
Try the nightly build (or build yourself from the git master branch) and boot with the `efidebug` boot command line option. Does that display anything?

**Comment by Unikat2000** [comment]
I compiled my own memtest.efi and added efidebug as an option..  still the same issue...

for exluding an ipxe issue: I tried booting the latest ISO with ventoy from anusb stick and the same issue...

**Comment by martinwhitaker** [comment]
Did you use the Linux ISO w/GRUB? Does it display the GRUB menu?

**Comment by Unikat2000** [comment]
The regular ISO doesn't work... the one w/GRUB shows menu and executes memtest....

**Comment by JRBSMaster** [comment]
Here it works with the following configuration:

:memtest_efi
	chain ${root-path}/memtest64.efi || goto failed
goto start

**Comment by Unikat2000** [comment]
Hi JRBSMaster,

thx for your configuration, but it didn't work for me...  still the same blank screen. So I assume there is something special about my hardware setup, that prevents it from working.

At least I know that it would work that way with ipxe...

**Comment by NobodyNada** [comment]
I'm seeing similar symptoms on a Ryzen 9 7950X3D, on a Gigabyte Eagle AX B650 motherboard, with a Radeon 7700 XT GPU. BIOS mode works fine, but I get a black screen when launching in EFI mode (whether over USB or from `systemd-boot`). I've tried both 7.00 and the latest nightly build with a variety of `screen.mode` and `efidebug` options, as well as tweaking firmware settings related to graphics; with no success.

Notably, the symptoms appeared only after I swapped out my CPU and motherboard. Up until today my PC had an i9-13900k with a Gigabyte Eagle AX Z790 motherboard, but I switched to AMD after experiencing symptoms of Intel's instability issue. So it would seem the issue is something specific to my Ryzen CPU or motherboard with the B650 chipset.

**Comment by Unikat2000** [comment]
Hi NobodyNada,

thx for you reply. This really could be a lead to the issue. Do you have the onboard (CPU-GPU) enabled or disabled?

**Comment by NobodyNada** [comment]
@Unikat2000 I tried both enabled and disabled in the firmware settings, and didn't get any display output from memtest with either (whether plugged into a DisplayPort connector on the GPU or the motherboard).

**Comment by NobodyNada** [comment]
If I remember correctly, I didn't hear the fans spin up like they normally do when I run memtest, so I suspected that memtest was outright crashing rather than just a display issue. I'll test that again to confirm next week when I'm back at my PC.

**Comment by martinwhitaker** [comment]
Could you test if the following patch makes any difference
````
diff --git a/boot/header.S b/boot/header.S
index 23e9a14..f337dd3 100644
--- a/boot/header.S
+++ b/boot/header.S
@@ -190,6 +190,7 @@ section_table:
        .word   0                               # NumberOfRelocations
        .word   0                               # NumberOfLineNumbers
        .long   IMAGE_SCN_MEM_READ              \
+             | IMAGE_SCN_MEM_WRITE             \
              | IMAGE_SCN_MEM_EXECUTE           \
              | IMAGE_SCN_CNT_CODE              # Characteristics (section flags)
 
````

**Comment by Unikat2000** [comment]
Hi @martinwhitaker 

I'm not familiar with the code you provided, but after checking the header.s file I assume you want me to add an additional line into the current code?  Correct?   => **| IMAGE_SCN_MEM_WRITE**

**Comment by debrouxl** [comment]
Yup, you need to insert this `             | IMAGE_SCN_MEM_WRITE             \` line into the current code :)

**Comment by Unikat2000** [comment]
Ok, thx

I added the line and compiled it.  Now it is working like expected :)  Even with the screen.mode parameter. Thx for fixing it :)

Just for curiosity: Was this issue related to Ryzen / B650 chipset or a general efi thing?

**Comment by martinwhitaker** [comment]
This is a more general thing - see issue #377. It looks like newer UEFI BIOSs are enabling memory protection.

**Comment by Unikat2000** [comment]
Ok I understand.  I assume this fix be integrated in the upcoming version of memtest?

Thx again for the help :)

**Comment by martinwhitaker** [comment]
We need to check if this simple fix causes any issues with shim / secure boot. I don't have any systems that allow me to test that.

**Comment by Unikat2000** [comment]
Ok I understand. 
I enabled secure boot on my system and it still works....

**Comment by NobodyNada** [comment]
@martinwhitaker Your patched fixed it on my system as well, thanks!

No issues with secure boot -- I signed `memtest64.efi` using my own keys, and it boots and runs just fine.

**Comment by martinwhitaker** [comment]
Thanks for the secure boot tests @Unikat2000 and @NobodyNada .

@x86fr and @debrouxl , are you happy with this fix? As it's a one-liner, I propose to commit it directly to main rather than spend time creating a PR.

**Comment by x86fr** [comment]
Sure.

**Comment by martinwhitaker** [comment]
Fix pushed to the main branch, so will be in the next nightly build and next release.
