### ISSUE TITLE
Memtest86+ v7.0.0 Slows Down on Additional Passes

### ISSUE THREAD

**Issue by JHGrove3** [memtest86plus/memtest86plus#431]
I just upgraded from Memtest 6.2 to Memtest 7.0

The new version runs much slower after it completes its initial pass.

On my current test, I received a PASS notice at the end of the first pass, which took 53 minutes.

The same test is still running. I'ts been 1 hour and 53 minutes total, yet pass #2 is only at 40% completion.  So it's taken 1 hour just to get 40% of the 2nd pass done.

This is the same thing I have noticed on several prior tests that I ran.

~~I don't recall this happening on Memtest 6.2. I didn't specifically check for it, but I think I would have noticed it given how quickly I noticed it with the new version.~~

I can't say for certain whether the initial pass gets slower throughout the test, or whether it slows down after it completes the first pass. I can't tell because it's running tests of different complexity throughout the pass, so the speed could vary a lot for different tests. But the two passes should be consistent, I believe, as I think they are running the same tests.

I am running the test on a Geekom IT12 (12th gen Intel i7) with 64GB of Crucial RAM: 2x32GB DDR4-3200.

Edit: Struck through text about previous version.

**Comment by debrouxl** [comment]
Indeed, the first pass is (almost, considering that the bit fade tests are time-based) exactly three times shorter than subsequent passes:

https://github.com/memtest86plus/memtest86plus/blob/main/app/main.c#L465C25-L468C6
```
    if (pass_num == 0) {
        // Reduce iterations for a faster first pass.
        iterations /= 3;
    }
``` 
The code has always been that way, though ?

**Comment by JHGrove3** [comment]
Yep - I was just coming back to edit my bug report.  I pulled out a copy of version 6.2 and ran it on the same setup to see how it compared.  Turns out I was wrong about the old version! It's been 1:47 and I'm at 37% on my 2nd pass. In 6 minutes I expect to be at 40%.
