### ISSUE TITLE
[Feature Request] VRAM Testing

### ISSUE THREAD

**Issue by moriel5** [memtest86plus/memtest86plus#432]
I realize that this may possibly be out of scope, and may deserve it's own project, however being able to test VRAM, similarly in idea to VMTCE (up to 512MB, the last update was in 2009) would be extremely helpful in diagnosing GPUs with faulty memory.

VMTCE source (GPLv3): [https://sourceforge.net/projects/vmtce/](https://sourceforge.net/projects/vmtce/)

The software was built with FreePascal, and the license is distributed within the downloadable archives, rather than being it's own file in the repository.

**Comment by x86fr** [comment]
Unfortunately, this is really out of scope.
