### ISSUE TITLE
Feature request: AMD k10 based APU temperature

### ISSUE THREAD

**Issue by hap2001gh** [memtest86plus/memtest86plus#438]
I cannot see the CPU temperature on my Stoney Ridge laptop, I hope this feature can be added in future versions.

**Comment by jonathan-teh** [comment]
Stoney Ridge is Excavator, which does have a different method of reading the temperature compared to everything else in family 10h-16h. The mentioned PR should fix it.

**Comment by x86fr** [comment]
Should be fixed by #440
