### ISSUE TITLE
wrong report in badram pattern

### ISSUE THREAD

**Issue by chchia** [memtest86plus/memtest86plus#444]
confirm bug and reproducible:

1. i have a confirm badram address at 0x000000084e190210 (at 33.22GB)
2. if i user individual error report it show 84e190210 (correct)
3. if i use badram pattern it show 8e190210 (wrong)
4. this is reproducible and every time give me the same result, which the badram pattern is showing wrongly without a "4".

this is my version of memtest86+
![image](https://github.com/user-attachments/assets/1b34a941-ff1d-48d2-8eaa-8298533d69da)

**Comment by debrouxl** [comment]
Thanks for the report.
You're using an outdated version of memtest86+, though; please try again with memtest86+ 7.00, which, besides being the current latest release, contains the df803bf2942747457c7275439c0b4da4e3e287f1 fix for the reported badram pattern, after the (certainly same) issue was reported as #308 . Thanks in advance :)

**Comment by chchia** [comment]
oh thank you, i am using proxmox and debian apt only have 6.10, i will live with it for a while until official 7.0 appear in the debian APT.

![image](https://github.com/user-attachments/assets/c9512987-3860-4eab-ba64-0e02247c3f42)

**Comment by chchia** [comment]
just to add on installed 7.0 just for testing, and confirmed that 7.0 now report correct bad pattern.

![image](https://github.com/user-attachments/assets/0d11b0cf-6d8c-4252-9561-5551713f007b)

**Comment by chchia** [comment]
thanks.
