### ISSUE TITLE
v7 x86_64 PXE/EFI boot - two machines, same processor diff motherboards. SMP enabled on one, disabled on other

### ISSUE THREAD

**Issue by AeonJJohnson** [memtest86plus/memtest86plus#445]
Greetings,

I'm PXE booting two machines with identical CPUs but different motherboard/vendors. BIOS settings are same for both.

CPU: AMD Epyc 9454 (Genoa, 48 core)
Motherboard #1 (working) Gigabyte MZ23-G20
Motherboard #2 (not working) Asus K14PA-U24

Same boot method, args, etc for both machines. One shows SMP mode, one shows SMP disabled.

Screenshots attached.

![Screen Shot 2024-10-14 at 12 45 11 PM](https://github.com/user-attachments/assets/796e9336-e6ec-4430-834f-6c7527039e10)
![Screen Shot 2024-10-14 at 12 45 27 PM](https://github.com/user-attachments/assets/8d1000d1-3935-48ab-ad9d-c3c4b2c54796)

**Comment by x86fr** [comment]
The ASUS board has x2APIC enabled by default. x2APIC is currently not supported (but on the top list). You can try to disable x2APIC on BIOS settings if the option is available.

**Comment by AeonJJohnson** [comment]
That was it. Runs as it should set to xAPIC. 

In case any intrepid searcher find this scenario on a Asus/Epyc system:
_Bios Setup -> Advanced -> AMD CBS -> CPU Common Options -> Local APIC Mode = xAPIC_

**Comment by AeonJJohnson** [comment]
Thanks!

**Comment by debrouxl** [comment]
The reported temperature looks too high as well.
