### ISSUE TITLE
Not loading on some AM5 motherboards.

### ISSUE THREAD

**Issue by 100ikov-81** [memtest86plus/memtest86plus#453]
Some motherboards can't load software. After booting up flash drive it stays on black screen and nothing happens. 
I'll make a list of problematic motherboards if it's necessary. On Intel motherboards, there is no such problems.

**Comment by debrouxl** [comment]
Which version of memtest86+ are you using, and how did you write the USB Flash drive ?

**Comment by 100ikov-81** [comment]
Memtest86+ v7.00 with default 
Windows USB Installer (32/64 bits)

**Comment by debrouxl** [comment]
Could you try using
1) the nightly version from https://memtest.org/dev/ , soon-ish to be the next release according to https://github.com/memtest86plus/memtest86plus/pull/427#issuecomment-2453465016 ;
2) if that does not solve the problem, Rufus to write the ISO in dd mode - see https://github.com/memtest86plus/memtest86plus/issues/399#issuecomment-2094855871 .
Thanks in advance :)

**Comment by 100ikov-81** [comment]
I'll try it.

Thank you for your support.

**Comment by 100ikov-81** [comment]
Nightly version starts and run OK. 

Thanks for support!

**Comment by debrouxl** [comment]
Thanks for your tests :)
I'll now close this issue.
