### ISSUE TITLE
Low Memory Bandwidth

### ISSUE THREAD

**Issue by westlake-san** [memtest86plus/memtest86plus#465]
Version 7.2 writes about a tenth of the real bandwidth. I have not tried with older versions. It shows ~800 MB/s, PassMark MemTest86 shows ~8 GB/s. The latter is the real value. I tried with several modules. 

Z10PE-D8 WS (C612), Xeon E5-2699 v3 + Xeon E5-2696 v3

With X99 motherboard, it shows the correct value (~7.6 GB/s).

**Comment by x86fr** [comment]
Duplicate #284
