### ISSUE TITLE
Keyboard testing: `noehci` turns out to be important

### ISSUE THREAD

**Issue by cwsystem76** [memtest86plus/memtest86plus#47]
This is the followup to the testing talked about this GitHub discussion (https://github.com/memtest86plus/memtest86plus/discussions/45). I built from source (at https://github.com/memtest86plus/memtest86plus/tree/66c6dfa3576f5720956848b7870fa04bf8da4c7d) with `make grub-iso`, created a USB stick, and ran a number of tests. This didn't take me as long as I expected as the problems were largely confined to one system (with multiple keyboards) and one keyboard (with multiple systems).

The five keyboards tested are:

* A Dell SK-8135 multimedia keuboard which has a USB1 hub built in (USB ID 413c:2010 https://web.archive.org/web/20111012163355/http://support.dell.com/support/edocs/acc/P76379/specs.htm)
* A System76 Launch mechanical keyboard with a USB3 hub built in, connected via a USB-C to USB-A cable (USB ID 3384:0001 https://tech-docs.system76.com/models/launch_1/README.html)
* A Logitech K400 wireless keyboard with touchpad, using a Logitech Unifying Receiver (USB ID 046d:c52b https://support.logi.com/hc/en-us/articles/360023306254-K400-Technical-Specifications)
* An HP KBAH21 keyboard, basically as generic an OEM keyboard as you can get (USB ID 0461:4e67 https://www.amazon.com/HP-801526-001-Keyboard-Galeras-wired/dp/B00XLVVEIM)
* A generic Chinese mechanical keyboard branded "Elecrat" (USB ID 258a:0190, original page has now disappeared from Amazon but it's basically this with slightly different branding, IDs as a "SINO WEALTH" device which is the microcontroller, I think: https://www.amazon.com/Water-Resistant-Backlit-Mechanical-Keyboard-Switches/dp/B01MRM4PB3)

The four systems used for testing are:

* A custom PC using an ASUS Z87-Expert motherboard, which has two different USB controllers built into it: the Intel XHCI controller from the Z87 chipset, and an additional ASMedia XHCI USB controller, but I've only listed it once because the results were the same regardless of which ports I used (UEFI, https://dlcdnets.asus.com/pub/ASUS/mb/LGA1150/Z87-EXPERT/E7833_Z87-EXPERT.pdf))
* A System76 Oryx Pro (model `orypx6`), using Coreboot firmware on a Intel HM470 chipset (UEFI, https://tech-docs.system76.com/models/oryp6/README.html)
* A 2013 MacBook Air (model `MacBookAir6,2`) with an Intel USB chipset I think? (Apple EFI, https://everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i7-1.7-13-mid-2013-specs.html)
* An HP EliteBook 8460p with an Intel QM67 chipset (BIOS, http://h10032.www1.hp.com/ctg/Manual/c03253774.pdf)

The chart key for results:

* *Y* - works with the default boot mode
* *B* - works with the `keyboard=buggy-usb` option enabled
* *E* - works with the `noehci` option enabled
* *X* - does not work at all regardless of options

I am not doing testing with the `keyboard=legacy` mode, as this would often require end-users to change their UEFI configuration, but could do so later if needed.

|               | Dell    | Launch  | K400    | HP      | Elecrat |
|---------------|---------|---------|---------|---------|---------|
| Z87-Expert    |    E    |    E    |    E    |    Y    |    Y    |
| Oryx Pro      |    Y    |    Y    |    X    |    Y    |    Y*   |
| Macbook Air   |    Y    |    Y    |    X    |    Y    |    Y*   |
| HP 8460p      |    Y    |    Y    |    X    |    Y    |    Y    |

The Z87-Expert has a number of BIOS configuration options, including an "EHCI handoff" setting, which did not have any effect. The `noehci` option was required to get the K400, the Launch, and the Dell working with it, regardless of what BIOS settings were used. Enabling `buggy-usb` caused the Dell to fail to be detected at all; in all other cases the keyboards were detected (and show up on the blue screen as detected devices) but no keyboard input was accepted. I can provide screen photos but there didn't seem to be any useful information other than the keyboard being found.

The thing that all the keyboards that needed `noehci` on the Z87 have in common is that they're all running multiple devices through the one connection. The Logitech wireless receiver has a K400 keyboard and touchpad connecting to it, and the Dell and Launch both have actual USB hubs in them. The HP and the Elecrat are just straight keyboards with no extra bits other than muiltimedia controls. That seems like it might be important?

The K400 doesn't seem to work at all on most of these systems; the fact that it works on the Z87 with `noehci` but none of the other systems is weird, especially since the Z87 had problems with other keyboards as well. The K400 with the receiver always seemed to be recognized as a keyboard but the system would not accept any input from it.

The Elecrat would sometimes not work the first time, but work on a reboot; I would chalk that up to it being a no-name cheap keyboard that just misbehaves sometimes.

Your last comment in the discussion thread about `buggy-usb` being rarely required was correct. So the next question is, are the issues with the Z87 system and the Logitech receiver in general worth investigating further? The fact that the `noehci` option seems to fix the problems with the Z87 system suggests to me that it might be good to set that up as a menu option on the downloadable ISOs, assuming that they'll be using GRUB. That might be quicker than trying to debug the actual problem, which might be related to the Z87 firmware anyway. The K400 might just be a loss in terms of support, although I'd be interested to know if anyone else has better results with a different unifying receiver or keyboard.

**Comment by x86fr** [comment]
Thanks for that detailed report. To keep the issues list clean, it's probably better to keep this as a discussion and create two issues (and add screenshot of the USB detection screen) : 

1. Logitech K400 not detected on various motherboard
2. noehci needed on Asus Z87-Expert

About the K400, I have a K400+ on my dev bench and it works on numerous motherboards, so it seems to be related to the K400 (without "+") only.

**Comment by cwsystem76** [comment]
I know there's a couple of different revisions of the Logitech Unifying Receiver so it might be that and not the K400 itself.

I'll close this issue out, transfer the contents of the initial post to the discussion, and start two new issues, one for the K400 and one for the Z87. Thanks for the feedback.
