### ISSUE TITLE
Logitech K400 w/ Unifying Receiver not detected

### ISSUE THREAD

**Issue by cwsystem76** [memtest86plus/memtest86plus#48]
This issue is being opened in reference to this existing GitHub discussion (https://github.com/memtest86plus/memtest86plus/discussions/45).

A Logitech K400 (https://support.logi.com/hc/en-us/articles/360023306254-K400-Technical-Specifications) that's paired with a Unifying Receiver (USB ID 046d:c52b) is not detected when booted up via a `grub-iso` build of memtest86+ (or other builds for that matter). I built the test ISO from source using commit 66c6dfa and tested it on multiple systems. I'm sharing the details here about three systems; I'm skipping the fourth because it's going to get its own issue later, since it's got problems of its own with other keyboards.

This is the output of `sudo lsusb -v -d 046d:c52b` run from within Pop!OS v22.04 (beta) on a System76 Oryx Pro (model _oryp6_) with the Unifying Receiver plugged in:

```
Bus 001 Device 012: ID 046d:c52b Logitech, Inc. Unifying Receiver
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc52b Unifying Receiver
  bcdDevice           12.10
  iManufacturer           1 Logitech
  iProduct                2 USB Receiver
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          4 RQR12.10_B0032
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               98mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      59
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     148
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               2
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      93
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               2
Device Status:     0x0000
  (Bus Powered)
```

The receiver is normally plugged into a Windows system (an HTPC/gaming system attached to the living room TV) and has the latest firmware according to both Logitech's Windows software and `fwupd`; same for the keyboard.

The three systems I'm providing test results for are the HP Elitebook, the Oryx Pro, and the MacBook Air as described in the related discussion (https://github.com/memtest86plus/memtest86plus/discussions/45). These are the screenshots I took for each. The first screenshot in each set is from memtest86+ run with just the `usbdebug` option; the second is from a run with `usbdebug noehci`.

The HP:

![HP-1](https://user-images.githubusercontent.com/96320715/164351575-f8609725-7e12-476b-8035-08542298cfc3.jpeg)
![HP-2](https://user-images.githubusercontent.com/96320715/164351602-f128a779-5ae3-4505-9a5f-1b5a32c4e66d.jpeg)

The Oryx Pro:

![oryx-1](https://user-images.githubusercontent.com/96320715/164351663-e101602b-72c2-4f74-b2db-83e7a2c1270b.jpeg)
![oryx-2](https://user-images.githubusercontent.com/96320715/164351669-6791c7e1-e233-40dd-a5f8-cff06e5e4e44.jpeg)

The Macbook Air:

![MBA-1](https://user-images.githubusercontent.com/96320715/164351680-c2c9000e-6efc-4bd3-99e9-3d4c613050e7.jpeg)
![MBA-2](https://user-images.githubusercontent.com/96320715/164351697-e715ebd3-1fd4-4392-b270-a4129f39b1fc.jpeg)

Each of these photos does show detected keyboards, but they're all laptops so they may be the integrated ones? Laptop keyboards should generally be attached to the i2c bus and not USB, though, so I may be wrong.

In each case the Logitech K400 worked fine before memtest86+ loaded; I was able to choose the boot device and edit the launch parameters in GRUB with it on each system, but memtest86+ did not receive any input from it. The integrated keyboards all work normally.

If there's any additional testing needed with this particular unifying receiver, let me know.

**Comment by martinwhitaker** [comment]
The keyboard interface and endpoint descriptors from your unifying receiver match mine, so nothing to be learnt there.

Yes, laptop keyboards don't usually appear as USB devices, but to confirm Memtest86+ is really detecting the K400, try starting Memtest86+ without the K400 plugged in (on one machine would be enough).

To check if there's any activity on the keyboard interrupt pipe, try adding this patch
````
--- a/system/xhci.c
+++ b/system/xhci.c
@@ -888,6 +888,7 @@ static uint8_t get_keycode(const usb_hcd_t *hcd)
     xhci_trb_t event;
 
     while (get_xhci_event(ws, &event)) {
+print_usb_info("Received event type %i cc %i", event_type(&event), event_cc(&event));
         if (event_type(&event) != XHCI_TRB_TRANSFER_EVENT || event_cc(&event) != XHCI_EVENT_CC_SUCCESS) continue;
 
         int kbd_idx = identify_keyboard(ws, event_slot_id(&event), event_ep_id(&event));
````
and booting with the `usbdebug` option. When it displays the "press any key to continue" message, does anything get printed out when you press a key?

**Comment by cwsystem76** [comment]
The HP shows zero keyboards detected and the MacBook Air shows two with the K400 disconnected, so it appears that memtest's USB driver is _detecting_ the K400 but it's not accepting any input from it. (Pretty sure the Oryx Pro should be the same since the integrated keyboard is using the i8042 kenrnel driver right now.) Should have tested that off the bat, whoops. 

Applying that patch, rebuilding the USB stick, and booting the HP or MBA with `usbdebug` results in this as the output from the K400 when I press any key:
```
Received event type 32768 cc 1
```
It occurs twice, once on key-press and once on key-release, so it appears to be receiving both events (not sure what they're called on the driver level). If I don't boot the stick with `usbdebug`, it continues normally to the testing screen and pressing a key causes that message to appear while running the tests, but it ignores the actual keypress otherwise (like the spacebar or F1). This is what happens when I pressed F1 three times during the testing and the menu did not come up:

![IMG_0182](https://user-images.githubusercontent.com/96320715/164997768-520e24a2-16d2-47b0-903e-90b2ccc0e38f.JPG)

Interestingly enough this is the same event type that my other keyboards generate, but keypresses on those are accepted by memtest (like F1, F10, etc) at the same time as they generate an event line. Pressing F1 on other keyboards prints `Received event` etc but also opens up the configuration menu.

Some additional testing I did involved plugging the K400 receiver into a different port on the HP, which causes it to be detected by the EHCI driver instead, but memtest still does not recognize any keypresses from the K400.

I also did some digging in my spare parts and found that I have a _second_ Logitech Unifying Receiver, but it's the same USB ID (`046d:c52b`) and appears to have the same firmware on it (`RQR12.10_B0032`) so I don't think that re-pairing the K400 to the second one will help. I can try if you think it'll make a difference.

However, while looking at the firmware versions, I found that there appears to be _four_ different kinds of firmware for Logitech Unifying Receivers at the moment [according the LVFS](https://fwupd.org/lvfs/search?value=unifying+receiver): `RQR12` and `RQR24`, and both signed and unsigned versions. The signed ones appear to be a security update that's still in testing and do not offer an upgrade by default. However, I'm wondering if part of the issue here is that my receivers are both RQR12, and possibly yours are both RQR24? I'm hesitant to try the `RQR12.11_B0032` firmware since it's still in testing and I don't know if that would change anything with this particular issue, but I can try if you want since I do have a spare receiver in case it gets bricked.

Let me know what else I can do moving forward.

**Comment by cwsystem76** [comment]
Continued doing some looking through the [Logitech firmware updates on GitHub](https://github.com/Logitech/fw_updates) and I think I may have found something else. You said in the discussion thread that you have two different Logitech receivers, `046d:c52e` and `046d:c534`, but those aren't listed as being Logitech Unifying Receivers in the RQR12 and RQR24 firmware updates.

The `046d:c534` receiver is apparently a "Logitech Nano Receiver" which does not work quite the same as their Unifying ones, and the `046d:c52e` receiver is apparently specific to the MK260 but is also considered a "Nano" receiver. They may show up in `lsusb` as `Logitech, Inc. Unifying Receiver` but I'm pretty sure that they're different devices internally.

These two devices are described here, showing that they're "Nano" and not "Unifying", and it's possible that the source for Solaar might be helpful as well if it defines how those kinds of devices differ: https://pwr-solaar.github.io/Solaar/devices.html

**Comment by martinwhitaker** [comment]
You are right, I was being misled by `lsusb` into thinking my receivers were the Unifying type, but they are not.

However, the fact that the receiver is sending keyboard interrupt reports when you press and release keys is promising. We now need to look at what it is sending. Could you test again with this patch:
````
--- a/system/xhci.c
+++ b/system/xhci.c
@@ -894,6 +894,16 @@ static uint8_t get_keycode(const usb_hcd_t *hcd)
         if (kbd_idx < 0) continue;
 
         hid_kbd_rpt_t *kbd_rpt = &ws->kbd_rpt[kbd_idx];
+print_usb_info("mods %02x rsvd %02x keycodes %02x %02x %02x %02x %02x %02x",
+  (uintptr_t)kbd_rpt->modifiers,
+  (uintptr_t)kbd_rpt->reserved,
+  (uintptr_t)kbd_rpt->key_code[0],
+  (uintptr_t)kbd_rpt->key_code[1],
+  (uintptr_t)kbd_rpt->key_code[2],
+  (uintptr_t)kbd_rpt->key_code[3],
+  (uintptr_t)kbd_rpt->key_code[4],
+  (uintptr_t)kbd_rpt->key_code[5]
+);
         uint8_t keycode = kbd_rpt->key_code[0];
         if (keycode != 0) {
             int kc_index_i = ws->kc_index_i;
````

**Comment by martinwhitaker** [comment]
That explains why the K400 is not working. I worked from the description of the USB keyboard boot protocol I found at https://wiki.osdev.org/USB_Human_Interface_Devices, but it appears that is not correct.. Reading the HID spec,, it says that the order in which keycodes appear in the report has no significance. That makes handling rollover much harder.

**Comment by cwsystem76** [comment]
Welp. Sorry to hand you a larger problem instead of the small one I was expecting.

Let me know if you need me to test any new builds, since we know I have a Weird Keycode Order Keyboard.

**Comment by martinwhitaker** [comment]
Please try the latest code in the main branch, which I hope will fix this bug.

**Comment by cwsystem76** [comment]
Built a new `make grub-iso` image and the K400 is now working without extra startup parameters on all four test PCs (HP, Oryx, MBA, and custom PC). Built another regular `make iso` image with no changes and it works fine as well.

I also tested the Launch and the Dell keyboard on some of those systems and they're working normally, so there doesn't _seem_ to be any regression for keyboards with "normal" keycode orders.

I have some other things to investigate on my end (my System76 Oryx Pro had a custom Coreboot build on it that wouldn't boot the stick but reverting it back to a release firmware worked fine), and there's still the issue of the desktop PC misbehaving with a bunch of keyboards, but those are all other issues that I'll try to narrow down further before submitting anything.

I've leave it up to you to close the GitHub issue as I'm not sure if you need any additional testing on the PR and related commits yet. Thanks again for your attention to this.

**Comment by x86fr** [comment]
Sounds good for the K400 with Unifying receiver. Please open another issue if you find something wrong with unrelated hardware.
