### ISSUE TITLE
Allow more then 2 digits in core selection

### ISSUE THREAD

**Issue by danielstr007** [memtest86plus/memtest86plus#50]
Found a small glitch, which might be also worth to fix:
![2022-04-21 18_30_44-Virtual Desktop - Desktop Viewer](https://user-images.githubusercontent.com/102787488/164508582-71f23b49-99ce-49e0-8dfb-db0a37ebb218.png)
You can "only" select up to 99 - in a decade of more than 100 cores, this might be worth to allow 3 digits as input.

Or did I miss something to put something like 1-127 Cores?

_Originally posted by @danielstr007 in https://github.com/memtest86plus/memtest86plus/issues/49#issuecomment-1105457282_

**Comment by martinwhitaker** [comment]
Thanks, fixed.
