### ISSUE TITLE
Cannot pass boot options when directly booting an EFI image (from BIOS or via rEFInd)

### ISSUE THREAD

**Issue by nidefawl** [memtest86plus/memtest86plus#53]
I am using refind to boot the 64 bit efi version.
On one of my machines the USB keyboard does not work, and I was trying to pass in the `buggy` or `noehci` option.
It seems like none of the options make it to memtest.

This is my refind.conf:
```
menuentry "MemTest86" {
    icon /EFI/BOOT/icons/tool_memtest.png
    loader /EFI/tools/memtest86.efi
}
menuentry "MemTest86 (noehci)" {
    icon \EFI\BOOT\icons\tool_memtest.png
    loader \EFI\tools\memtest86.efi
    options "noehci nobench"
}
menuentry "MemTest86 (debug)" {
    icon \EFI\BOOT\icons\tool_memtest.png
    loader \EFI\tools\memtest86.efi
    options "keyboard=buggy-usb noehci usbdebug trace nobench nosm trace"
}
```
This is from refind.log
```
==========Launching 'Boot MemTest86 (noehci) from LINUXUSB'==========
11:07:28 - Getting EFI variable 'PreviousBoot' from disk
11:07:28 - Loading file 'PreviousBoot'
11:07:28 - Saving EFI variable 'PreviousBoot' to disk
11:07:28 - Freeing OldBuf
11:07:28 - Have freed OldBuf
11:07:28 - Starting memtest86.efi
11:07:28 - Using load options 'noehci nobench'
11:07:28 - '\EFI\tools\memtest86.efi' is a valid loader
11:07:28 - Getting EFI variable 'SecureBoot' from NVRAM
11:07:28 - Launching 'memtest86.efi'
```

I also tried using grub from build64/grup-esp.img. Same result.

**Comment by martinwhitaker** [comment]
Currently boot command line options are only supported when using an intermediate bootloader to start Memtest86+ via one of the Linux boot protocols. rEFInd is a boot manager that simply chain loads the EFI image. We should add support for passing on the boot options in this case.

Using GRUB should work. I've just tested it again using the `grub-memtest.iso` built by `make grub-iso`, both booted directly from the UEFI BIOS and indirectly via rEFInd. If you have problems with that, please open a separate issue.

**Comment by nidefawl** [comment]
I can confirm that `grub-memtest.iso` works with options
Thanks for clearing it up.
