### ISSUE TITLE
DMI productname not always enough?

### ISSUE THREAD

**Issue by mmuman** [memtest86plus/memtest86plus#55]
I noticed the productname was printed from the DMI tables, but in case of ThinkPad machines this contains the model number, which is quite cryptic, although it does determine the model uniquely. Would it be interesting to also display the version string?

As a record here is the DMI dump on my T510:
```
Handle 0x0001, DMI type 1, 27 bytes
System Information
        Manufacturer: LENOVO
        Product Name: 4384Z8S
        Version: ThinkPad T510
        Serial Number: …
        UUID: …
        Wake-up Type: Power Switch
        SKU Number: Not Specified
        Family: ThinkPad T510

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
        Manufacturer: LENOVO
        Product Name: 4384Z8S
        Version: Not Available
        Serial Number: 
        Asset Tag: Not Specified
        Features: None
        Location In Chassis: Not Specified
        Chassis Handle: 0xFFFF
        Type: Unknown
        Contained Object Handles: 0

```

**Comment by x86fr** [comment]
Unfortunately, we can't support all specific cases when manufacturers does not follow DMI specifications. 
In this case, the `4384Z8S` is the SKU and should have been added in `SKU Number`.  `Product Name` should contains `ThinkPad T510`. 

This said, for debugging purpose, it's much more interesting to get the unique SKU than the commercial retail name, so maybe Lenovo did that on purpose.

**Comment by mmuman** [comment]
Indeed, on the ProLiant server here version is just Not Specified.
I was merely asking to see if there was an interest in a patch to also print the version or if it's not worth it.

**Comment by debrouxl** [comment]
Hi François ;)

Given that 1) screen space is limited and 2) the version information can be low quality or plain weird (just like most other bits of DMI data...), I don't think that the DMI data type 2 / 1 version field should be part of the main screen, though I acknowledge its potential usefulness _when the MB manufacturer provided reasonable information in those fields_.
