### ISSUE TITLE
Selection of initial set of tests through the command line

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#58]
This came up in #57 : non-interactive selection of tests through the command line without modifying and recompiling the program.

EDIT: suggested CLI:
* `tests=<m>(,<n>,<p>...)`: enable only tests numbers m, (n, p...);
* `tests=-<m>(,-<n>,-<p>...)`: enable all tests but tests numbers m, (n, p...);
* `tests=<m>-<n>(,<p>-<q>...)`: enable only tests numbers m to n inclusive, (p to q inclusive...);
* `tests=-<m>-<n>(,-<p>-<q>...)`: enable all tests but tests numbers m to n inclusive, (p to q inclusive...);
* combinations of single positive tests and positive test ranges, negative tests and negative test ranges.
In case of an error, e.g. empty resulting set of tests: enable all tests.

**Comment by x86fr** [comment]
> `tests=<m>(,<n>,<p>...):` enable only tests numbers m, (n, p...); 

Looks the most easy to understand.

IMO, before adding all these options to config.c, we should explore the possibility of using UEFI Boot services to read a simple configuration file on the boot media early in the startup process.

**Comment by x86fr** [comment]
Added in #570
