### ISSUE TITLE
Keyboard issue on HP z440 in legacy boot

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#61]
Hi.

I just tested mt86plus_6.00b1_64.grub on my HP z440 workstation and noticed that I either need to boot in UEFI mode (where keyboard works w/o problems) or have to specify keyboard=legacy for my USB keyboard to work in legacy boot.

I also tried keyboard=buggy-usb and it says "No USB keyboards found" and the counts down from 10 to 0.

Let me what information do you need to debug this further.  Thanks!

**Comment by debrouxl** [comment]
Thanks for the report.
* which USB port(s) did you use ? From past experience with a Z440, at least one of the front USB ports is special, it wasn't possible to boot from a USB MSD, or something like that.
* could you provide the list of USB controllers on the PCI bus ? From Linux, filtering the output of `lspci`+ `lspci -n` will do the job; for Windows, the likes of System Information Viewer, HWiNFO, CPU-Z will return the same kind of information. I do no longer have access to a Z440 and the hardware might have changed in the meantime anyway.

BTW: when the memory test starts, does the screen contain 1) manufacturer and model information on the second last line, and 2) DIMM speed - timings - manufacturer - model - manufacturing date in the second half of the screen ?

**Comment by martinwhitaker** [comment]
What is displayed if you use the boot command line option "usbdebug", both with legacy and with UEFI boot?

**Comment by 01e3** [comment]
The keyboard is connected to one of the rear ports, and as mentioned - works in UEFI. It also properly works in Windows / Linux.

I have attached lspci -nn (essentially lspci+ lspci -n) and also the outputs from lsusb and lsbusb.py.

[hpz440-lspci.txt](https://github.com/memtest86plus/memtest86plus/files/8647694/hpz440-lspci.txt)
[hpz440-lsusb.py.txt](https://github.com/memtest86plus/memtest86plus/files/8647696/hpz440-lsusb.py.txt)
[hpz440-lsusb.txt](https://github.com/memtest86plus/memtest86plus/files/8647697/hpz440-lsusb.txt)

I have also attached screenshots from the boot with keyboard=buggy-usb:
![no-keyboard-legacy-BIOS-boot](https://user-images.githubusercontent.com/105136494/167313576-d3dd860f-9de2-4715-a163-cb3e76767ce5.png)
![OK-keyboard-UEFI](https://user-images.githubusercontent.com/105136494/167313578-1891c244-9f95-4566-baca-25a197cfbb39.png)

When memtest is running, it shows the mfg / model: "Hewlett-Packard 212B" but does not show the DIMM speed:
![memtest-running](https://user-images.githubusercontent.com/105136494/167313681-a23cc8cc-dc0c-4aa3-b55c-30730cd46f3b.png)

Will provide usbdebug outputs shortly.

**Comment by 01e3** [comment]
The output / result with usbdebug is the same I captured earlier with keyboard=buggy-usb. The only difference is that it says "Press any key to continue...", which after I looked at the code seems expected - usbdebug sets USB_DEBUG flag, and the only action based on USB_DEBUG is to wait for a key.

BTW - I just noticed that github removed the screenshot names. In case it was not clear, the first one is no-keyboard-legacy-BIOS-boot.png (memtest booted in legacy BIOS mode via GRUB), the 2nd - OK-keyboard-UEFI.png (booted in UEFI via GRUB). I was using "Linux ISO w/ GRUB (64 bits)" installed into a pendrive.

**Comment by 01e3** [comment]
An idea - while it would be great to investigate more why no hubs / devices are found in legacy mode under memtest86, I wonder if it would make sense to automatically enable legacy keyboard as a fallback mechanism (i.e. keyboard=legacy) when no USB keyboards are found?

Also, for the other problem - no DIMM speed info on HP Z440 - should I file a separate bug?

**Comment by debrouxl** [comment]
8086:8d22 has 0c05 type and is in the current list of SMBus controller devices, so it may work. There may be other factors preventing its successful use, though...
Under Linux, does `decode-dimms` from `i2c-tools` print some information, probably after `modprobe eeprom; modprobe at24; modprobe ee1004` (the modules are listed by the script if it doesn't find anything) ? Often, an ACPI memory range reservation conflicting with a system I/O resource, which can usually be seen as a line starting with "ACPI Warning" in the kernel log and the next line, prevents successful `decode-dimms` operation. The `acpi_enforce_resources=lax` Linux cmdline parameter bypasses this reservation, but general usage of this parameter is advised against by mainline, as it's definitely unsafe on some computers... so no need to use this cmdline parameter, even for testing purposes, unless there's a conflict in the kernel log.

**Comment by martinwhitaker** [comment]
> An idea - while it would be great to investigate more why no hubs / devices are found in legacy mode under memtest86, I wonder if it would make sense to automatically enable legacy keyboard as a fallback mechanism (i.e. keyboard=legacy) when no USB keyboards are found?

The default is to enable both USB and legacy keyboard support. But the process of probing the USB bus will disable legacy keyboard emulation, so we'd have to add code to re-enable it  (which no doubt would be equally prone to system-specific quirks).

My intention for the final release is to default to legacy keyboard only when booted in legacy mode. USB support is currently enabled so we can flush out and fix as many issues as we can.

**Comment by martinwhitaker** [comment]
Could you build and test with this patch applied:
````
--- a/system/ehci.c
+++ b/system/ehci.c
@@ -503,12 +503,18 @@ bool ehci_init(int bus, int dev, int func, uintptr_t base_addr, usb_hcd_t *hcd)
         if (ext_cap_id == EHCI_EXT_CAP_OS_HANDOFF) {
             // Take ownership from the SMM if necessary.
             int timer = 1000;
+            print_usb_info("Ownership status is %08x %08x",
+                (uintptr_t)pci_config_read32(bus, dev, func, ext_cap_ptr),
+                (uintptr_t)pci_config_read32(bus, dev, func, ext_cap_ptr + 4)
+            );
             pci_config_write8(bus, dev, func, ext_cap_ptr + 3, 1);
             while (pci_config_read8(bus, dev, func, ext_cap_ptr + 2) & 1) {
                 if (timer == 0) return false;
                 usleep(1*MILLISEC);
                 timer--;
             }
+            print_usb_info("Ownership gained after %ims", 1000 - timer);
+            pci_config_write32(bus, dev, func, ext_cap_ptr + 4, 0);
         }
         ext_cap_ptr = pci_config_read8(bus, dev, func, ext_cap_ptr + 1);
     }
````
(and this if you just want to build the plain ISO / don't want to type boot options)
````
--- a/system/usbhcd.c
+++ b/system/usbhcd.c
@@ -80,7 +80,7 @@ static int print_col = 0;
 // Public Variables
 //------------------------------------------------------------------------------
 
-usb_init_options_t usb_init_options = USB_DEFAULT_INIT;
+usb_init_options_t usb_init_options = USB_DEFAULT_INIT | USB_DEBUG;
 
 //------------------------------------------------------------------------------
 // Macro Functions
````
I'm interested in both the extra debug output and whether the additional PCI write makes it work.

**Comment by 01e3** [comment]
Thanks. Here is the output:

![image](https://user-images.githubusercontent.com/105136494/167529955-97efac96-0bc4-4c72-b1f5-342823e6185c.png)

Regarding testing - I already have PXE boot set up, but I initially used pendrive to test the provided images and also make sure it is not the PXE booting that is causing the kbd problem.

Regarding SMBus:

# decode-dimms
# decode-dimms version 4.3
(...)
Number of SDRAM DIMMs detected and decoded: 0

Tested on Linux 5.15.22

# i2cdetect  -l |grep SMBus
i2c-0   smbus           SMBus I801 adapter at 0780              SMBus adapter

# i2cdetect  -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         08 -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: 20 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- 44 -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- 62 -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

No luck. :(

From dmesg:
[ 1142.669525] i801_smbus 0000:00:1f.3: SPD Write Disable is set
[ 1142.669544] i801_smbus 0000:00:1f.3: SMBus using PCI interrupt
[ 1142.671658] i2c i2c-0: 2/8 memory slots populated (from DMI)
[ 1142.671661] i2c i2c-0: Systems with more than 4 memory slots not supported yet, not instantiating SPD

However, I'm sure I saw CPU-Z / HWInfo64 reporting the SPDs, but let me double check if this is still the case after the recent BIOS update, etc.

....
....
..... 

Yes it does:
Row: 0 [CPU0/CPU0-DIMM8] - 8 GB PC4-19200 DDR4 SDRAM Samsung M393A1G40EB1-CRC
Row: 8 [CPU0/CPU0-DIMM1] - 8 GB PC4-17000 DDR4 SDRAM Samsung M393A1G40EB1-CPB

DIMM #                          1
        SMBus address           0x50
        Memory type             DDR4
        Module format           RDIMM
--
DIMM #                          2
        SMBus address           0x50
        Memory type             DDR4
        Module format           RDIMM

Not sure why it did not work on Linux :(

To compare, on another machine I get:

# ./i2cdetect  -l |grep SMBus
i2c-6   smbus           SMBus PIIX4 adapter at 0b20             SMBus adapter
i2c-5   smbus           SMBus PIIX4 adapter at 0b00             SMBus adapter

# ./i2cdetect  -y 5
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: 30 31 32 33 -- -- -- -- 38 -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: UU UU UU UU -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- 69 -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

And so... 

# decode-dimms|grep detected
Number of SDRAM DIMMs detected and decoded: 4


BTW: I have access to several more machines, if it helps - I can test them later this week.

**Comment by martinwhitaker** [comment]
It would be helpful if you could open a new issue for the SMbus stuff.

**Comment by 01e3** [comment]
Now when we have a dedicated bug for the SPD issue, should we go back to the USB / keyboard problem?

**Comment by martinwhitaker** [comment]
Could you test both legacy boot and UEFI boot with both the following patch and the earlier patch to ehci.c:
````
--- a/system/usbhcd.c
+++ b/system/usbhcd.c
@@ -432,6 +432,16 @@ static void probe_usb_controller(int bus, int dev, int func, hci_type_t controll
         keyboards_found = ehci_init(bus, dev, func, base_addr, &usb_controllers[num_usb_controllers]);
     }
     if (controller_type == XHCI) {
+        print_usb_info("xHC USB 2.0 port control %08x %08x %08x",
+            (uintptr_t)pci_config_read32(bus, dev, func, 0xd0),
+            (uintptr_t)pci_config_read32(bus, dev, func, 0xd4),
+            (uintptr_t)pci_config_read32(bus, dev, func, 0xe4)
+        );
+        print_usb_info("xHC USB 3.0 port control %08x %08x %08x",
+            (uintptr_t)pci_config_read32(bus, dev, func, 0xd8),
+            (uintptr_t)pci_config_read32(bus, dev, func, 0xdc),
+            (uintptr_t)pci_config_read32(bus, dev, func, 0xe8)
+        );
         keyboards_found = xhci_init(base_addr, &usb_controllers[num_usb_controllers]);
     }
     if (keyboards_found) {
--- a/system/xhci.c
+++ b/system/xhci.c
@@ -972,12 +972,17 @@ bool xhci_init(uintptr_t base_addr, usb_hcd_t *hcd)
             xhci_legacy_support_t *legacy_support = (xhci_legacy_support_t *)ext_cap_base;
             // Take ownership from the SMM if necessary.
             int timer = 1000;
+            print_usb_info("Ownership status is %02x %02x",
+                (uintptr_t)legacy_support->bios_owns,
+                (uintptr_t)legacy_support->host_owns
+            );
             legacy_support->host_owns |= 0x1;
             while (legacy_support->bios_owns & 0x1) {
                 if (timer == 0) return false;
                 usleep(1*MILLISEC);
                 timer--;
             }
+            print_usb_info("Ownership gained after %ims", 1000 - timer);
         }
         if (ext_cap->id == XHCI_EXT_CAP_SUPPORTED_PROTOCOL) {
             xhci_supported_protocol_t *protocol = (xhci_supported_protocol_t *)ext_cap_base;
````
What USB settings do you have in your BIOS?

**Comment by 01e3** [comment]
Here is the result with the patch applied:
![no-keyboard-legacy-BIOS-boot-0](https://user-images.githubusercontent.com/105136494/168487410-9bc2e749-18d4-4fe8-a3a9-2df8ad27d481.png)

Regarding USB settings, there aren't that many, which is pretty common for these types of proprietary boards:
![no-keyboard-legacy-BIOS-boot-1](https://user-images.githubusercontent.com/105136494/168487434-6a6baba8-e46d-4f4f-9b98-50f613d72dc5.png)

Also, despite the confusing copyright message (2013-2017), I'm using the newest BIOS - v02.59 release this year. ;)

**Comment by 01e3** [comment]
Sorry, you asked about the output with both the patches applied. Updated:
![no-keyboard-legacy-BIOS-boot-2](https://user-images.githubusercontent.com/105136494/168488367-15a69492-8eba-4410-a2d1-1d55b1eb640f.png)

**Comment by martinwhitaker** [comment]
Also for UEFI boot. I'm trying to identify what your BIOS is doing differently that allows memtest86+ to work in one case but not the other.

**Comment by 01e3** [comment]
Sure, with UEFI:
![no-keyboard-legacy-BIOS-boot-3](https://user-images.githubusercontent.com/105136494/168490308-71bd441c-4388-4835-b52d-fde6304fca73.png)

**Comment by martinwhitaker** [comment]
There are a couple of oddities here:
1. With legacy boot, the BIOS has claimed ownership of the XHCI controller, but not of the EHCI controllers. With UEFI boot it has set the flag that indicates the OS owns the XHCI controller (it shouldn't touch that flag). But in both cases all ports are shown to be switched to the EHCI controller.
2. The port routing mask (00007fff) indicates 15 ports can be switched between the XHCI and EHCI controllers. But the C610/X99 PCH only has 14 USB ports.

My Intel system with a H77 chipset gives the expected output, so I don't think the debug code is faulty.

Linux forces all ports to be routed to the XHCI controller. I am reluctant to do that because the XHCI controller uses more system memory than the EHCI controller.

**Comment by 01e3** [comment]
Not sure if it changes much, but I think it is C612 and there are 12 USE ports total:
 - 4xUSB 3.0 front <- this is where Logitech Unifying received is plugged - technically I don't have a kbd linked (only mouse), but this is a HID device supporting both KBD / mouse
 - 4xUSB 3.0 back
 - 2xUSB 2.0 back <- this is where the kbd is plugged
 - 2xUSB 3.0 Internal

Also note that according to lsusb/lsusb.py (attached earlier) there are is also a TUSB8041 4-Port Hub:
```
  3-13              0451:8142 09 1IF  [USB 2.10,   480 Mbps,   0mA] (Texas Instruments, Inc. TUSB8041 4-Port Hub 32001849326B) hub
  4-4               0451:8140 09 1IF  [USB 3.00,  5000 Mbps,   0mA] (Texas Instruments, Inc. TUSB8041 4-Port Hub) hub
```

However, it does not look like it is used for supporting the keyboard?

**Comment by martinwhitaker** [comment]
According to the Intel website, the C612 is the sole member of the C610 chipset family. The PCH chip has 14 USB ports, but they aren't necessarily all used on a particular motherboard. There is a rate-matching hub attached to each EHCI controller - those are the 6 port and 8 port hubs listed in your UEFI screenshot. The TI 4-port hub has also been detected in that screenshot, along with two keyboard devices, which will be your keyboard and your Logitech receiver.

The BIOS appears to have disabled the rate-matching hubs when booted in legacy mode, but I don't know how.

**Comment by martinwhitaker** [comment]
Was your hpz440-lsusb.py.txt obtained after booting in legacy mode or in UEFI mode? It would be useful to know if Linux detects the hubs attached to the EHCI controller when booted in legacy mode.

**Comment by 01e3** [comment]
Linux was booted in legacy mode, via PXE.

**Comment by 01e3** [comment]
If it helps, I can also provide "lspci -x" or add some "debug" printks to the kernel, just let me know.

**Comment by martinwhitaker** [comment]
I still have no idea how to fix this, but the latest code defaults to using legacy keyboard emulation when booted in legacy mode, which should mask this issue.

**Comment by 01e3** [comment]
Indeed, it does!

I wonder if we can just close it as "not planned" unless there is a value in keeping this open and try to fix it?
