### ISSUE TITLE
unconventional serial console argument parsing

### ISSUE THREAD

**Issue by ajschorr** [memtest86plus/memtest86plus#64]
Hi,

In app/config.c:parse_serial_params, there's a mapping implemented from a single-digit
number to the actual baud rate of the serial console:

```
       switch (params[6])
        {
            default:
                return;
            case '0':
                tty_params_baud   = 9600;
                tty_update_period = 5;
                break;
            case '1':
                tty_params_baud   = 19200;
                tty_update_period = 4;
                break;
            case '2':
                tty_params_baud   = 38400;
                tty_update_period = 3;
                break;
            case '3':
                tty_params_baud   = 57600;
                tty_update_period = 3;
                break;
            case '4':
                tty_params_baud   = 115200;
                tty_update_period = 2;
                break;
        }
```

So whereas a typical linux kernel would be booted with "console=ttyS0,57600", this
code seems to require "console=ttyS0,3" instead. Previous versions of memtest
such as 5.01 and 5.31 used the normal syntax console=ttyS0,57600. Is there a 
reason that it's desirable to switch to this incompatible mapping? Is it just for
ease of argument parsing? I don't think it should be too hard to come up with 
a patch that allows the use of the standard "ttyS<n>,<speed>" syntax. I can whip
up a patch if needed, if it might be accepted.

Thanks for the work you're doing,
Andy

**Comment by x86fr** [comment]
OK, I will change that later today. 9600/38400/57600/115200 should be enough for 99.9% of cases, so I'll just switch on the first digit.

**Comment by ajschorr** [comment]
Thank you. That will simplify the generation of grub configuration files. I haven't used anything other than 115200 or 57600 in ages.

**Comment by x86fr** [comment]
Done. The readme will be updated when Beta 2 is released.
