### ISSUE TITLE
serial console support not working when invoked from grub

### ISSUE THREAD

**Issue by ajschorr** [memtest86plus/memtest86plus#66]
When I run current memtest.efi from grub with a command-line argument of console=ttyS0,115200,
I do not see any output in the serial console. I have no evidence that this used to work in v6 beta1,
but I really don't know, since that version doesn't work at all for me when run from grub. When I
run v6 beta in trace mode, I see nothing in the serial console, so I'm guessing it was broken in
that version as well (but with console=ttyS0,4 for the old v6 beta1 version).

**Comment by x86fr** [comment]
What about others arguments like `nosmp`? Is it a global issue with any parameter or just the `console` parameter?

**Comment by ajschorr** [comment]
Other arguments like nosmp and nobench and trace work OK, so it's just the serial console that's the problem. Another user reported that serial support works OK if enable_tty=true is precompiled into the binary. I will try that.

**Comment by ajschorr** [comment]
I can confirm that if I compile HEAD with patched enable_tty = true and run from grub with an argument
of "nosmp", that it works OK and I can finally see memtest running in a serial console (with updates
every 2 seconds). I suppose that app/config.c:parse_serial_params is either not grokking the argument
properly or setting enable_tty to true too late in the game.

**Comment by ajschorr** [comment]
app/main.c:global_init calls tty_init before calling config_init. Isn't that the source of the problem?

Also, why does parse_serial_params start with a test for (strncmp(params, "ttyS", 5) == 0)? 
Shouldn't it be (strncmp(params, "ttyS", 4) != 0)? Maybe I haven't had enough coffee yet.

**Comment by ajschorr** [comment]
Thanks. That looks like it should fix it, although I still don't know what you're going for with this initial test:

`    // No TTY port passed, use default ttyS0
    if (strncmp(params, "ttyS", 5) == 0) {
        return;
    }`

That's just a quick exit if the argument is "console=ttyS". Why is that interesting?
Don't you mean "if (strncmp(params, "ttyS", 4) != 0)", i.e. bail out if the
argument does NOT start with ttyS?

What happens if the argument is "console=junk1,9600"? Do you really want
to accept that as being equivalent to "console=ttyS0,9600"? Not that it
matters much. For any sane argument, the function should work, but that's
a weird test.

**Comment by x86fr** [comment]
As long as you have the console argument passed, no matter the parameters, it probably means you want the console enabled.

> That's just a quick exit if the argument is "console=ttyS". Why is that interesting?

This had been added to bypass a script failure while creating grub arguments from a big OEM validation factory.

> What happens if the argument is "console=junk1,9600"? Do you really want to accept that as being equivalent to "console=ttyS0,9600"?

Yes. The idea is to allow case-sensitive variations like `TTYS`, `ttys`, `TTYs`, etc. without adding too much code (string manipulation are costly in code size).

Let us know if it now works correctly when you can try in real-world (nightly builds will be available on [memtest.org](url) tomorrow)

**Comment by ajschorr** [comment]
I already tested that it works, as long as I add "nosmp". Thanks for fixing this.

**Comment by x86fr** [comment]
Thanks for your help!
