### ISSUE TITLE
32 bit ISO not booting on Fujitsu S400

### ISSUE THREAD

**Issue by tatokis** [memtest86plus/memtest86plus#67]
I have a Fujitsu Siemens [Futro S400](https://www.parkytowers.me.uk/thin/Futro/s400/) (Geode NX1500, SiS 741CX) and attempting to boot the 32 bit ISO from either the website, or manually built, results in the system rebooting endlessly. No errors are visible (on screen or over serial, although I don't know how one would pass the console param without grub).

Interestingly enough, the manually built 32 bit grub ISO boots fine, and memtest runs correctly (linux and linux16).

The normal iso was built and written to the USB device like this:
```
$ cd build32
$ make iso -j32
$ sudo dd if=memtest.iso of=/dev/sdi conv=fsync
```

The grub iso:
```
$ cd build32
$ make -j32 -i grub-iso
$ sudo dd if=grub-memtest.iso of=/dev/sdi conv=fsync
```

Worth noting that the grub iso build errors out with
```
cp: cannot stat '/usr/lib/grub/i386-efi/*.mod': No such file or directory
```
however that is most likely because I do not have i386 grub efi installed, but everything else functions correctly, and this system is too old to support EFI.

As mentioned, using the grub iso, it runs with the linux and linux16 commands, but not with linux32, as grub returns:
```
error: can't find command ` linux32'.
```
That might also be an issue on my end though/related to efi.
Last tested and reproduced with `v6.00-beta1-8-g722b1b2`.

![mt86pv6](https://user-images.githubusercontent.com/6003656/168119431-e57f59e1-6e15-4e47-83cd-b5f8530e2d37.png)

**Comment by x86fr** [comment]
Quite odd hardware here. I love it :)

Can you try to create the USB Flash Drive with the Windows creation tool?
Also, if you have an option named "Antivirus Protection" in your bios, try disabling it.

PS: You need the `grub-efi-ia32-bin` package to build the 32-bit Grub ISO.

**Comment by martinwhitaker** [comment]
Using your working ISO, could you enable tracing (either using the "trace" option on the boot command line or via the configuration menu at startup) and attach a screenshot of the initial trace output (up to the point the scroll lock kicks in).

I assume you patched the Makefile to get past the missing GRUB EFI files. That's fine - it won't affect legacy boot.

See the comment in the Makefile regarding the linux32 command.

**Comment by tatokis** [comment]
@x86fr 

> Can you try to create the USB Flash Drive with the Windows creation tool?

I do not have access to a Windows machine, and I found qemu usb passthrough to be unreliable in the past, so I'm not sure if using a VM to do it would provide any meaningful insight. If you believe that's okay, I'll try it.

> Also, if you have an option named "Antivirus Protection" in your bios, try disabling it.

There is only a virus warning option, and it's already disabled.

> PS: You need the grub-efi-ia32-bin package to build the 32-bit Grub ISO.

Thanks! I didn't install it as I assumed it wouldn't be required for legacy boot. I'll install it anyway, just so that make doesn't throw errors.

@martinwhitaker 
![memtesttrace](https://user-images.githubusercontent.com/6003656/168314067-53405694-4b22-463d-874c-f9472e50d109.png)

I noticed that if I boot with `console=ttyS0 trace`, I don't actually get the trace in the serial output. It just remains blank. Not sure if this is a separate bug, but I thought my serial port was not functioning. It only starts rendering after I hit space to unlock scrolling.

> I assume you patched the Makefile to get past the missing GRUB EFI files. That's fine - it won't affect legacy boot.

I used `-i` in make to ignore the error. The grub iso is built successfully and boots (as that's the only one I can use), but I mentioned it as I wasn't sure if it was related to linux32.

> See the comment in the Makefile regarding the linux32 command.

I hadn't looked at the makefile before, but I see now. Thank you!

**Comment by martinwhitaker** [comment]
Thanks for the screenshot. That shows your machine has sufficient free memory below 1MB, so that's not the problem.

**Comment by tatokis** [comment]
Replying so that the issue doesn't get closed. It still happens on 1278f026176cfddd12cc1092ec51e80bec1f3192.

**Comment by martinwhitaker** [comment]
Following the link to [Futro S400](https://www.parkytowers.me.uk/thin/Futro/s400/) you gave, in the Firmware section I read

> My standard Tiny Core 4.6.2 with Syslinux as the boot loader was ignored by the BIOS which just loaded Windows XPe. An alternative pen drive which has Grub installed as the boot loader worked. I haven't yet investigated to see what it doesn't like about syslinux.

so it seems we aren't alone.

One possibility is that the BIOS doesn't support the EDD (LBA) extensions for loading data from disk, although I would find that surprising as those extensions were introduced in 1997.

**Comment by tatokis** [comment]
I'm not sure that's the case. With the flash drive connected, it seems to attempt to boot and then resets (and goes through POST again). Without the flash drive connected (and no OS on the CF card in both cases), it complains with "DISK BOOT FAILURE [...]".

I think if the issue was the one described above, it'd always throw the disk boot failure message (effectively ignoring the flash drive).

**Comment by martinwhitaker** [comment]
When booting from a flash drive, the BIOS will load the boot sector, which on the memtest.iso contains the code from boot/mbr.c. That code then loads the rest of the Memtest86+ program. When I created the PCMemTest fork, I chose not to support really ancient hardware, so the code in boot/mbr.c uses the EDD extensions and doesn't include a fallback.

The boot sector on the grub-memtest.iso comes from GRUB, and does include a fallback to the older BIOS services.

**Comment by tatokis** [comment]
That makes sense. I was referring to the symptom of it ignoring the USB device entirely, as that is not the case here.

That said, do the EDD extensions apply only to USB? I wrote the mt86+ iso (without grub) to the CF card and it booted fine from it. If so I guess the issue can be closed.
