### ISSUE TITLE
Truncated SPD information and wrong date for DDR2

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#68]
I tested v6.00 Beta 1 on Dell PowerEdge 840 and while it works, the SPD data is wrong.

![dell-poweredge840-wrong-SPD-data](https://user-images.githubusercontent.com/105136494/168406644-66635c00-e3a4-4ca3-840a-d1e796b467c7.png)

As you can seen, for the lines where there is mfd date provided, the last character is truncated.

However, the date is missing for 2 of the dimms, but for the two where it is present, it is wrong - W11'13.

```
# egrep '(Part Number|Manufacturer|Manufacturing Date)'  decode-dimm-pe840 |sed 's/.*   //'|xargs -n 4
Micron Technology 18HTF25672AZ-80EH1 2011-W13
Micron Technology 18HTF25672AZ-80EH1 2010-W37
Micron Technology 18HTF25672AZ-80EH1 2010-W37
Micron Technology 18HTF25672AZ-80EH1 2011-W13
```

As you can see - week and year seems to be swapped, which probably also explains why only  W11'13 is reported.

I looked at the code and it seems the indices in the parse_spd_ddr2() function are swapped:

```
    uint8_t bcd = get_spd(smb_idx, slot_idx, 94);
    spdi.fab_year = bcd - 6 * (bcd >> 4);

    bcd = get_spd(smb_idx, slot_idx, 93);
    spdi.fab_week = bcd - 6 * (bcd >> 4);

```
Interestingly - it is correct for parse_spd_ddr:
```
    uint8_t bcd = get_spd(smb_idx, slot_idx, 93);
    spdi.fab_year = bcd - 6 * (bcd >> 4);

    bcd = get_spd(smb_idx, slot_idx, 94);
    spdi.fab_week = bcd - 6 * (bcd >> 4);
```

Also, since we are here - any chance to change the date format to ISO 8601 - "YYYY-Www", which is also what decode-dimms uses? 

https://xkcd.com/1179/
https://en.wikipedia.org/wiki/ISO_8601#Week_dates

**Comment by 01e3** [comment]
How about:


![dell-poweredge840-ok-SPD-data](https://user-images.githubusercontent.com/105136494/168408994-f833c093-0390-4274-b945-a80f4ca85cb3.png)


```

diff --git a/system/smbus.c b/system/smbus.c
index 778590f..ced5a29 100644
--- a/system/smbus.c
+++ b/system/smbus.c
@@ -172,7 +172,7 @@ static void print_spdi(spd_info spdi, uint8_t lidx)
     uint16_t i;
 
     // Print Slot Index, Module Size, type & Max frequency (Jedec or XMP)
-    curcol = printf(LINE_SPD+lidx, 0, " - Slot %i : %kB %s-%i",
+    curcol = printf(LINE_SPD+lidx, 0, " Slot %i: %kB %s-%i",
                     spdi.slot_num,
                     spdi.module_size * 1024,
                     spdi.type,
@@ -191,7 +191,7 @@ static void print_spdi(spd_info spdi, uint8_t lidx)
     }
 
     // Print Manufacturer from JEDEC106
-    for (i = 0; i < JEP106_CNT ; i++) {
+    for (i = 0; i < JEP106_CNT; i++) {
 
         if (spdi.jedec_code == jep106[i].jedec_code) {
             curcol = printf(LINE_SPD+lidx, curcol, " - %s", jep106[i].name);
@@ -205,13 +205,18 @@ static void print_spdi(spd_info spdi, uint8_t lidx)
     }
 
     // Print SKU
+    if (spdi.sku_len)
+      curcol++;
+
     for(i = 0; i < spdi.sku_len; i++) {
-        printc(LINE_SPD+lidx, ++curcol, spdi.sku[i]);
+        printc(LINE_SPD+lidx, curcol++, spdi.sku[i]);
     }
 
     // Print Manufacturing date (only if valid)
     if (curcol <= 72 && spdi.fab_year > 1 && spdi.fab_year < 32 && spdi.fab_week < 53) {
-        curcol = printf(LINE_SPD+lidx, curcol, " (W%02i'%02i)", spdi.fab_week, spdi.fab_year);
+        curcol = printf(LINE_SPD+lidx, curcol, " %02i%02i-W%02i",
+	                spdi.fab_year >= 80 ? 19 : 20,
+	                spdi.fab_year, spdi.fab_week);
     }
 
     // Populate global ram var
@@ -865,10 +870,10 @@ static spd_info parse_spd_ddr2(uint8_t smb_idx, uint8_t slot_idx)
         }
     }
 
-    uint8_t bcd = get_spd(smb_idx, slot_idx, 94);
+    uint8_t bcd = get_spd(smb_idx, slot_idx, 93);
     spdi.fab_year = bcd - 6 * (bcd >> 4);
 
-    bcd = get_spd(smb_idx, slot_idx, 93);
+    bcd = get_spd(smb_idx, slot_idx, 94);
     spdi.fab_week = bcd - 6 * (bcd >> 4);
 
     spdi.isValid = true;

```

**Comment by x86fr** [comment]
One of the commit in PR #44 is referencing the week/year swap. I'm working on a big optimization/bug fixes of the spd functions for beta 2. Probably by the end of next week.

**Comment by debrouxl** [comment]
01e3: this patch looks good to me and can be sent as a PR (for better authorship attribution to you) after removing the `&& spdi.fab_year > 1` test, which is another bug I've fixed on a commit not integrated yet (fuzzing branch). I noticed it when printing the SPD data from a RAM stick manufactured in 2000. Please reference me as `Co-developed-by: ` inside the commit message :)

Sam: does your optimization+fix+development work leave the door open to the implementation of older AMD, Nvidia and SiS SMBus controllers whose PCI IDs I've listed in the current first commit of #44 ? I still really don't think that maintainers should strive to implement support for all of them, but 1) there's no point in making it harder for contributors to do so by making some form of reverse refactoring a prerequisite and 2) as a matter of fact, implementing support for 1039:0016 would - well, hopefully, modulo SMBus access quirks - provide a way for me to test the SDRAM SPD decoder live on my K7S5A, rather than offline through a CLI program acting on a copy of the SPD data.

**Comment by x86fr** [comment]
> Sam: does your optimization+fix+development work leave the door open to the implementation of older AMD, Nvidia and SiS SMBus controllers whose PCI IDs I've listed in the current first commit of https://github.com/memtest86plus/memtest86plus/pull/44 ?

Yes. The goal is to avoid obfuscation by removing unnecessary macro, functions pointers, etc, while lowering code footprint by removing unused strings and excess of repetitions.

**Comment by debrouxl** [comment]
Alright. By all means, if you produce something smaller than my current approach for optimizing `smbcontrollers[]` (for every entry, 12 bytes + reloc on x86 / 16 bytes + reloc on x86_64), the target being 8 bytes per entry, and more maintainable than a pure ASM declaration, go for it :)

**Comment by 01e3** [comment]
debrouxl: Sure, happy to send a patch.

Just one more question regarding date handling - do we also want to remove "spdi.fab_year < 32" check to support 19[89]x? Or at least allow 199x? I think SPD was introduced in mid 90s?

**Comment by debrouxl** [comment]
On the one hand, I wouldn't forego the check entirely, and use something along the lines of `(spdi.fab_year < 32 || spdi.fab_year > 95)`. On the other hand, I don't know the right upper bound. On my computers, I haven't yet been able to see a SPD data dump from a device produced before 2000. 
Sam ?

**Comment by x86fr** [comment]
1996

**Comment by debrouxl** [comment]
So `(spdi.fab_year < 32 || (spdi.fab_year > 95 && spdi.fab_year <= 99))`, I guess.
