### ISSUE TITLE
SMBus: support for PIIX4 I2C controller not added back yet

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#69]
At the time of this writing, support for the family of PIIX4 controllers hasn't been imported back into the memtest86+ 6.00-pre repository. Such controllers are used on a number of ATI/AMD chipsets, even mildly recent ones. Therefore, here's a tracking issue for this matter.
Every day gets us closer to the release, so unless Sam's working on it as part of the SMBus / SPD rewrite mentioned in #68 , it might well not be a task for 6.00.

The Linux driver (drivers/i2c/busses/i2c-piix4.c) shows that multiple models of the PIIX4 family have various quirks and behavioural changes depending on the device revision...

**Comment by x86fr** [comment]
Added in commit e0cee8e2c3f6874d1c6a4d22156b5feab1d7f3e5

**Comment by debrouxl** [comment]
FWIW, the current form of `piix4_get_smb()` is enough to display the SPD data on ASUS RS904A server with 1002:4385:
![memtest86plus_smb_rs904a_20220520](https://user-images.githubusercontent.com/8375/169593621-2cf05f80-e2e3-4e68-8719-06d5660efdde.png)
which matches
![bios_smb_rs904a_20220520](https://user-images.githubusercontent.com/8375/169593736-a838e167-8dce-4e0a-be90-479f00110bd0.png)
and
![post_smb_rs904a_20220520](https://user-images.githubusercontent.com/8375/169593760-f3176f32-717f-44f0-8923-bdb61ba98734.png)
This server has 4 sockets x 4 x 16 GB RAM, but even the BIOS and the POST summary screen only display a single socket's RAM information at once.

However, it does not on the Dell PowerEdge R815, which is also equipped with 1002:4385. Probably a newer revision ID, and on another day, I should try associating `amd_sb_get_smb()` instead of `piix4_get_smb()` to 1002:4385, right ?
The version of `piix4_get_smb()` in https://github.com/anphsw/memtest86/blob/master/spd.c also contains a revision ID check, but that wouldn't be necessary here as long as `amd_sb_get_smb()` works.

Of course, both servers have survived later reboots, and the amount of memory is still correct ;)

**Comment by x86fr** [comment]
I'm working on AMD SB (0x4385). 

Multi Sockets servers often uses proprietary way to access SPD, so supporting them will probably require complex quirks (especially for Behemoths like the KGPX-Q32).

**Comment by x86fr** [comment]
> The version of `piix4_get_smb()` in https://github.com/anphsw/memtest86/blob/master/spd.c also contains a revision ID check, but that wouldn't be necessary here as long as `amd_sb_get_smb()` works.

This anphsw code is wrong. I'm testing a lot of motherboard with 1002:4385 and I just found one with SMBus RevID = 0x42 (ASRock C70M1). The specific code written there does not work (but the standard sb amd code do work as expected).
