### ISSUE TITLE
Better version handling / reporting

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#75]
With memtest86+ using the same headers (including the EFI stub) as Linux, the image files are recognized as a Linux kernel, which also applies to the "file" tool:

```
$ file memtest.efi memtest.bin
memtest.efi: Linux kernel x86 boot executable bzImage, version ▒fHdrS\014\002, RW-rootFS,
memtest.bin: Linux kernel x86 boot executable bzImage, version ▒fHdrS\014\002, RW-rootFS,
```

However, instead of the version, we get "some garbage". This is because value of kernel_version field is set to 0:
```
kernel_version:
        .word   0
```
so instead of pointing to the version string, it points to the header itself...

Does a patch like the one below look acceptable? It provides a single place for managing the version, and...:

```
$ file memtest.bin memtest.efi
memtest.bin: Linux kernel x86 boot executable bzImage, version Memtest86+ v6.00b1, RW-rootFS,
memtest.efi: Linux kernel x86 boot executable bzImage, version Memtest86+ v6.00b1, RW-rootFS,
```

Note that I added version.h to boot/ so the Makefile files don't need to be changed, but app/ or system/ can be also used if more appropriate.

```
diff --git a/app/display.c b/app/display.c
index eb31dae..0669164 100644
--- a/app/display.c
+++ b/app/display.c
@@ -27,6 +27,8 @@
 
 #include "display.h"
 
+#include "version.h"
+
 //------------------------------------------------------------------------------
 // Constants
 //------------------------------------------------------------------------------
@@ -83,7 +85,7 @@ void display_init(void)
     set_foreground_colour(BLACK);
     set_background_colour(WHITE);
     clear_screen_region(0, 0, 0, 27);
-    prints(0, 0, "     Memtest86+ v6.00b1");
+    prints(0, 0, "     Memtest86+ v" VERSION);
     set_foreground_colour(RED);
     printc(0, 14, '+');
     set_foreground_colour(WHITE);
@@ -121,7 +123,7 @@ void display_init(void)
     set_background_colour(WHITE);
     clear_screen_region(ROW_FOOTER, 0, ROW_FOOTER, SCREEN_WIDTH - 1);
     prints(ROW_FOOTER, 0, " <ESC> Exit  <F1> Configuration  <Space> Scroll Lock");
-    prints(ROW_FOOTER, 64, "6.00.");
+    prints(ROW_FOOTER, 69-sizeof(VERSION), VERSION ".");
     prints(ROW_FOOTER, 69, GIT_HASH);
 #if TESTWORD_WIDTH > 32
     prints(ROW_FOOTER, 76, ".x64");
diff --git a/boot/setup.S b/boot/setup.S
index 04bc5d9..507cfc1 100644
--- a/boot/setup.S
+++ b/boot/setup.S
@@ -18,6 +18,7 @@
 #define __ASSEMBLY__
 
 #include "boot.h"
+#include "version.h"
 
 #define	BOOT_PARAMS_START	(SETUP_SECS * 512)
 #define	BOOT_PARAMS_END		(BOOT_PARAMS_START + 4096)
@@ -41,7 +42,7 @@ realmode_swtch:
 start_sys_seg:
 	.word	0x1000
 kernel_version:
-	.word	0
+	.word	memtest_version-512
 type_of_loader:
 	.byte	0
 loadflags:
@@ -385,6 +386,9 @@ idt_descr:
 	.word	0			# idt limit=0
 	.long	0			# idt base=0
 
+memtest_version:
+	.asciz	"Memtest86+ v" VERSION
+
 # Pad to the declared size.
 
 	.org	(SETUP_SECS*512)
diff --git a/boot/version.h b/boot/version.h
new file mode 100644
index 0000000..1494952
--- /dev/null
+++ b/boot/version.h
@@ -0,0 +1,7 @@
+// SPDX-License-Identifier: GPL-2.0
+#ifndef VERSION_H
+#define VERSION_H
+
+#define VERSION "6.00b1"
+
+#endif
```

**Comment by x86fr** [comment]
- To avoid having 2 files with version numbers, it's probably better to use or rework github.h (by renaming it to version.h and add another define). 
- The "v" before number is useless (it was there until Memtest86+ v5.31 but has been removed with Memtest86+ 6.00)
- Any change in .S files (especially if only cosmetic) must be tested on a wide scale as they can introduce side-effects.
- We need to be sure this have no conflict with PR #34, which is the top priority.

**Comment by 01e3** [comment]
Thanks!

Sure, can drop "v", but it has been here already: https://github.com/memtest86plus/memtest86plus/blob/d901f9e8a1524e898d78828df7b60cb839270f14/app/display.c#L86

Regarding github.h, it does not look like it is in the main branch, should I be looking for a different one?

Good point about proper testing and the priority. Just a note that it does not change any of the assembly code and uses spaces that has been otherwise filled with \0,  and IMO - seems less risky than https://github.com/memtest86plus/memtest86plus/commit/f98ceb1613f01efd58ac62de158c000d6096d773

That said, this is indeed a cosmetic change. In case we may not want to risk this in 6.00, would putting this behind #ifdef (which could be removed in removed in a later version) be an acceptable compromise?

**Comment by x86fr** [comment]
> Sure, can drop "v", but it has been here already:

Right. I can't remember if it's a mistake or not. Well, it's doesn't really matter. 
Anyway, if this string is not fixed anymore, you have to do some math to center it properly.

> Regarding github.h, it does not look like it is in the main branch, should I be looking for a different one?

github.h is generated by Makefile. If we switch to a permanent version.h file, we must change Makefile to write a define with the latest git commit in that file, and then remove it after compilation.

> Good point about proper testing and the priority. Just a note that it does not change any of the assembly code and uses spaces that has been otherwise filled with \0, and IMO - seems less risky than [f98ceb1](https://github.com/memtest86plus/memtest86plus/commit/f98ceb1613f01efd58ac62de158c000d6096d773)

I don't think this will create any issue with the code by itself, but maybe with bootloader (Grub, iPXE, ...) trying to detect which version of the kernel it is about to load. 

> That said, this is indeed a cosmetic change. In case we may not want to risk this in 6.00, would putting this behind #ifdef (which could be removed in removed in a later version) be an acceptable compromise?

We're still in beta phase, so it's probably the right time to test stuff like this.

**Comment by 01e3** [comment]
Sam, I'm probably missing something obvious, but could you be more specific regarding github.h?

There is no single match for https://github.com/memtest86plus/memtest86plus/search?q=github.h

I also checked https://github.com/memtest86plus/memtest86plus/archive/refs/tags/v6.00-beta1.tar.gz, there are no more reference to the version:

```
$ grep -R '6\.00' memtest86plus-6.00-beta1
memtest86plus-6.00-beta1/app/display.c:    prints(0, 0, "     Memtest86+ v6.00b1");
memtest86plus-6.00-beta1/app/display.c:    prints(ROW_FOOTER, 64, "6.00.");

$ find memtest86plus-6.00-beta1|grep vers
<empty>

$ find memtest86plus-6.00-beta1|grep gith
<empty>
```

**Comment by x86fr** [comment]
Sorry, the correct name is `githash.h`

**Comment by martinwhitaker** [comment]
This is actually a bug in the `file` command - it shouldn't be dereferencing the kernel_version field when it is set to zero (see https://www.kernel.org/doc/Documentation/x86/boot.txt). But I don't object to the change.

**Comment by debrouxl** [comment]
This one slipped through the cracks.

**Comment by 01e3** [comment]
Still on my todo list, once I find some more time...  Unfortunately, I cannot re-open the bug myself...

**Comment by x86fr** [comment]
Implemented. Tks @01e3!

**Comment by 01e3** [comment]
Ah, nice, thanks!

**Comment by 01e3** [comment]
Just one question: didn't we decide to get rid of that "v" prefix? i.e. "v6.01" -> "6.01", for both UI reporting and the header file?
