### ISSUE TITLE
minor issue:  100°C doesn't display correctly, overflows its field

### ISSUE THREAD

**Issue by cgull** [memtest86plus/memtest86plus#78]
I have an old iMac that is giving me memory problems, and its CPU is rather hot:
![IMG_8546](https://user-images.githubusercontent.com/1934797/169640323-326fb654-52ae-4d54-b602-08e66bc5d622.jpg)
I haven't looked at the code but it looks like three-digit temperatures aren't being handled properly.

**Comment by x86fr** [comment]
Got it. I will commit a patch later today. It will be available tomorrow ok the nightly builds.

**Comment by x86fr** [comment]
Fixed with commit 0adcdfa160e39679de05319a6c0fd5393a3c0e69
