### ISSUE TITLE
Selecting the error reporting mode through the command line

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#83]
At the moment, this is another configuration option which can only be set through the menu.

**Comment by martinwhitaker** [comment]
Do we really want multiple issues for this? Memtest86+ doesn't currently have a proper CLI - the boot command line options are only there to work around hardware quirks that would otherwise prevent you getting to the interactive configuration menu. If this is a desired feature, it would be best considered as a whole rather than piecemeal.

**Comment by x86fr** [comment]
Agree. Also, I can't find a way to easily pass arguments to the efi binary loaded by iPXE. The config menu is much more efficient for complex settings.

**Comment by x86fr** [comment]
IMO, to avoid flooding the issues list, we should convert all these enhancements ideas without an active developer working on it to discussion (#7, #58, #72,#73, #83 and maybe some others). So users can vote and we will spend some time on the most popular ones.

**Comment by debrouxl** [comment]
This one was the last of the "scriptability" tracking issues. Scriptability is the correct way to provide the best building blocks for automated, non-interactive regression testing, instead of some more brittle TTY-based workaround for insufficient scriptability, which would involve waiting a bit, then sending keypresses. Some of these issues, especially #82 and #83 , are easy to implement.

I posted them because building a proper CLI for memtest86+ is _far_ less complex (and yields much smaller code) than the alternatives, e.g. reading a configuration file from a FS on an internal or external mass storage device, or getting configuration information from some form of network server. For a portable implementation of these, rewriting the memory testing as a task in an embedded RTOS would be an option...

The command line length limit is high, as 300+ characters routinely work ( https://clonezilla.org/livehd.php et. al) and we don't need that many for reasonable inputs to #7 + #58 + #72 + #82 + #83 on the same command line :)

**Comment by x86fr** [comment]
- Considering that there is a demand from users for scripting that way, we should regroup all of these to a single "scripting" issue with sub-requests
- reading/writing on a FS is the ultimate solution and will be needed at some point.
- Still convert #7 (and future ones like this one) to discussion so we can get feedbacks from users with the voting system
