### ISSUE TITLE
Not showing "Cache" & "RAM" speed on AMD K6-2/500

### ISSUE THREAD

**Issue by Pintaiux** [memtest86plus/memtest86plus#87]
![K6-2@500](https://user-images.githubusercontent.com/20352277/169914342-32c96ed6-c7b4-4062-8513-b027bf23489b.jpeg)

**Comment by x86fr** [comment]
Currently, the benchmark is disabled when L2 is not detected. On your motherboard, the L2 is external so it's much more complex to detect. I will soon start working on Socket 4/5/7 CPUs to enhance these features on older platforms. 

Can you tell us the exact motherboard you're using?

**Comment by Pintaiux** [comment]
Asus P5A Rev1.04

**Comment by x86fr** [comment]
The latest commit should solve this issue (tested working on Asus P5A-B with K6-2/500)
