### ISSUE TITLE
"pass  complete .."  overlaps information

### ISSUE THREAD

**Issue by b-user** [memtest86plus/memtest86plus#94]
the phrase "pass  complete .." appeared in an unexpected place

[
![IMG_20220602_095812_proc_proc](https://user-images.githubusercontent.com/11581901/171572879-8ab9cc5d-129d-429b-a7b8-6c09c924cd68.jpg)
![IMG_20220602_095817_proc_proc](https://user-images.githubusercontent.com/11581901/171572884-3e0670be-92d1-4a26-a4f6-4fe6fef19d8c.jpg)
](url)

**Comment by x86fr** [comment]
Solved on Beta 3
