### ISSUE TITLE
build issue on hurd kernel

### ISSUE THREAD

**Issue by Fantu** [memtest86plus/memtest86plus#97]
Hi, debian have also a port with hurd kernel. I never used it but memtest86+ package support it and before v6 was built correctly.
On v6 the build fails on a boot part in assembly: https://buildd.debian.org/status/package.php?p=memtest86%2B&suite=experimental
https://buildd.debian.org/status/fetch.php?pkg=memtest86%2B&arch=hurd-i386&ver=6.00%7Ebeta2-1&stamp=1654254585&raw=0
I don't have knowledge with hurd kernel and assembly. Is there someone that have enough knowledge to fix the build on hurd easy/fast please? If is there nobody or is not easy/fast I'll probably drop hurd support.

**Comment by x86fr** [comment]
It's not very complex to solve but that requires some deep change to create a 100% 32-bit build (as there is no 64-bit hurd planned). Probably better to drop hurd for now.

**Comment by x86fr** [comment]
Seems we can solve this by using `ifdef/endif` around specific 64-bit code like `.code64` and by using `.byte` opcodes instead of "literal" instructions. (https://debbugs.gnu.org/cgi/bugreport.cgi?bug=41982). But that will render the code harder to read and to change. 

Probably not needed at this time (hurd is really a niche currently).

**Comment by debrouxl** [comment]
Indeed, making that 32-bit x86 gas binary able to assemble x86_64 instructions would certainly be a better choice than patching various code bases to add several `ifdef/else/endif` blocks around `.code64` or ugly sequences of `.byte` - the usual way to work around assembler bugs or deficiencies - where needed.
Even if no 64-bit version of Hurd is planned, Hurd / gas / the Debian gas build for Hurd / etc. making it harder for users to target other OS from Hurd isn't going to make Hurd less unpopular.

**Comment by martinwhitaker** [comment]
Marking this as "won't fix", as we don't  want to add ugly workarounds for this niche use case.
